package hts.backend.entity;
// Generated 28/02/2017 11:04:15 AM by Hibernate Tools 5.2.0.Beta1

import hts.backend.entity.CexCitaPaciente;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * AdmAgendaCupos generated by hbm2java
 */
@Entity
@Table(name = "adm_agenda_cupos")
public class
AdmAgendaCupos implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	private int cupoId;
	private Integer status;
	private Integer turno;
	private AdmAgendaDetalle admAgendaDetalle;
	private Date fecha;
	private Date horaInicio;
	private Date horaFinal;
	private String tipoCupo;
	private Integer bloqueo;
	private AdmAgendaModelo admAgendaModelo;

//	private Set<CexCitaPaciente> cexCitaPacientesByCupoId = new HashSet<CexCitaPaciente>(0);

	public AdmAgendaCupos() {
	}

	public AdmAgendaCupos(int cupoId) {
		this.cupoId = cupoId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CUPO_ID", unique = true, nullable = false, precision = 5, scale = 0)
	public int getCupoId() {
		return this.cupoId;
	}

	public void setCupoId(int cupoId) {
		this.cupoId = cupoId;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AGENDA_DETALLE_ID", referencedColumnName = "AGENDA_DETALLE_ID")
	public AdmAgendaDetalle getAdmAgendaDetalle() {
		return this.admAgendaDetalle;
	}

	public void setAdmAgendaDetalle(AdmAgendaDetalle admAgendaDetalle) {
		this.admAgendaDetalle = admAgendaDetalle;
	}

	@Column(name = "ESTATUS", length = 10)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "TURNO", length = 10)
	public Integer getTurno() {
		return this.turno;
	}

	public void setTurno(Integer turno) {
		this.turno = turno;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA")
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HORA_INICIO")
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HORA_FINAL")
	public Date getHoraFinal() {
		return this.horaFinal;
	}

	public void setHoraFinal(Date horaFinal) {
		this.horaFinal = horaFinal;
	}

	@Column(name = "TIPO_CUPO", length = 10)
	public String getTipoCupo() {
		return this.tipoCupo;
	}

	public void setTipoCupo(String tipoCupo) {
		this.tipoCupo = tipoCupo;
	}

//	@OneToMany(mappedBy = "admAgendaCuposByCupoId")
//	public Set<CexCitaPaciente> getCexCitaPacientesByCupoId() {
//		return cexCitaPacientesByCupoId;
//	}
//
//	public void setCexCitaPacientesByCupoId(Set<CexCitaPaciente> cexCitaPacientesByCupoId) {
//		this.cexCitaPacientesByCupoId = cexCitaPacientesByCupoId;
//	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AGENDA_MODELO_ID", referencedColumnName = "AGENDA_MODELO_ID")
	public AdmAgendaModelo getAdmAgendaModelo() {
		return admAgendaModelo;
	}

	public void setAdmAgendaModelo(AdmAgendaModelo admAgendaModelo) {
		this.admAgendaModelo = admAgendaModelo;
	}


	@Column(name = "BLOQUEO", length = 10)
	public Integer getBloqueo() {
		return this.bloqueo;
	}

	public void setBloqueo(Integer bloqueo) {
		this.bloqueo = bloqueo;
	}

}
