package hts.backend.entity;
// Generated 28/02/2017 11:04:15 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * AdmAgendaModelo generated by hbm2java
 */
@Entity
@Table(name = "adm_agenda_modelo")
public class AdmAgendaModelo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer agendaModeloId;
	private CatTipoAgente catTipoAgente;
	private Integer status;
	private String nombre;
	private String descripcion;
	private Date fechaInicio;
	private Date fechaFin;
	private String cveSobrecupo;
	private Integer autorizaSobrecupo;
	private Integer extensible;
	private Integer facturable;
	private Integer cupoExtra;
	private Integer diasFestivos;
	private AdmHospital admHospital;
	private Integer maxPrestaciones;
	private Integer actorId;
	private Set<AdmAgendaDetalle> admAgendaDetalles = new HashSet<AdmAgendaDetalle>(0);

	public AdmAgendaModelo() {
	}

	public AdmAgendaModelo(Integer agendaModeloId, CatTipoAgente catTipoAgente, Integer status, String nombre, String descripcion,
			Date fechaInicio, Date fechaFin, int agendaDetalleId) {
		this.agendaModeloId = agendaModeloId;
		this.catTipoAgente = catTipoAgente;
		this.status = status;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
	}

	public AdmAgendaModelo(Integer agendaModeloId, CatTipoAgente catTipoAgente, Integer catStatus,AdmHospital  admHospital, String nombre, String descripcion,
			Date fechaInicio, Date fechaFin, String cveSobrecupo, Integer autorizaSobrecupo, Integer extensible,
			Integer facturable, Integer cupoExtra,Integer diasFestivos, Integer maxPrestaciones,Integer hospitalId, Integer actorId,
			Set<AdmAgendaDetalle> admAgendaDetalles, Integer status) {
		this.agendaModeloId = agendaModeloId;
		this.catTipoAgente = catTipoAgente;
		this.status = status;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.cveSobrecupo = cveSobrecupo;
		this.autorizaSobrecupo = autorizaSobrecupo;
		this.extensible = extensible;
		this.facturable = facturable;
		this.cupoExtra = cupoExtra;
		this.diasFestivos = diasFestivos;
		this.maxPrestaciones = maxPrestaciones;
		this.admHospital = admHospital;
		this.actorId = actorId;
		this.admAgendaDetalles = admAgendaDetalles;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
		@Column(name = "AGENDA_MODELO_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getAgendaModeloId() {
		return this.agendaModeloId;
	}

	public void setAgendaModeloId(Integer agendaModeloId) {
		this.agendaModeloId = agendaModeloId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_AGENTE_ID")
	public CatTipoAgente getCatTipoAgente() {
		return this.catTipoAgente;
	}

	public void setCatTipoAgente(CatTipoAgente catTipoAgente) {
		this.catTipoAgente = catTipoAgente;
	}

	@Column(name = "NOMBRE", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTATUS", precision = 22, scale = 0)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_INICIO", nullable = false, length = 7)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_FIN", nullable = false, length = 7)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "CVE_SOBRECUPO", length = 4)
	public String getCveSobrecupo() {
		return this.cveSobrecupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HOSPITAL_ID")
	public AdmHospital getAdmHospital() {
		return this.admHospital;
	}

	public void setAdmHospital(AdmHospital admHospital) {
		this.admHospital = admHospital;
	}

	public void setCveSobrecupo(String cveSobrecupo) {
		this.cveSobrecupo = cveSobrecupo;
	}

	@Column(name = "AUTORIZA_SOBRECUPO", precision = 22, scale = 0)
	public Integer getAutorizaSobrecupo() {
		return this.autorizaSobrecupo;
	}

	public void setAutorizaSobrecupo(Integer autorizaSobrecupo) {
		this.autorizaSobrecupo = autorizaSobrecupo;
	}

	@Column(name = "EXTENSIBLE", precision = 22, scale = 0)
	public Integer getExtensible() {
		return this.extensible;
	}

	public void setExtensible(Integer extensible) {
		this.extensible = extensible;
	}

	@Column(name = "FACTURABLE", precision = 22, scale = 0)
	public Integer getFacturable() {
		return this.facturable;
	}

	public void setFacturable(Integer facturable) {
		this.facturable = facturable;
	}

	@Column(name = "CUPO_EXTRA", precision = 22, scale = 0)
	public Integer getCupoExtra() {
		return this.cupoExtra;
	}

	public void setCupoExtra(Integer cupoExtra) {
		this.cupoExtra = cupoExtra;
	}

	@Column(name = "DIAS_FESTIVOS", precision = 22, scale = 0)
	public Integer getDiasFestivos() {
		return this.diasFestivos;
	}

	public void setDiasFestivos(Integer diasFestivos) {
		this.diasFestivos = diasFestivos;
	}

	@Column(name = "MAX_PRESTACIONES", precision = 2, scale = 0)
	public Integer getMaxPrestaciones() {
		return this.maxPrestaciones;
	}

	public void setMaxPrestaciones(Integer maxPrestaciones) {
		this.maxPrestaciones = maxPrestaciones;
	}

	@Column(name = "ACTOR_ID", precision = 5, scale = 0)
	public Integer getActorId() {
		return this.actorId;
	}

	public void setActorId(Integer actorId) {
		this.actorId = actorId;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admAgendaModelo")
	public Set<AdmAgendaDetalle> getAdmAgendaDetalles() {
		return this.admAgendaDetalles;
	}

	public void setAdmAgendaDetalles(Set<AdmAgendaDetalle> admAgendaDetalles) {
		this.admAgendaDetalles = admAgendaDetalles;
	}

}
