package hts.backend.entity;
// Generated 03-feb-2017 12:09:42 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * AdmAccion generated by hbm2java
 */
@Deprecated
@Entity
@Table(name = "adm_accion")
public class AdmAccion implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer accionId;
	private AdmModulo admModulo;
	private String nombre;
	private String descripcion;
	private Integer padreId;
	private Integer orden;
	private String urlVista;
	private Integer nivel;
	private Integer estatus;
	private Date fecha;
	private String usuario;
	private Set<AdmFuncion> admFuncions = new HashSet<AdmFuncion>(0);



	public AdmAccion() {
	}

	public AdmAccion(Integer accionId) {
		this.accionId = accionId;
	}

	public AdmAccion(Integer accionId, AdmModulo admModulo, String nombre, String descripcion, Integer orden,
			String urlVista, Integer nivel, Integer estatus, Date fecha, String usuario) {
		this.accionId = accionId;
		this.admModulo = admModulo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.orden = orden;
		this.urlVista = urlVista;
		this.nivel = nivel;
		this.estatus = estatus;
		this.fecha = fecha;
		this.usuario = usuario;
	}

	public AdmAccion( AdmModulo admModulo, String nombre, String descripcion, Integer orden,
			String urlVista, Integer nivel, Integer estatus, Date fecha, String usuario) {

		this.admModulo = admModulo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.orden = orden;
		this.urlVista = urlVista;
		this.nivel = nivel;
		this.estatus = estatus;
		this.fecha = fecha;
		this.usuario = usuario;
	}
	public AdmAccion(Integer accionId, AdmModulo admModulo, String nombre, String descripcion, Integer padreId,
			Integer orden, String urlVista, Integer nivel, Integer estatus, Date fecha, String usuario) {
		this.accionId = accionId;
		this.admModulo = admModulo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.padreId = padreId;
		this.orden = orden;
		this.urlVista = urlVista;
		this.nivel = nivel;
		this.estatus = estatus;
		this.fecha = fecha;
		this.usuario = usuario;
	}

	public AdmAccion(Integer accionId, AdmModulo admModulo, String nombre, String descripcion, Integer padreId,
			Integer orden, String urlVista, Integer nivel, Integer estatus, Date fecha, String usuario,
			Set<AdmFuncion> admFuncions
			) {
		this.accionId = accionId;
		this.admModulo = admModulo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.padreId = padreId;
		this.orden = orden;
		this.urlVista = urlVista;
		this.nivel = nivel;
		this.estatus = estatus;
		this.fecha = fecha;
		this.usuario = usuario;
		this.admFuncions=admFuncions;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ACCION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getAccionId() {
		return this.accionId;
	}

	public void setAccionId(Integer accionId) {
		this.accionId = accionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODULO_ID", nullable = false)
	public AdmModulo getAdmModulo() {
		return this.admModulo;
	}

	public void setAdmModulo(AdmModulo admModulo) {
		this.admModulo = admModulo;
	}

	@Column(name = "NOMBRE", nullable = false, length = 70)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "PADRE_ID", precision = 22, scale = 0)
	public Integer getPadreId() {
		return this.padreId;
	}

	public void setPadreId(Integer padreId) {
		this.padreId = padreId;
	}

	@Column(name = "ORDEN", nullable = false, precision = 22, scale = 0)
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "URL_VISTA", nullable = false, length = 300)
	public String getUrlVista() {
		return this.urlVista;
	}

	public void setUrlVista(String urlVista) {
		this.urlVista = urlVista;
	}

	@Column(name = "NIVEL", nullable = false, precision = 22, scale = 0)
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", nullable = false, length = 7)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "USUARIO", nullable = false, length = 20)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admAccion")
	public Set<AdmFuncion> getAdmFuncions() {
		return this.admFuncions;
	}

	public void setAdmFuncions(Set<AdmFuncion> admFuncions) {
		this.admFuncions = admFuncions;
	}


}
