package hts.backend.entity;
// Generated 27/03/2017 10:38:40 AM by Hibernate Tools 5.2.0.CR1

import hts.backend.entity.FacValidacionEvento;
import hts.backend.entity.FacturacionEvento;
import hts.backend.entity.PacAseguradora;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

//import java.util.HashSet;
//import java.util.Set;
//import javax.persistence.OneToMany;

/**
 * AdmCatAseguradora generated by hbm2java
 */
@Entity
@Table(name = "adm_cat_aseguradora")
public class AdmCatAseguradora implements java.io.Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private int aseguradoraId;
	private CatClasificacionFiscal catClasificacionFiscal;
	private NomCatMonedas nomCatTipoMonedac;
	private CatTipoAseguradora catTipoAseguradora;
	private String cve;
	private String nombre;
	private String descripcion;
	private String telefono;
	private String fiscalId;
	private String deudor;
	private String cuentaAsociada;
	private int valorDefault;
	private Date fechaRegistra;
	private String usuarioRegistro;
	private int estatus;
	//	private Set<PacConvenioAseguradora> pacConvenioAseguradoras = new HashSet<PacConvenioAseguradora>(0);
	private Set<PacAseguradora> pacAseguradoras = new HashSet<PacAseguradora>(0);
	private Set<FacturacionEvento> facturacionEventosByAseguradoraId;
	private Set<FacValidacionEvento> facValidacionEventosByAseguradoraId;
	private Set<CoreAseguradoraHospital> coreAseguradoraHospital = new HashSet<CoreAseguradoraHospital>(0);


	public void setFacturacionEventosByAseguradoraId(Set<FacturacionEvento> facturacionEventosByAseguradoraId) {
		this.facturacionEventosByAseguradoraId = facturacionEventosByAseguradoraId;
	}

	public AdmCatAseguradora() {
	}

	public AdmCatAseguradora(Integer aseguradoraId) {
		this.aseguradoraId = aseguradoraId;
	}

	public AdmCatAseguradora(int aseguradoraId, String cve, String nombre, String descripcion,
							 int valorDefault, Date fechaRegistra, String usuarioRegistro, int estatus) {
		this.aseguradoraId = aseguradoraId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.fechaRegistra = fechaRegistra;
		this.usuarioRegistro = usuarioRegistro;
		this.estatus = estatus;
	}

	public AdmCatAseguradora(int aseguradoraId, CatClasificacionFiscal catClasificacionFiscal, NomCatMonedas nomCatTipoMonedac, CatTipoAseguradora catTipoAseguradora, String cve, String nombre,
							 String descripcion, String telefono, String fiscalId, String deudor, String cuentaAsociada,
							 int valorDefault, Date fechaRegistra, String usuarioRegistro, int estatus,
							 Set<PacConvenioAseguradora> pacConvenioAseguradoras, Set<PacAseguradora> pacAseguradoras) {
		this.aseguradoraId = aseguradoraId;
		this.catClasificacionFiscal = catClasificacionFiscal;
		this.nomCatTipoMonedac = nomCatTipoMonedac;
		this.catTipoAseguradora = catTipoAseguradora;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.telefono = telefono;
		this.fiscalId = fiscalId;
		this.deudor = deudor;
		this.cuentaAsociada = cuentaAsociada;
		this.valorDefault = valorDefault;
		this.fechaRegistra = fechaRegistra;
		this.usuarioRegistro = usuarioRegistro;
		this.estatus = estatus;
//		this.pacConvenioAseguradoras = pacConvenioAseguradoras;
		this.pacAseguradoras = pacAseguradoras;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ASEGURADORA_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getAseguradoraId() {
		return this.aseguradoraId;
	}

	public void setAseguradoraId(int aseguradoraId) {
		this.aseguradoraId = aseguradoraId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLASIFICACION_FISCAL_ID", nullable = false)
	public CatClasificacionFiscal getCatClasificacionFiscal() {
		return this.catClasificacionFiscal;
	}

	public void setCatClasificacionFiscal(CatClasificacionFiscal catClasificacionFiscal) {
		this.catClasificacionFiscal = catClasificacionFiscal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_MONEDA_ID", nullable = false)
	public NomCatMonedas getNomCatTipoMonedac() {
		return this.nomCatTipoMonedac;
	}

	public void setNomCatTipoMonedac(NomCatMonedas nomCatTipoMonedac) {
		this.nomCatTipoMonedac = nomCatTipoMonedac;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_ASEGURADORA_ID", nullable = false)
	public CatTipoAseguradora getCatTipoAseguradora() {
		return this.catTipoAseguradora;
	}

	public void setCatTipoAseguradora(CatTipoAseguradora catTipoAseguradora) {
		this.catTipoAseguradora = catTipoAseguradora;
	}

	@Column(name = "CVE", nullable = false, length = 10)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "TELEFONO", length = 12)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "FISCAL_ID", length = 20)
	public String getFiscalId() {
		return this.fiscalId;
	}

	public void setFiscalId(String fiscalId) {
		this.fiscalId = fiscalId;
	}

	@Column(name = "DEUDOR", length = 20)
	public String getDeudor() {
		return this.deudor;
	}

	public void setDeudor(String deudor) {
		this.deudor = deudor;
	}

	@Column(name = "CUENTA_ASOCIADA", length = 20)
	public String getCuentaAsociada() {
		return this.cuentaAsociada;
	}

	public void setCuentaAsociada(String cuentaAsociada) {
		this.cuentaAsociada = cuentaAsociada;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, precision = 22, scale = 0)
	public int getValorDefault() {
		return this.valorDefault;
	}

	public void setValorDefault(int valorDefault) {
		this.valorDefault = valorDefault;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistra() {
		return this.fechaRegistra;
	}

	public void setFechaRegistra(Date fechaRegistra) {
		this.fechaRegistra = fechaRegistra;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

//
//	 @OneToMany(fetch = FetchType.LAZY, mappedBy = "admCatAseguradora")
//	public Set<PacConvenioAseguradora> getPacConvenioAseguradoras() {
//		return this.pacConvenioAseguradoras;
//	}
//
//	public void setPacConvenioAseguradoras(Set<PacConvenioAseguradora> pacConvenioAseguradoras) {
//		this.pacConvenioAseguradoras = pacConvenioAseguradoras;
//	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admCatAseguradora")
	public Set<PacAseguradora> getPacAseguradoras() {
		return this.pacAseguradoras;
	}

	public void setPacAseguradoras(Set<PacAseguradora> pacAseguradoras) {
		this.pacAseguradoras = pacAseguradoras;
	}

	@OneToMany(mappedBy = "admCatAseguradoraByAseguradoraId")
	public Set<FacturacionEvento> getFacturacionEventosByAseguradoraId() {
		return facturacionEventosByAseguradoraId;
	}

	@OneToMany(mappedBy = "admCatAseguradoraByAseguradoraId")
	public Set<FacValidacionEvento> getFacValidacionEventosByAseguradoraId() {
		return facValidacionEventosByAseguradoraId;
	}

	public void setFacValidacionEventosByAseguradoraId(Set<FacValidacionEvento> facValidacionEventosByAseguradoraId) {
		this.facValidacionEventosByAseguradoraId = facValidacionEventosByAseguradoraId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admCatAseguradora")
	public Set<CoreAseguradoraHospital> getCoreAseguradoraHospital() {
		return coreAseguradoraHospital;
	}

	public void setCoreAseguradoraHospital(Set<CoreAseguradoraHospital> coreAseguradoraHospital) {
		this.coreAseguradoraHospital = coreAseguradoraHospital;
	}
}
