package hts.backend.entity;
// Generated 28/02/2017 11:04:15 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * CatTipoConsulta generated by hbm2java
 */
@Entity
@Table(name = "adm_cat_tipo_consulta")
public class AdmCatTipoConsulta implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer tipoConsultaId;
	private String cve;
	private String nombre;
	private String descripcion;
	private Integer valorDefault;
	private Integer estatus;
	private Date fechaRegistro;
	private String usuario;
	private AdmHospital admHospital;
	private Integer hospitalId;
	private CatTipoVisita catTipoVisita;
	private Integer tipoVisitaId;

	private Set<AdmAgendaDetalle> admAgendaDetalles = new HashSet<AdmAgendaDetalle>(0);
	private Set<InstruccionVisita> instruccionVisita = new HashSet<InstruccionVisita>(0);

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "TIPO_CONSULTA_ID", unique = true, nullable = false, precision = 5, scale = 0)
	public Integer getTipoConsultaId() {
		return this.tipoConsultaId;
	}

	public void setTipoConsultaId(Integer tipoConsultaId) {
		this.tipoConsultaId = tipoConsultaId;
	}

	@Column(name = "CVE", nullable = false, precision = 5, scale = 0)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", precision = 1, scale = 0)
	public Integer getValorDefault() {
		return valorDefault;
	}

	public void setValorDefault(Integer valorDefault) {
		this.valorDefault = valorDefault;
	}


	@Column(name = "ESTATUS", precision = 1, scale = 0)
	public Integer getEstatus() {
		return estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", length = 30)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoConsulta")
	public Set<AdmAgendaDetalle> getAdmAgendaDetalles() {
		return this.admAgendaDetalles;
	}

	public void setAdmAgendaDetalles(Set<AdmAgendaDetalle> admAgendaDetalles) {
		this.admAgendaDetalles = admAgendaDetalles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoConsulta")
	public  Set<InstruccionVisita> getInstruccionVisita() {
		return instruccionVisita;
	}

	public  void setInstruccionVisita(Set<InstruccionVisita> instruccionVisita) {
		this.instruccionVisita = instruccionVisita;
	}

	@ManyToOne
	@JoinColumn(name = "HOSPITAL_ID", insertable = false, updatable = false)
	public AdmHospital getAdmHospital() {
		return admHospital;
	}

	public void setAdmHospital(AdmHospital admHospital) {
		this.admHospital = admHospital;
	}

	@Column(name = "HOSPITAL_ID", nullable = false)
	public Integer getHospitalId() {
		return hospitalId;
	}

	public void setHospitalId(Integer hospitalId) {
		this.hospitalId = hospitalId;
	}

	@ManyToOne
	@JoinColumn(name = "TIPO_VISITA_ID", insertable = false, updatable = false)
	public CatTipoVisita getCatTipoVisita() {
		return catTipoVisita;
	}

	public void setCatTipoVisita(CatTipoVisita catTipoVisita) {
		this.catTipoVisita = catTipoVisita;
	}

	@Column(name = "TIPO_VISITA_ID", nullable = false)
	public Integer getTipoVisitaId() {
		return tipoVisitaId;
	}

	public void setTipoVisitaId(Integer tipoVisitaId) {
		this.tipoVisitaId = tipoVisitaId;
	}
}
