package hts.backend.entity;
// Generated 27/03/2017 10:38:40 AM by Hibernate Tools 5.2.0.CR1

import hts.backend.entity.FacValidacionEvento;
import hts.backend.entity.FacturacionEvento;
import hts.backend.entity.PacAseguradora;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

//import java.util.HashSet;
//import java.util.Set;
//import javax.persistence.OneToMany;

/**
 * AdmCatAseguradora generated by hbm2java
 */
@Entity
@Table(name = "adm_cat_diagnostico_visita")
public class AdmCatDiagnosticoVisita implements java.io.Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private int diagnosticoVisitaId;
	private int cve;
	private String nombre;
	private String descripcion;
	private int estatus;


	@Id
	@Column(name = "DIAGNOSTICO_VISITA_ID", nullable = false, precision = 0)
	public int getDiagnosticoVisitaId() {
		return diagnosticoVisitaId;
	}

	public void setDiagnosticoVisitaId(int diagnosticoVisitaId) {
		this.diagnosticoVisitaId = diagnosticoVisitaId;
	}


	@Basic @Column(name = "CVE", nullable = false, precision = 0)
	public int getCve() {
		return cve;
	}

	public void setCve(int cve) {
		this.cve = cve;
	}
	@Basic @Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	@Basic @Column(name = "DESCRIPCION", nullable = false, length = 50)
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	@Basic @Column(name = "ESTATUS", nullable = false, precision = 0)
	public int getEstatus() {
		return estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}
}
