package hts.backend.entity;
// Generated 15/03/2017 10:07:24 AM by Hibernate Tools 5.2.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * NomCatTipoPrestacion3 generated by hbm2java
 */
@Entity
@Table(name = "adm_cat_tipo_prestacion3")
public class AdmCatTipoPrestacion3 implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private int tipoPrestacion3Id;
	private String cve;
	private String nombre;
	private String descripcion;
	private int valorDefault;
	private int estatus;
	private Date fechaRegistro;
	private String usuarioRegistra;
	private AdmHospital admHospital;
	private Integer hospitalId;
	private Set<NomCatTipoPrestacion2> nomCatTipoPrestacion2s = new HashSet<NomCatTipoPrestacion2>(0);

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "TIPO_PRESTACION3_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getTipoPrestacion3Id() {
		return this.tipoPrestacion3Id;
	}

	public void setTipoPrestacion3Id(int tipoPrestacion3Id) {
		this.tipoPrestacion3Id = tipoPrestacion3Id;
	}

	@Column(name = "CVE", nullable = false, length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, precision = 22, scale = 0)
	public int getValorDefault() {
		return this.valorDefault;
	}

	public void setValorDefault(int valorDefault) {
		this.valorDefault = valorDefault;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nomCatTipoPrestacion3")
	public Set<NomCatTipoPrestacion2> getNomCatTipoPrestacion2s() {
		return this.nomCatTipoPrestacion2s;
	}

	public void setNomCatTipoPrestacion2s(Set<NomCatTipoPrestacion2> nomCatTipoPrestacion2s) {
		this.nomCatTipoPrestacion2s = nomCatTipoPrestacion2s;
	}

	@ManyToOne @JoinColumn(name = "HOSPITAL_ID", insertable = false, updatable = false)
	public AdmHospital getAdmHospital() {
		return admHospital;
	}

	public void setAdmHospital(AdmHospital admHospital) {
		this.admHospital = admHospital;
	}
	@Column(name = "HOSPITAL_ID", nullable = false)
	public Integer getHospitalId() {
		return hospitalId;
	}

	public void setHospitalId(Integer hospitalId) {
		this.hospitalId = hospitalId;
	}
}
