package hts.backend.entity;
// Generated 27-feb-2017 9:57:50 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

/**
 * AdmEquipoSerEspecialidad generated by hbm2java
 */
@Entity
@Table(name = "adm_equipo_ser_especialidad")
public class AdmEquipoSerEspecialidad implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer equipoSerEspeId;
	private CatServEspecialidad catServEspecialidad;
	private AdmEquipo admEquipo;
	private Date fechaRegistro;
	private String noUsuario;
	private Date fechaAnulacion;
	private String usuarioAnulacion;


	public AdmEquipoSerEspecialidad() {
	}

	public AdmEquipoSerEspecialidad(Integer equipoSerEspeId) {
		this.equipoSerEspeId = equipoSerEspeId;
	}

	public AdmEquipoSerEspecialidad(Integer equipoSerEspeId, CatServEspecialidad catServEspecialidad,
			AdmEquipo admEquipo, Date fechaRegistro, String noUsuario) {
		this.equipoSerEspeId = equipoSerEspeId;
		this.catServEspecialidad = catServEspecialidad;
		this.admEquipo = admEquipo;
		this.fechaRegistro = fechaRegistro;
		this.noUsuario = noUsuario;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "EQUIPO_SER_ESPE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getEquipoSerEspeId() {
		return this.equipoSerEspeId;
	}

	public void setEquipoSerEspeId(Integer equipoSerEspeId) {
		this.equipoSerEspeId = equipoSerEspeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_ESPECIALIDAD_ID")
	public CatServEspecialidad getCatServEspecialidad() {
		return this.catServEspecialidad;
	}

	public void setCatServEspecialidad(CatServEspecialidad catServEspecialidad) {
		this.catServEspecialidad = catServEspecialidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EQUIPO_ID")
	public AdmEquipo getAdmEquipo() {
		return this.admEquipo;
	}

	public void setAdmEquipo(AdmEquipo admEquipo) {
		this.admEquipo = admEquipo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "NO_USUARIO", length = 20)
	public String getNoUsuario() {
		return this.noUsuario;
	}

	public void setNoUsuario(String noUsuario) {
		this.noUsuario = noUsuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_ANULACION", length = 7)
	public Date getFechaAnulacion() { return this.fechaAnulacion; }

	public void setFechaAnulacion(Date fechaAnulacion) { this.fechaAnulacion = fechaAnulacion; }

	@Column(name = "USUARIO_ANULACION", length = 20)
	public String getUsuarioAnulacion() { return this.usuarioAnulacion; }

	public void setUsuarioAnulacion(String usuarioAnulacion) { this.usuarioAnulacion = usuarioAnulacion; }

}
