package hts.backend.entity;
// Generated 09-feb-2017 11:07:58 by Hibernate Tools 5.2.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import hts.backend.entity.CatRol;

/**
 * AdmFuncion generated by hbm2java
 */
@Deprecated
@Entity
@Table(name = "adm_funcion")
public class AdmFuncion implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	private Integer funcionId;
//	private Integer accionId;
	AdmAccion admAccion;
	private String nombre;
	private String descripcion;
	private Integer estatus;
	private Date fecha;
	private String usuario;
	private Set<CatRol> catRols = new HashSet<CatRol>(0);

	public AdmFuncion() {
	}

	public AdmFuncion(Integer funcionId, AdmAccion admAccion, String nombre, String descripcion, Integer estatus,
			Date fecha, String usuario) {
		this.funcionId = funcionId;
		this.admAccion = admAccion;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.fecha = fecha;
		this.usuario = usuario;
	}

	public AdmFuncion(AdmAccion admAccion, String nombre, String descripcion, Integer estatus,
			Date fecha, String usuario) {
		this.admAccion = admAccion;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.fecha = fecha;
		this.usuario = usuario;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "FUNCION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getFuncionId() {
		return this.funcionId;
	}

	public void setFuncionId(Integer funcionId) {
		this.funcionId = funcionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCION_ID", nullable = false)
	public AdmAccion getAdmAccion() {
		return this.admAccion;
	}

	public void setAdmAccion(AdmAccion admAccion) {
		this.admAccion = admAccion;
	}


	@Column(name = "NOMBRE", nullable = false, length = 70)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", nullable = false, length = 7)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "USUARIO", nullable = false, length = 20)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ADM_ROL_FUNCION", joinColumns = {
			@JoinColumn(name = "FUNCION_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ROL_ID", nullable = false, updatable = false) })
	public Set<CatRol> getCatRols() {
		return this.catRols;
	}

	public void setCatRols(Set<CatRol> catRols) {
		this.catRols = catRols;
	}

}
