package hts.backend.entity;
// Generated 24-ene-2017 15:08:05 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * AdmHabitacion generated by hbm2java
 */
@Entity
@Table(name = "adm_habitacion")
public class AdmHabitacion implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer habitacionId;
	private CatTipoHabitacion catTipoHabitacion;
	private AdmCentroCosto catCentroCosto;
	private AdmUnidadEnfermeria admUnidadEnfermeria;
	private String numero;
	private String nombre;
	private Integer status;
	private Date fechaRegistro;
	private String usuarioCve;
	private Set<AdmCama> admCamas = new HashSet<AdmCama>(0);

	public AdmHabitacion() {
	}

	public AdmHabitacion(Integer habitacionId) {
		this.habitacionId = habitacionId;
	}

	public AdmHabitacion(Integer habitacionId, CatTipoHabitacion catTipoHabitacion, AdmCentroCosto catCentroCosto,
			AdmUnidadEnfermeria admUnidadEnfermeria, String numero, String nombre, Integer status,
			Date fechaRegistro, String usuarioCve, Set<AdmCama> admCamas) {
		this.habitacionId = habitacionId;
		this.catTipoHabitacion = catTipoHabitacion;
		this.catCentroCosto = catCentroCosto;
		this.admUnidadEnfermeria = admUnidadEnfermeria;
		this.numero = numero;
		this.nombre = nombre;
		this.status = status;
		this.fechaRegistro = fechaRegistro;
		this.usuarioCve = usuarioCve;
		this.admCamas = admCamas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "HABITACION_ID", unique = true, nullable = false)
	public Integer getHabitacionId() {
		return this.habitacionId;
	}

	public void setHabitacionId(Integer habitacionId) {
		this.habitacionId = habitacionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_HABITACION_ID")
	public CatTipoHabitacion getCatTipoHabitacion() {
		return this.catTipoHabitacion;
	}

	public void setCatTipoHabitacion(CatTipoHabitacion catTipoHabitacion) {
		this.catTipoHabitacion = catTipoHabitacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CENTRO_COSTO_ID")
	public AdmCentroCosto getCatCentroCosto() {
		return this.catCentroCosto;
	}

	public void setCatCentroCosto(AdmCentroCosto catCentroCosto) {
		this.catCentroCosto = catCentroCosto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNIDAD_ENFERMERIA_ID")
	public AdmUnidadEnfermeria getAdmUnidadEnfermeria() {
		return this.admUnidadEnfermeria;
	}

	public void setAdmUnidadEnfermeria(AdmUnidadEnfermeria admUnidadEnfermeria) {
		this.admUnidadEnfermeria = admUnidadEnfermeria;
	}

	@Column(name = "NUMERO", length = 50)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "NOMBRE", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ESTATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", length = 20)
	public String getUsuarioCve() {
		return this.usuarioCve;
	}

	public void setUsuarioCve(String usuarioCve) {
		this.usuarioCve = usuarioCve;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admHabitacion")
	public Set<AdmCama> getAdmCamas() {
		return this.admCamas;
	}

	public void setAdmCamas(Set<AdmCama> admCamas) {
		this.admCamas = admCamas;
	}

}
