package hts.backend.entity;
// Generated 03-feb-2017 12:09:42 by Hibernate Tools 5.2.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;


/**
 * AdmPortal generated by hbm2java
 */
@Entity
@Table(name = "adm_portal")
public class AdmPortal implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	private Integer portalId;
	private Integer hospitalId;
	private String nombre;
	private String descripcion;
	private Integer estatus;
	private Date fecha;
	private String usuario;
	private String icono;
	private Set<AdmModulo> admModulos = new HashSet<AdmModulo>(0);
//	private AdmHospital admHospital;



	public AdmPortal() {
	}

	public AdmPortal(Integer portalId) {
		this.portalId = portalId;
	}

	public AdmPortal(Integer portalId, Integer hospitalId, String nombre, String descripcion, Integer estatus,
			Date fecha, String usuario, String icono) {
		this.portalId = portalId;
		this.hospitalId = hospitalId;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.fecha = fecha;
		this.usuario = usuario;
		this.icono = icono;
	}
	public AdmPortal(Integer hospitalId, String nombre, String descripcion, Integer estatus,
			Date fecha, String usuario) {

		this.hospitalId = hospitalId;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.fecha = fecha;
		this.usuario = usuario;


	}
	public AdmPortal(Integer portalId, Integer hospitalId, String nombre, String descripcion, Integer estatus,
			Date fecha, String usuario, /*AdmHospital admHospital ,*/ Set<AdmModulo> admModulos) {
		this.portalId = portalId;
		this.hospitalId = hospitalId;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.fecha = fecha;
		this.usuario = usuario;
//		this.admHospital= admHospital;
		this.admModulos = admModulos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "PORTAL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getPortalId() {
		return this.portalId;
	}

	public void setPortalId(Integer portalId) {
		this.portalId = portalId;
	}

	@Column(name = "HOSPITAL_ID", nullable = false, precision = 22, scale = 0)
	public Integer getHospitalId() {
		return this.hospitalId;
	}

	public void setHospitalId(Integer hospitalId) {
		this.hospitalId = hospitalId;
	}

	@Column(name = "NOMBRE", nullable = false, length = 70)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", nullable = false, length = 7)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "USUARIO", nullable = false, length = 20)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admPortal")
	public Set<AdmModulo> getAdmModulos() {
		return this.admModulos;
	}

	public void setAdmModulos(Set<AdmModulo> admModulos) {
		this.admModulos = admModulos;
	}


	@Column(name = "ICONO", length = 30)
	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "HOSPITAL_ID", nullable = false)
//	public AdmHospital getAdmHospital() {
//		return this.admHospital;
//	}
//
//	public void setAdmHospital(AdmHospital admHospital) {
//		this.admHospital = admHospital;
//	}

}
