package hts.backend.entity;


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdmPiso generated by hbm2java
 */
@Entity
@Table(name = "adm_piso")
public class AdmPiso implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private Integer pisoId;
    private AdmEdificio admEdificio;
    private String nombre;
    private Integer status;
    private Date fechaRegistro;
    private String usuarioCve;
    private Set<AdmUnidadServicio> admUnidadServicios = new HashSet<AdmUnidadServicio>(0);

    public AdmPiso() {
    }

    public AdmPiso(Integer pisoId, AdmEdificio admEdificio) {
        this.pisoId = pisoId;
        this.admEdificio = admEdificio;
    }

    public AdmPiso(Integer pisoId, AdmEdificio admEdificio, String nombre, Integer status, Date fechaRegistro,
                   String usuarioCve, Set<AdmUnidadServicio> admUnidadServicios) {
        this.pisoId = pisoId;
        this.admEdificio = admEdificio;
        this.nombre = nombre;
        this.status = status;
        this.fechaRegistro = fechaRegistro;
        this.usuarioCve = usuarioCve;
        this.admUnidadServicios = admUnidadServicios;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "PISO_ID", unique = true, nullable = false)
    public Integer getPisoId() {
        return this.pisoId;
    }

    public void setPisoId(Integer pisoId) {
        this.pisoId = pisoId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EDIFICIO_ID", nullable = false)
    public AdmEdificio getAdmEdificio() {
        return this.admEdificio;
    }

    public void setAdmEdificio(AdmEdificio admEdificio) {
        this.admEdificio = admEdificio;
    }

    @Column(name = "NOMBRE", length = 50)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "ESTATUS")
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_REGISTRO", length = 7)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Column(name = "USUARIO_REGISTRO", length = 20)
    public String getUsuarioCve() {
        return this.usuarioCve;
    }

    public void setUsuarioCve(String usuarioCve) {
        this.usuarioCve = usuarioCve;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "admPiso")
    public Set<AdmUnidadServicio> getAdmUnidadServicios() {
        return this.admUnidadServicios;
    }

    public void setAdmUnidadServicios(Set<AdmUnidadServicio> admUnidadServicios) {
        this.admUnidadServicios = admUnidadServicios;
    }

}
