package hts.backend.entity;
// Generated 4/04/2017 12:02:20 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import hts.backend.entity.CatRol;

/**
 * AdmRolAccion generated by hbm2java
 */
@Entity
@Table(name = "adm_rol_accion")
public class AdmRolAccion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private AdmRolAccionId id;
	private CatRol catRol;

	public AdmRolAccion() {
	}

	public AdmRolAccion(AdmRolAccionId id, CatRol catRol) {
		this.id = id;
		this.catRol = catRol;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "rolId", column = @Column(name = "ROL_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "portalId", column = @Column(name = "PORTAL_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "moduloId", column = @Column(name = "MODULO_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "accionId", column = @Column(name = "ACCION_ID", nullable = false, precision = 22, scale = 0)) })
	public AdmRolAccionId getId() {
		return this.id;
	}

	public void setId(AdmRolAccionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROL_ID", nullable = false, insertable = false, updatable = false)
	public CatRol getCatRol() {
		return this.catRol;
	}

	public void setCatRol(CatRol catRol) {
		this.catRol = catRol;
	}

}
