package hts.backend.entity;
// Generated 4/04/2017 12:02:20 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdmRolAccionId generated by hbm2java
 */
@Embeddable
public class AdmRolAccionId implements java.io.Serializable {

	private int rolId;
	private int portalId;
	private int moduloId;
	private int accionId;

	public AdmRolAccionId() {
	}

	public AdmRolAccionId(int rolId, int portalId, int moduloId, int accionId) {
		this.rolId = rolId;
		this.portalId = portalId;
		this.moduloId = moduloId;
		this.accionId = accionId;
	}

	@Column(name = "ROL_ID", nullable = false, precision = 22, scale = 0)
	public int getRolId() {
		return this.rolId;
	}

	public void setRolId(int rolId) {
		this.rolId = rolId;
	}

	@Column(name = "PORTAL_ID", nullable = false, precision = 22, scale = 0)
	public int getPortalId() {
		return this.portalId;
	}

	public void setPortalId(int portalId) {
		this.portalId = portalId;
	}

	@Column(name = "MODULO_ID", nullable = false, precision = 22, scale = 0)
	public int getModuloId() {
		return this.moduloId;
	}

	public void setModuloId(int moduloId) {
		this.moduloId = moduloId;
	}

	@Column(name = "ACCION_ID", nullable = false, precision = 22, scale = 0)
	public int getAccionId() {
		return this.accionId;
	}

	public void setAccionId(int accionId) {
		this.accionId = accionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdmRolAccionId))
			return false;
		AdmRolAccionId castOther = (AdmRolAccionId) other;

		return (this.getRolId() == castOther.getRolId())
				&& (this.getPortalId() == castOther.getPortalId())
				&& (this.getModuloId() == castOther.getModuloId())
				&& (this.getAccionId() == castOther.getAccionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRolId();
		result = 37 * result + this.getPortalId();
		result = 37 * result + this.getModuloId();
		result = 37 * result + this.getAccionId();
		return result;
	}

}
