package hts.backend.entity;
// Generated 21/02/2017 12:43:05 PM by Hibernate Tools 5.2.0.Beta1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import hts.backend.entity.AdmConsultorio;

/**
 * AdmSala generated by hbm2java
 */
@Entity
@Table(name = "adm_sala")
public class AdmSala implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer salaId;
	private AdmCentroCosto catCentroCosto;
	private AdmUnidadTratamiento admUnidadTratamiento;
	private String cve;
	private String nombre;
	private String descripcion;
	private Integer status;
	private Date fechaRegistro;
	private String usuarioCve;
	private Set <AdmConsultorio>admConsultorios = new HashSet<AdmConsultorio>(0);
	private Integer exclusivoTriage;

	public AdmSala() {
	}

	public AdmSala(Integer salaId) {
		this.salaId = salaId;
	}

	public AdmSala(Integer salaId, AdmUnidadTratamiento admUnidadTratamiento, String cve, String nombre,
			String descripcion, Integer status, Date fechaRegistro, String usuarioCve, Set <AdmConsultorio>admConsultorios) {
		this.salaId = salaId;
		this.admUnidadTratamiento = admUnidadTratamiento;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.status = status;
		this.fechaRegistro = fechaRegistro;
		this.usuarioCve = usuarioCve;
		this.admConsultorios = admConsultorios;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "SALA_ID", unique = true, nullable = false)

	public Integer getSalaId() {
		return this.salaId;
	}

	public void setSalaId(Integer salaId) {
		this.salaId = salaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNIDAD_TRATAMIENTO_ID")
	public AdmUnidadTratamiento getAdmUnidadTratamiento() {
		return this.admUnidadTratamiento;
	}

	public void setAdmUnidadTratamiento(AdmUnidadTratamiento admUnidadTratamiento) {
		this.admUnidadTratamiento = admUnidadTratamiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CENTRO_COSTO_ID")
	public AdmCentroCosto getCatCentroCosto() {
		return this.catCentroCosto;
	}

	public void setCatCentroCosto(AdmCentroCosto catCentroCosto) {
		this.catCentroCosto = catCentroCosto;
	}

	@Column(name = "CVE", length = 50)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTATUS", precision = 22, scale = 0)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", length = 20)
	public String getUsuarioCve() {
		return this.usuarioCve;
	}

	public void setUsuarioCve(String usuarioCve) {
		this.usuarioCve = usuarioCve;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admSala")
	public Set<AdmConsultorio> getAdmConsultorios() {
		return this.admConsultorios;
	}

	public void setAdmConsultorios(Set <AdmConsultorio>admConsultorios) {
		this.admConsultorios = admConsultorios;
	}

	@Column(name = "EXCLUSIVO_TRIAGE", length = 50)
	public Integer getExclusivoTriage() {
		return exclusivoTriage;
	}

	public void setExclusivoTriage(Integer exclusivoTriage) {
		this.exclusivoTriage = exclusivoTriage;
	}
}
