package hts.backend.entity;
// Generated 23-feb-2017 12:51:24 by Hibernate Tools 4.3.1.Final


import java.util.Date;
import javax.persistence.*;


/**
 * AdmUsuario generated by hbm2java
 */
@Entity
@Table(name = "adm_usuario")
public class AdmUsuario implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer userId;
	private String username;
	private String password;
	private String identificador;
	private String nombre;
	private String APaterno;
	private String AMaterno;
	private Date fechaRegistro;
	private Date fechaModificacion;
	private Integer usuarioNuevo;
	private Integer estatus;

	public AdmUsuario() {
	}

	public AdmUsuario(Integer userId) {
		this.userId = userId;
	}

	public AdmUsuario(Integer userId, String username, String password, String identificador, AdmPersonal profecionalId,
			String nombre, String APaterno, String AMaterno, Date fechaRegistro, Date fechaModificacion,
			Integer usuarioNuevo, Integer estatus ) {
		this.userId = userId;
		this.username = username;
		this.password = password;
		this.identificador = identificador;
		this.nombre = nombre;
		this.APaterno = APaterno;
		this.AMaterno = AMaterno;
		this.fechaRegistro = fechaRegistro;
		this.fechaModificacion = fechaModificacion;
		this.usuarioNuevo = usuarioNuevo;
		this.estatus = estatus;

	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "USER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "USERNAME")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "IDENTIFICADOR", length = 20)
	public String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(String identificador) {
		this.identificador = identificador;
	}



	@Column(name = "NOMBRE")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "A_PATERNO")
	public String getAPaterno() {
		return this.APaterno;
	}

	public void setAPaterno(String APaterno) {
		this.APaterno = APaterno;
	}

	@Column(name = "A_MATERNO")
	public String getAMaterno() {
		return this.AMaterno;
	}

	public void setAMaterno(String AMaterno) {
		this.AMaterno = AMaterno;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_MODIFICACION", length = 7)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "USUARIO_NUEVO", precision = 22, scale = 0)
	public Integer getUsuarioNuevo() {
		return this.usuarioNuevo;
	}

	public void setUsuarioNuevo(Integer usuarioNuevo) {
		this.usuarioNuevo = usuarioNuevo;
	}

	@Column(name = "ESTATUS", precision = 22, scale = 0)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}


}