package hts.backend.entity;



import hts.backend.entity.GusModulos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * AdmUnidadMedica generated by hbm2java
 */
@Entity
@Table(name = "adm_unidad_medica")
public class AdmUnidadMedica implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private Integer unidadMedicaId;
    private AdmUnidadServicio admUnidadServicio;
    private String nombre;
    private String descripcion;
    private String cve;
    private Integer status;
    private Date fechaRegistro;
    private String usuarioCve;
    private Set<AdmUnidadEnfermeria> admUnidadEnfermerias = new HashSet<AdmUnidadEnfermeria>(0);
    private Set<AdmUnidadTratamiento> admUnidadTratamientos = new HashSet<AdmUnidadTratamiento>(0);
    private GusModulos gusModulos;

    public AdmUnidadMedica() {
    }

    public AdmUnidadMedica(Integer unidadMedicaId) {
        this.unidadMedicaId = unidadMedicaId;
    }
    public AdmUnidadMedica(Integer unidadMedicaId, AdmUnidadServicio admUnidadServicio) {
        this.unidadMedicaId = unidadMedicaId;
        this.admUnidadServicio = admUnidadServicio;
    }

    public AdmUnidadMedica(Integer unidadMedicaId, AdmUnidadServicio admUnidadServicio, String nombre,
                           String descripcion, String cve, Integer status, Date fechaRegistro, String usuarioCve,
                           Set<AdmUnidadEnfermeria> admUnidadEnfermerias, Set<AdmUnidadTratamiento> admUnidadTratamientos) {
        this.unidadMedicaId = unidadMedicaId;
        this.admUnidadServicio = admUnidadServicio;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.cve = cve;
        this.status = status;
        this.fechaRegistro = fechaRegistro;
        this.usuarioCve = usuarioCve;
        this.admUnidadEnfermerias = admUnidadEnfermerias;
        this.admUnidadTratamientos = admUnidadTratamientos;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "UNIDAD_MEDICA_ID", unique = true, nullable = false)
    public Integer getUnidadMedicaId() {
        return this.unidadMedicaId;
    }

    public void setUnidadMedicaId(Integer unidadMedicaId) {
        this.unidadMedicaId = unidadMedicaId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UNIDAD_SERVICIO_ID", nullable = false)
    public AdmUnidadServicio getAdmUnidadServicio() {
        return this.admUnidadServicio;
    }

    public void setAdmUnidadServicio(AdmUnidadServicio admUnidadServicio) {
        this.admUnidadServicio = admUnidadServicio;
    }

    @Column(name = "NOMBRE", length = 100)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "DESCRIPCION", length = 100)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "CVE", length = 50)
    public String getCve() {
        return this.cve;
    }

    public void setCve(String cve) {
        this.cve = cve;
    }

    @Column(name = "ESTATUS")
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_REGISTRO", length = 7)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Column(name = "USUARIO_REGISTRO", length = 20)
    public String getUsuarioCve() {
        return this.usuarioCve;
    }

    public void setUsuarioCve(String usuarioCve) {
        this.usuarioCve = usuarioCve;
    }
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "admUnidadMedica")
    public Set<AdmUnidadEnfermeria> getAdmUnidadEnfermerias() {
        return this.admUnidadEnfermerias;
    }

    public void setAdmUnidadEnfermerias(Set<AdmUnidadEnfermeria> admUnidadEnfermerias) {
        this.admUnidadEnfermerias = admUnidadEnfermerias;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "admUnidadMedica")
    public Set<AdmUnidadTratamiento> getAdmUnidadTratamientos() {
        return this.admUnidadTratamientos;
    }

    public void setAdmUnidadTratamientos(Set<AdmUnidadTratamiento> admUnidadTratamientos) {
        this.admUnidadTratamientos = admUnidadTratamientos;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GUS_MODULO_ID")
    public GusModulos getGusModulos() {
        return gusModulos;
    }

    public void setGusModulos(GusModulos gusModulos) {
        this.gusModulos = gusModulos;
    }
}
