package hts.backend.entity;
// Generated 24-ene-2017 15:08:05 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * AdmUnidadEnfermeria generated by hbm2java
 */
@Entity
@Table(name = "adm_unidad_enfermeria")
public class AdmUnidadEnfermeria implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer unidadEnfermeriaId;
	private AdmCentroCosto catCentroCosto;
	private AdmUnidadMedica admUnidadMedica;
	private String nombre;
	private String descripcion;
	private String cve;
	private Integer status;
	private Date fechaRegistro;
	private String usuarioCve;
	private Set<AdmHabitacion> admHabitacions = new HashSet<AdmHabitacion>(0);

	public AdmUnidadEnfermeria() {
	}
	public AdmUnidadEnfermeria(Integer unidadEnfermeriaId) {
		this.unidadEnfermeriaId = unidadEnfermeriaId;
	}

	public AdmUnidadEnfermeria(Integer unidadEnfermeriaId, AdmUnidadMedica admUnidadMedica) {
		this.unidadEnfermeriaId = unidadEnfermeriaId;
		this.admUnidadMedica = admUnidadMedica;
	}

	public AdmUnidadEnfermeria(Integer unidadEnfermeriaId, AdmCentroCosto catCentroCosto,
			AdmUnidadMedica admUnidadMedica, String nombre, String descripcion, String cve, Integer status,
			Date fechaRegistro, String usuarioCve, Set<AdmHabitacion> admHabitacions) {

		this.unidadEnfermeriaId = unidadEnfermeriaId;
		this.catCentroCosto = catCentroCosto;
		this.admUnidadMedica = admUnidadMedica;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.cve = cve;
		this.status = status;
		this.fechaRegistro = fechaRegistro;
		this.usuarioCve = usuarioCve;
		this.admHabitacions = admHabitacions;
	}

	public AdmUnidadEnfermeria( AdmUnidadMedica admUnidadMedica, AdmCentroCosto catCentroCosto, String nombre,
			String descripcion, String cve, Integer status,
			Date fechaRegistro, String usuarioCve) {

		this.admUnidadMedica = admUnidadMedica;
		this.catCentroCosto = catCentroCosto;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.cve = cve;
		this.status = status;
		this.fechaRegistro = fechaRegistro;
		this.usuarioCve = usuarioCve;

	}

	public AdmUnidadEnfermeria( AdmUnidadMedica admUnidadMedica, String nombre,
			String descripcion, String cve, Integer status,
			Date fechaRegistro, String usuarioCve) {

		this.admUnidadMedica = admUnidadMedica;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.cve = cve;
		this.status = status;
		this.fechaRegistro = fechaRegistro;
		this.usuarioCve = usuarioCve;

	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "UNIDAD_ENFERMERIA_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getUnidadEnfermeriaId() {
		return this.unidadEnfermeriaId;
	}

	public void setUnidadEnfermeriaId(Integer unidadEnfermeriaId) {
		this.unidadEnfermeriaId = unidadEnfermeriaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CENTRO_COSTO_ID")
	public AdmCentroCosto getCatCentroCosto() {
		return this.catCentroCosto;
	}

	public void setCatCentroCosto(AdmCentroCosto catCentroCosto) {
		this.catCentroCosto = catCentroCosto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNIDAD_MEDICA_ID", nullable = false)
	public AdmUnidadMedica getAdmUnidadMedica() {
		return this.admUnidadMedica;
	}

	public void setAdmUnidadMedica(AdmUnidadMedica admUnidadMedica) {
		this.admUnidadMedica = admUnidadMedica;
	}

	@Column(name = "NOMBRE", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "CVE", length = 50)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "ESTATUS", precision = 22, scale = 0)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", length = 20)
	public String getUsuarioCve() {
		return this.usuarioCve;
	}

	public void setUsuarioCve(String usuarioCve) {
		this.usuarioCve = usuarioCve;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admUnidadEnfermeria")
	public Set<AdmHabitacion> getAdmHabitacions() {
		return this.admHabitacions;
	}

	public void setAdmHabitacions(Set<AdmHabitacion> admHabitacions) {
		this.admHabitacions = admHabitacions;
	}

}
