package hts.backend.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * AdmUnidadServicio generated by hbm2java
 */
@Entity
@Table(name = "adm_unidad_servicio")
public class AdmUnidadServicio implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private Integer unidadServicioId;
    private AdmPiso admPiso;
    private String nombre;
    private String descripcion;
    private String cve;
    private Integer status;
    private Date fechaRegistro;
    private String usuarioCve;
    private Set<AdmUnidadMedica> admUnidadMedicas = new HashSet<AdmUnidadMedica>(0);

    public AdmUnidadServicio() {
    }

    public AdmUnidadServicio(Integer unidadServicioId) {
        this.unidadServicioId = unidadServicioId;
    }

    public AdmUnidadServicio(Integer unidadServicioId, AdmPiso admPiso, String nombre, String descripcion,
                             String cve, Integer status, Date fechaRegistro, String usuarioCve, Set<AdmUnidadMedica> admUnidadMedicas) {
        this.unidadServicioId = unidadServicioId;
        this.admPiso = admPiso;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.cve = cve;
        this.status = status;
        this.fechaRegistro = fechaRegistro;
        this.usuarioCve = usuarioCve;
        this.admUnidadMedicas = admUnidadMedicas;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "UNIDAD_SERVICIO_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public Integer getUnidadServicioId() {
        return this.unidadServicioId;
    }

    public void setUnidadServicioId(Integer unidadServicioId) {
        this.unidadServicioId = unidadServicioId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PISO_ID")
    public AdmPiso getAdmPiso() {
        return this.admPiso;
    }

    public void setAdmPiso(AdmPiso admPiso) {
        this.admPiso = admPiso;
    }

    @Column(name = "NOMBRE", length = 100)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "DESCRIPCION", length = 100)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "CVE", length = 50)
    public String getCve() {
        return this.cve;
    }

    public void setCve(String cve) {
        this.cve = cve;
    }

    @Column(name = "ESTATUS", precision = 22, scale = 0)
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_REGISTRO", length = 7)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Column(name = "USUARIO_REGISTRO", length = 20)
    public String getUsuarioCve() {
        return this.usuarioCve;
    }

    public void setUsuarioCve(String usuarioCve) {
        this.usuarioCve = usuarioCve;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "admUnidadServicio")
    public Set<AdmUnidadMedica> getAdmUnidadMedicas() {
        return this.admUnidadMedicas;
    }

    public void setAdmUnidadMedicas(Set<AdmUnidadMedica> admUnidadMedicas) {
        this.admUnidadMedicas = admUnidadMedicas;
    }

}
