package hts.backend.entity;

// Generated 24/03/2017 02:00:24 PM by Hibernate Tools 5.2.0.CR1


import org.springframework.security.core.context.SecurityContextHolder;

import java.util.Date;
import javax.persistence.*;

/**
 * AgenteDocumento generated by hbm2java
 */
@Entity
@Table(name = "agente_documento")
public class AgenteDocumento implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer agenteDocumentoId;
	private CatTipoAgente catTipoAgente;
	private Integer tipoAgenteId;
	private Documento documento;
	private Integer agenteId;
	private Integer status;
	private Date fechaRegistro;
	private String usuarioRegistro;
	private String cve;
	private String agenteCve;

	public AgenteDocumento() {
	}

	public static AgenteDocumento DocumentoPaciente(Documento documento, int idPaciente) {
		AgenteDocumento obj = new AgenteDocumento();

		obj.setTipoAgenteId(2);
		obj.setDocumento(documento);
		obj.setAgenteId(idPaciente);
		obj.setStatus(1);
		obj.setFechaRegistro(new Date());
		obj.setUsuarioRegistro(SecurityContextHolder.getContext().getAuthentication().getName());
		obj.setCve(null);
		obj.setAgenteCve(null);

		return obj;
	}

	public static AgenteDocumento DocumentoContactoPaciente(Documento documento, int idContacto) {
		AgenteDocumento obj = new AgenteDocumento();

		obj.setTipoAgenteId(5);
		obj.setDocumento(documento);
		obj.setAgenteId(idContacto);
		obj.setStatus(1);
		obj.setFechaRegistro(new Date());
		obj.setUsuarioRegistro(SecurityContextHolder.getContext().getAuthentication().getName());
		obj.setCve(null);
		obj.setAgenteCve(null);

		return obj;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "AGENTE_DOCUMENTO_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getAgenteDocumentoId() {
		return this.agenteDocumentoId;
	}

	public void setAgenteDocumentoId(Integer agenteDocumentoId) {
		this.agenteDocumentoId = agenteDocumentoId;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCUMENTO_ID")
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@Column(name = "AGENTE_ID", nullable = false, precision = 22, scale = 0)
	public Integer getAgenteId() {
		return this.agenteId;
	}

	public void setAgenteId(Integer agenteId) {
		this.agenteId = agenteId;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@Column(name = "CVE", length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "AGENTE_CVE", length = 20)
	public String getAgenteCve() {
		return this.agenteCve;
	}

	public void setAgenteCve(String agenteCve) {
		this.agenteCve = agenteCve;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_AGENTE_ID", insertable = false, updatable = false)
	public CatTipoAgente getCatTipoAgente() {
		return this.catTipoAgente;
	}

	public void setCatTipoAgente(CatTipoAgente catTipoAgente) {
		this.catTipoAgente = catTipoAgente;
	}


	@Column(name = "TIPO_AGENTE_ID", nullable = false)
	public Integer getTipoAgenteId() {
		return tipoAgenteId;
	}

	public void setTipoAgenteId(Integer tipoAgenteId) {
		this.tipoAgenteId = tipoAgenteId;
	}
}
