package hts.backend.entity;
// Generated 17/03/2017 11:00:42 AM by Hibernate Tools 5.2.0.CR1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CatClasificacionFiscal generated by hbm2java
 */
@Entity
@Table(name = "cat_clasificacion_fiscal")
public class CatClasificacionFiscal implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int clasificacionFiscalId;
	private String cve;
	private String nombre;
	private String descripcion;
	private int valorDefault;
	private int estatus;
	private Date fechaRegistro;
	private String usuarioRegistra;
	private Set<NomPrductoPrestacion> nomPrductoPrestacions = new HashSet<NomPrductoPrestacion>(0);
	private Set<AdmCatAseguradora> admCatAseguradoras2 = new HashSet<AdmCatAseguradora>(0);


	public CatClasificacionFiscal() {
	}

	public CatClasificacionFiscal(int clasificacionFiscalId, String cve, String nombre, String descripcion,
								  int valorDefault, int estatus) {
		this.clasificacionFiscalId = clasificacionFiscalId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
	}

	public CatClasificacionFiscal(int clasificacionFiscalId, String cve, String nombre, String descripcion,
								  int valorDefault, int estatus, Date fechaRegistro, String usuarioRegistra,
								  Set<NomPrductoPrestacion> nomPrductoPrestacions, Set<AdmCatAseguradora> admCatAseguradoras) {
		this.clasificacionFiscalId = clasificacionFiscalId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
		this.nomPrductoPrestacions = nomPrductoPrestacions;
		this.admCatAseguradoras2 = admCatAseguradoras;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CLASIFICACION_FISCAL_ID", unique = true, nullable = false, precision = 22)
	public int getClasificacionFiscalId() {
		return this.clasificacionFiscalId;
	}

	public void setClasificacionFiscalId(int clasificacionFiscalId) {
		this.clasificacionFiscalId = clasificacionFiscalId;
	}

	@Column(name = "CVE", nullable = false, length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, precision = 22)
	public int getValorDefault() {
		return this.valorDefault;
	}

	public void setValorDefault(int valorDefault) {
		this.valorDefault = valorDefault;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22)
	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catClasificacionFiscal")
	public Set<NomPrductoPrestacion> getNomPrductoPrestacions() {
		return this.nomPrductoPrestacions;
	}

	public void setNomPrductoPrestacions(Set<NomPrductoPrestacion> nomPrductoPrestacions) {
		this.nomPrductoPrestacions = nomPrductoPrestacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catClasificacionFiscal")
	public Set<AdmCatAseguradora> getAdmCatAseguradoras() {
		return this.admCatAseguradoras2;
	}

	public void setAdmCatAseguradoras(Set<AdmCatAseguradora> admCatAseguradoras) {
		this.admCatAseguradoras2 = admCatAseguradoras;
	}
}
