package hts.backend.entity;
// Generated 15/05/2017 04:17:33 PM by Hibernate Tools 5.2.1.Final

import hts.backend.entity.CatIdiomaApp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * CatImpedimento generated by hbm2java
 */
@Entity
@Table(name = "cat_impedimento")
public class CatImpedimento implements java.io.Serializable {

	private Integer impedimentoId;
	private CatIdiomaApp catIdiomaApp;
	private String cve;
	private String nombre;
	private String descripcion;
	private Integer valorDefualt;
	private Integer estatus;
	private Date fechaRegistro;
	private String usuarioRegistro;
	private Set<PacImpedimentoPaciente> pacImpedimentoPacientes = new HashSet<PacImpedimentoPaciente>(0);

	public CatImpedimento() {
	}


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "IMPEDIMENTO_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getImpedimentoId() {
		return this.impedimentoId;
	}

	public void setImpedimentoId(Integer impedimentoId) {
		this.impedimentoId = impedimentoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDIOMA_APP_ID", nullable = false)
	public CatIdiomaApp getCatIdiomaApp() {
		return this.catIdiomaApp;
	}

	public void setCatIdiomaApp(CatIdiomaApp catIdiomaApp) {
		this.catIdiomaApp = catIdiomaApp;
	}

	@Column(name = "CVE", nullable = false, length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, precision = 22, scale = 0)
	public Integer getValorDefualt() {
		return this.valorDefualt;
	}

	public void setValorDefualt(Integer valorDefualt) {
		this.valorDefualt = valorDefualt;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catImpedimento")
	public Set<PacImpedimentoPaciente> getPacImpedimentoPacientes() {
		return this.pacImpedimentoPacientes;
	}

	public void setPacImpedimentoPacientes(Set<PacImpedimentoPaciente> pacImpedimentoPacientes) {
		this.pacImpedimentoPacientes = pacImpedimentoPacientes;
	}

}
