package hts.backend.entity;

import javax.persistence.*;
import java.util.Date;

/**
 * CatIdiomaApp generated by hbm2java
 */
@Entity
@Table(name = "nom_cat_idioma_app")
public class CatIdiomaApp implements java.io.Serializable {


	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private int idiomaAppId;
	private String usuarioRegistra;
	private String descripcion;
	private String cve;
	private String nombre;
	private int valorDefault;
	private int estatus;
	private Date fechaRegistro;

	public CatIdiomaApp() {
	}

	public CatIdiomaApp(int idiomaAppId, String usuarioRegistra) {
		this.idiomaAppId = idiomaAppId;
		this.usuarioRegistra = usuarioRegistra;
	}

	public CatIdiomaApp(int idiomaAppId, String usuarioRegistra, String descripcion, String cve, String nombre,
						int valorDefault, int estatus, Date fechaRegistro) {
		this.idiomaAppId = idiomaAppId;
		this.usuarioRegistra = usuarioRegistra;
		this.descripcion = descripcion;
		this.cve = cve;
		this.nombre = nombre;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
	}

	@Id

	@Column(name = "IDIOMA_APP_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getIdiomaAppId() {
		return this.idiomaAppId;
	}

	public void setIdiomaAppId(int idiomaAppId) {
		this.idiomaAppId = idiomaAppId;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}

	@Column(name = "DESCRIPCION", length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "CVE", length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "VALOR_DEFAULT", precision = 22, scale = 0)
	public int getValorDefault() {
		return this.valorDefault;
	}

	public void setValorDefault(int valorDefault) {
		this.valorDefault = valorDefault;
	}

	@Column(name = "ESTATUS", precision = 22, scale = 0)
	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}
}

