package hts.backend.entity;

// Generated 5/04/2017 07:23:32 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CatMotivoAsignacion generated by hbm2java
 */
@Entity
@Table(name = "nom_cat_motivo_asignacion")
public class CatMotivoAsignacion implements java.io.Serializable {

	private Integer motivoAsignacionId;
	private String cve;
	private String nombre;
	private String descripcion;
	private Integer valorDefault;
	private Integer estatus;
	private Date fechaRegistro;
	private String usuarioRegistro;
	private Integer idiomaAppId;
	private Set<PacAseguradora> pacAseguradoras = new HashSet<PacAseguradora>(0);

	public CatMotivoAsignacion() {
	}
	public CatMotivoAsignacion(Integer motivoAsignacionId) {
		this.motivoAsignacionId = motivoAsignacionId;
	}
	public CatMotivoAsignacion(Integer motivoAsignacionId, String cve, String nombre, String descripcion,
			Integer valorDefault, Integer estatus, Date fechaRegistro, String usuarioRegistro) {
		this.motivoAsignacionId = motivoAsignacionId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
	}

	public CatMotivoAsignacion(Integer motivoAsignacionId, String cve, String nombre, String descripcion,
			Integer valorDefault, Integer estatus, Date fechaRegistro, String usuarioRegistro,
			Integer idiomaAppId, Set<PacAseguradora> pacAseguradoras) {
		this.motivoAsignacionId = motivoAsignacionId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
		this.idiomaAppId = idiomaAppId;
		this.pacAseguradoras = pacAseguradoras;
	}

	@Id

	@Column(name = "MOTIVO_ASIGNACION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getMotivoAsignacionId() {
		return this.motivoAsignacionId;
	}

	public void setMotivoAsignacionId(Integer motivoAsignacionId) {
		this.motivoAsignacionId = motivoAsignacionId;
	}

	@Column(name = "CVE", nullable = false, length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, precision = 22, scale = 0)
	public Integer getValorDefault() {
		return this.valorDefault;
	}

	public void setValorDefault(Integer valorDefault) {
		this.valorDefault = valorDefault;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@Column(name = "IDIOMA_APP_ID", precision = 22, scale = 0)
	public Integer getIdiomaAppId() {
		return this.idiomaAppId;
	}

	public void setIdiomaAppId(Integer idiomaAppId) {
		this.idiomaAppId = idiomaAppId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catMotivoAsignacion")
	public Set<PacAseguradora> getPacAseguradoras() {
		return this.pacAseguradoras;
	}

	public void setPacAseguradoras(Set<PacAseguradora> pacAseguradoras) {
		this.pacAseguradoras = pacAseguradoras;
	}

}
