package hts.backend.entity;

// Generated 24/02/2017 07:59:12 PM by Hibernate Tools 5.2.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;


/**
 * CatTipoAgente generated by hbm2java
 */
@Entity
@Table(name = "nom_cat_tipo_agente")
public class CatTipoAgente implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer tipoAgenteId;
	private String cve;
	private String nombre;
	private String descripcion;
	private Integer status;
	private Date fechaRegistro;
	private String usuarioRegistra;
	private Set<AgenteTelefono> agenteTelefonos = new HashSet<AgenteTelefono>(0);
	private Set<AgenteCorreo> agenteCorreos = new HashSet<AgenteCorreo>(0);
	private Set<AgenteDireccion> agenteDireccions = new HashSet<AgenteDireccion>(0);
	private Set<AgenteDocumento> agenteDocumentos = new HashSet<AgenteDocumento>(0);
	private Set<AgenteContacto> agenteContactos = new HashSet<AgenteContacto>(0);

	public CatTipoAgente(Integer tipoAgenteId) {
		this.tipoAgenteId = tipoAgenteId;
	}

	public CatTipoAgente() {

	}



	public CatTipoAgente(Integer tipoAgenteId, String cve, String nombre, String descripcion, Integer status,
			Date fechaRegistro, String usuarioRegistra) {
		this.tipoAgenteId = tipoAgenteId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.status = status;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
	}

	public CatTipoAgente(Integer tipoAgenteId, String cve, String nombre, String descripcion, Integer status,
			Date fechaRegistro, String usuarioRegistra, Set<AgenteTelefono> agenteTelefonos,
			Set<AgenteCorreo> agenteCorreos, Set<AgenteDireccion> agenteDireccions) {
		this.tipoAgenteId = tipoAgenteId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.status = status;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
		this.agenteTelefonos = agenteTelefonos;
		this.agenteCorreos = agenteCorreos;
		this.agenteDireccions = agenteDireccions;
	}

	public CatTipoAgente(Integer tipoAgenteId, String cve, String nombre, String descripcion, Integer status,
			Date fechaRegistro, String usuarioRegistra, Set<AgenteTelefono> agenteTelefonos,
			Set<AgenteCorreo> agenteCorreos, Set<AgenteDireccion> agenteDireccions, 
			Set<AgenteDocumento> agenteDocumentos) {
		this.tipoAgenteId = tipoAgenteId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.status = status;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
		this.agenteTelefonos = agenteTelefonos;
		this.agenteCorreos = agenteCorreos;
		this.agenteDireccions = agenteDireccions;
		this.agenteDocumentos = agenteDocumentos;
	}

	public CatTipoAgente(Integer tipoAgenteId, String cve, String nombre, String descripcion, Integer status,
			Date fechaRegistro, String usuarioRegistra, Set<AgenteTelefono> agenteTelefonos,
			Set<AgenteCorreo> agenteCorreos, Set<AgenteDireccion> agenteDireccions,
			Set<AgenteDocumento> agenteDocumentos, Set<AgenteContacto> agenteContactos) {
		this.tipoAgenteId = tipoAgenteId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.status = status;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
		this.agenteTelefonos = agenteTelefonos;
		this.agenteCorreos = agenteCorreos;
		this.agenteDireccions = agenteDireccions;
		this.agenteDocumentos = agenteDocumentos;
		this.agenteContactos = agenteContactos;
	}

	public CatTipoAgente(Integer tipoAgenteId, String cve, String nombre, String descripcion, Integer status,
						 Date fechaRegistro, String usuarioRegistra, Set<AgenteTelefono> agenteTelefonos) {
		this.tipoAgenteId = tipoAgenteId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.status = status;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
		this.agenteTelefonos = agenteTelefonos;
		this.agenteCorreos = agenteCorreos;
		this.agenteDireccions = agenteDireccions;
		this.agenteDocumentos = agenteDocumentos;
		this.agenteContactos = agenteContactos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "TIPO_AGENTE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getTipoAgenteId() {
		return this.tipoAgenteId;
	}

	public void setTipoAgenteId(Integer tipoAgenteId) {
		this.tipoAgenteId = tipoAgenteId;
	}

	@Column(name = "CVE", nullable = false, length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoAgente")
	public Set<AgenteTelefono> getAgenteTelefonos() {
		return this.agenteTelefonos;
	}

	public void setAgenteTelefonos(Set<AgenteTelefono> agenteTelefonos) {
		this.agenteTelefonos = agenteTelefonos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoAgente")
	public Set<AgenteCorreo> getAgenteCorreos() {
		return this.agenteCorreos;
	}

	public void setAgenteCorreos(Set<AgenteCorreo> agenteCorreos) {
		this.agenteCorreos = agenteCorreos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoAgente")
	public Set<AgenteDireccion> getAgenteDireccions() {
		return this.agenteDireccions;
	}

	public void setAgenteDireccions(Set<AgenteDireccion> agenteDireccions) {
		this.agenteDireccions = agenteDireccions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoAgente")
	public Set<AgenteDocumento> getAgenteDocumentos() {
		return this.agenteDocumentos;
	}

	public void setAgenteDocumentos(Set<AgenteDocumento> agenteDocumentos) {
		this.agenteDocumentos = agenteDocumentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoAgente")
	public Set<AgenteContacto> getAgenteContactos() {
		return this.agenteContactos;
	}

	public void setAgenteContactos(Set<AgenteContacto> agenteContactos) {
		this.agenteContactos = agenteContactos;
	}

}
