package hts.backend.entity;
// Generated 27/03/2017 10:38:40 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CatTipoAseguradora generated by hbm2java
 */
@Entity
@Table(name = "cat_tipo_aseguradora")
public class CatTipoAseguradora implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private int tipoAseguradoraId;
	private String cve;
	private String nombre;
	private String descripcion;
	private int valorDefault;
	private int estatus;
	private Date fechaRegistro;
	private String usuarioRegistra;
	private CatIdiomaApp catIdiomaApp;
	private Set<AdmCatAseguradora> admCatAseguradoras = new HashSet<AdmCatAseguradora>(0);

	public CatTipoAseguradora() {
	}

	public CatTipoAseguradora(int tipoAseguradoraId, String cve, String nombre, String descripcion,
							  int valorDefault, int estatus) {
		this.tipoAseguradoraId = tipoAseguradoraId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
	}

	public CatTipoAseguradora(int tipoAseguradoraId, String cve, String nombre, String descripcion,
							  int valorDefault, int estatus, Date fechaRegistro, String usuarioRegistra,
							  int idiomaAppId, CatIdiomaApp catIdiomaApp, Set<AdmCatAseguradora> admCatAseguradoras) {
		this.tipoAseguradoraId = tipoAseguradoraId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
		this.catIdiomaApp = catIdiomaApp;
		this.admCatAseguradoras = admCatAseguradoras;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "TIPO_ASEGURADORA_ID", unique = true, nullable = false, precision = 22)
	public int getTipoAseguradoraId() {
		return this.tipoAseguradoraId;
	}

	public void setTipoAseguradoraId(int tipoAseguradoraId) {
		this.tipoAseguradoraId = tipoAseguradoraId;
	}

	@Column(name = "CVE", nullable = false, length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, precision = 22)
	public int getValorDefault() {
		return this.valorDefault;
	}

	public void setValorDefault(int valorDefault) {
		this.valorDefault = valorDefault;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22)
	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDIOMA_APP_ID")
	public CatIdiomaApp getCatIdiomaApp() {
		return this.catIdiomaApp;
	}

	public void setCatIdiomaApp(CatIdiomaApp catIdiomaApp) {
		this.catIdiomaApp = catIdiomaApp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoAseguradora")
	public Set<AdmCatAseguradora> getAdmCatAseguradoras() {
		return this.admCatAseguradoras;
	}

	public void setAdmCatAseguradoras(Set<AdmCatAseguradora> admCatAseguradoras) {
		this.admCatAseguradoras = admCatAseguradoras;
	}
}
