package hts.backend.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * CatTipoEstablecimiento generated by hbm2java
 */
@Entity
@Table(name = "cat_tipo_establecimiento")
public class CatTipoEstablecimiento implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -4103020689721430747L;
    private Integer idTipoEstablecimiento;
    private String clave;
    private String nombre;
    private String descripcion;
    private Integer indicaDefault;
    private Integer estatus;
    private Date fechaRegistro;
    private String noUsuario;
    private Set<AdmHospital> admHospitals = new HashSet<AdmHospital>(0);

    public CatTipoEstablecimiento() {
    }

    public CatTipoEstablecimiento(Integer idTipoEstablecimiento) {
        this.idTipoEstablecimiento = idTipoEstablecimiento;
    }

    public CatTipoEstablecimiento(Integer idTipoEstablecimiento, String clave, String nombre, String descripcion,
                                  Integer indicaDefault, Integer estatus, Date fechaRegistro, String noUsuario) {
        this.idTipoEstablecimiento = idTipoEstablecimiento;
        this.clave = clave;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.indicaDefault = indicaDefault;
        this.estatus = estatus;
        this.fechaRegistro = fechaRegistro;
        this.noUsuario = noUsuario;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "TIPO_ESTABLECIMIENTO_ID", unique = true, nullable = false)
    public Integer getIdTipoEstablecimiento() {
        return this.idTipoEstablecimiento;
    }

    public void setIdTipoEstablecimiento(Integer idTipoEstablecimiento) {
        this.idTipoEstablecimiento = idTipoEstablecimiento;
    }

    @Column(name = "CVE", length = 10)
    public String getClave() {
        return this.clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    @Column(name = "NOMBRE", length = 50)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "DESCRIPCION", length = 50)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "VALOR_DEFAULT")
    public Integer getIndicaDefault() {
        return this.indicaDefault;
    }

    public void setIndicaDefault(Integer indicaDefault) {
        this.indicaDefault = indicaDefault;
    }

    @Column(name = "ESTATUS")
    public Integer getEstatus() {
        return this.estatus;
    }

    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_REGISTRO", length = 7)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Column(name = "USUARIO_REGISTRO", length = 20)
    public String getNoUsuario() {
        return this.noUsuario;
    }

    public void setNoUsuario(String noUsuario) {
        this.noUsuario = noUsuario;
    }
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoEstablecimiento")
    public Set<AdmHospital> getAdmHospitals() {
        return this.admHospitals;
    }

    public void setAdmHospitals(Set<AdmHospital> admHospitals) {
        this.admHospitals = admHospitals;
    }

}

