package hts.backend.entity;
// Generated 27-feb-2017 9:57:50 by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CatTipoEquipo generated by hbm2java
 */
@Entity
@Table(name = "cat_tipo_equipo")
public class CatTipoEquipo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;


	private Integer tipoEquipoId;
	private String cve;
	private String nombre;
	private String descripcion;
	private Integer indicaDefault;
	private Integer status;
	private Date fechaRegistro;
	private String noUsuario;
	private Set<AdmEquipo> admEquipos = new HashSet<>(0);

	public CatTipoEquipo() {
	}

	public CatTipoEquipo(Integer tipoEquipoId) {
		this.tipoEquipoId = tipoEquipoId;
	}

	public CatTipoEquipo(Integer tipoEquipoId, String cve, String nombre, String descripcion,
						 Integer indicaDefault, Integer status, Date fechaRegistro, String noUsuario,
						 Set<AdmEquipo> admEquipos) {
		this.tipoEquipoId = tipoEquipoId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.indicaDefault = indicaDefault;
		this.status = status;
		this.fechaRegistro = fechaRegistro;
		this.noUsuario = noUsuario;
		this.admEquipos = admEquipos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "TIPO_EQUIPO_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getTipoEquipoId() {
		return this.tipoEquipoId;
	}

	public void setTipoEquipoId(Integer tipoEquipoId) {
		this.tipoEquipoId = tipoEquipoId;
	}

	@Column(name = "CVE", length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", precision = 22, scale = 0)
	public Integer getIndicaDefault() {
		return this.indicaDefault;
	}

	public void setIndicaDefault(Integer indicaDefault) {
		this.indicaDefault = indicaDefault;
	}

	@Column(name = "ESTATUS", precision = 22, scale = 0)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", length = 20)
	public String getNoUsuario() {
		return this.noUsuario;
	}

	public void setNoUsuario(String noUsuario) {
		this.noUsuario = noUsuario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoEquipo")
	public Set<AdmEquipo> getAdmEquipos() {
		return this.admEquipos;
	}

	public void setAdmEquipos(Set<AdmEquipo> admEquipos) {
		this.admEquipos = admEquipos;
	}
}
