package hts.backend.entity;


// Generated 24/02/2017 07:59:12 PM by Hibernate Tools 5.2.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * CatTipoAsen generated by hbm2java
 */
@Entity
@Table(name = "cat_tipo_asen")
public class CatTipoAsen implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer tipoAsenId;
	private Integer clave;
	private String nombre;
	private String descripcion;
	private Integer indicaDefault;
	private Integer status;
	private Date fechaRegistro;
	private String noUsuario;
	private Set<Direccion> direccions = new HashSet<Direccion>(0);

	public CatTipoAsen() {
	}

	public CatTipoAsen(Integer tipoAsenId) {
		this.tipoAsenId = tipoAsenId;
	}

	public CatTipoAsen(Integer tipoAsenId, Integer clave, String nombre, String descripcion,
			Integer indicaDefault, Integer status, Date fechaRegistro, String noUsuario,
			Set<Direccion> direccions) {
		this.tipoAsenId = tipoAsenId;
		this.clave = clave;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.indicaDefault = indicaDefault;
		this.status = status;
		this.fechaRegistro = fechaRegistro;
		this.noUsuario = noUsuario;
		this.direccions = direccions;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "TIPO_ASEN_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getTipoAsenId() {
		return this.tipoAsenId;
	}

	public void setTipoAsenId(Integer tipoAsenId) {
		this.tipoAsenId = tipoAsenId;
	}

	@Column(name = "CVE", precision = 22, scale = 0)
	public Integer getClave() {
		return this.clave;
	}

	public void setClave(Integer clave) {
		this.clave = clave;
	}

	@Column(name = "NOMBRE", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", precision = 22, scale = 0)
	public Integer getIndicaDefault() {
		return this.indicaDefault;
	}

	public void setIndicaDefault(Integer indicaDefault) {
		this.indicaDefault = indicaDefault;
	}

	@Column(name = "ESTATUS", precision = 22, scale = 0)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", length = 20)
	public String getNoUsuario() {
		return this.noUsuario;
	}

	public void setNoUsuario(String noUsuario) {
		this.noUsuario = noUsuario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoAsen")
	public Set<Direccion> getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set<Direccion> direccions) {
		this.direccions = direccions;
	}

}
