package hts.backend.entity;
// Generated 28/03/2017 06:24:11 PM by Hibernate Tools 5.2.0.CR1

import hts.backend.entity.FacturacionEvento;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CatTipoEpisodio generated by hbm2java
 */
@Entity
@Table(name = "nom_cat_tipo_episodio")
public class CatTipoEpisodio implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private int tipoEpisodioId;
	private CatIdiomaApp catIdiomaApp;
	private String cve;
	private String nombre;
	private String descripcion;
	private int valorDefault;
	private int estatus;
	private Date fechaRegistro;
	private String usuarioRegistro;
	private Set<PacConvenioDetalleEvento> pacConvenioDetalleEventos = new HashSet<PacConvenioDetalleEvento>(0);
	private Set<PacEpisodio> pacEpisodiosByTipoEpisodioId= new HashSet<PacEpisodio>(0);
	private Set<FacturacionEvento> facturacionEventosByTipoEpisodioId;

	public CatTipoEpisodio() {
	}

	public CatTipoEpisodio(int tipoEpisodioId) {
		this.tipoEpisodioId = tipoEpisodioId;
	}

	public CatTipoEpisodio(int tipoEpisodioId, String cve, String nombre, String descripcion,
						   int valorDefault, int estatus, Date fechaRegistro, String usuarioRegistro) {
		this.tipoEpisodioId = tipoEpisodioId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
	}

	public CatTipoEpisodio(int tipoEpisodioId, CatIdiomaApp catIdiomaApp, String cve, String nombre,
			String descripcion, int valorDefault, int estatus, Date fechaRegistro, String usuarioRegistro,
			Set<PacConvenioDetalleEvento> pacConvenioDetalleEventos) {
		this.tipoEpisodioId = tipoEpisodioId;
		this.catIdiomaApp = catIdiomaApp;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
		this.pacConvenioDetalleEventos = pacConvenioDetalleEventos;
	}

	@Id

	@Column(name = "TIPO_EPISODIO_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getTipoEpisodioId() {
		return this.tipoEpisodioId;
	}

	public void setTipoEpisodioId(int tipoEpisodioId) {
		this.tipoEpisodioId = tipoEpisodioId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDIOMA_APP_ID")
	public CatIdiomaApp getCatIdiomaApp() {
		return this.catIdiomaApp;
	}

	public void setCatIdiomaApp(CatIdiomaApp catIdiomaApp) {
		this.catIdiomaApp = catIdiomaApp;
	}

	@Column(name = "CVE", nullable = false, length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, precision = 22, scale = 0)
	public int getValorDefault() {
		return this.valorDefault;
	}

	public void setValorDefault(int valorDefault) {
		this.valorDefault = valorDefault;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoEpisodio")
	public Set<PacConvenioDetalleEvento> getPacConvenioDetalleEventos() {
		return this.pacConvenioDetalleEventos;
	}

	public void setPacConvenioDetalleEventos(Set<PacConvenioDetalleEvento> pacConvenioDetalleEventos) {
		this.pacConvenioDetalleEventos = pacConvenioDetalleEventos;
	}

	@OneToMany(mappedBy = "tipoEpisodio")
	public Set<PacEpisodio> getPacEpisodiosByTipoEpisodioId() {
		return pacEpisodiosByTipoEpisodioId;
	}

	public void setPacEpisodiosByTipoEpisodioId(Set<PacEpisodio> pacEpisodiosByTipoEpisodioId) {
		this.pacEpisodiosByTipoEpisodioId = pacEpisodiosByTipoEpisodioId;
	}

	@OneToMany(mappedBy = "catTipoEpisodioByTipoEpisodioId") public Set<FacturacionEvento> getFacturacionEventosByTipoEpisodioId() {
		return facturacionEventosByTipoEpisodioId;
	}

	public void setFacturacionEventosByTipoEpisodioId(Set<FacturacionEvento> facturacionEventosByTipoEpisodioId) {
		this.facturacionEventosByTipoEpisodioId = facturacionEventosByTipoEpisodioId;
	}
}
