package hts.backend.entity;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * CatTipoPauta generated by hbm2java
 */
@Entity
@Table(name = "nom_cat_tipo_pauta")
public class CatTipoPauta implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private int tipoPautaId;
    private String descripcion;
    private Date fechaResgistro;
    private String usuarioRegistro;
    private String cve;
    private String nombre;
    private int defauls;
    private int estatus;
    private Set<CorePauta> corePautas = new HashSet<CorePauta>(0);
    private CatIdiomaApp catIdiomaAppByIdiomaAppId;

    public CatTipoPauta() {
    }

    public CatTipoPauta(int tipoPautaId, String descripcion, Date fechaResgistro, String usuarioRegistro,
                        String cve, String nombre, int defauls, int estatus) {
        this.tipoPautaId = tipoPautaId;
        this.descripcion = descripcion;
        this.fechaResgistro = fechaResgistro;
        this.usuarioRegistro = usuarioRegistro;
        this.cve = cve;
        this.nombre = nombre;
        this.defauls = defauls;
        this.estatus = estatus;
    }

    public CatTipoPauta(int tipoPautaId, String descripcion, Date fechaResgistro, String usuarioRegistro,
                        String cve, String nombre, int defauls, int estatus, Set corePautas) {
        this.tipoPautaId = tipoPautaId;
        this.descripcion = descripcion;
        this.fechaResgistro = fechaResgistro;
        this.usuarioRegistro = usuarioRegistro;
        this.cve = cve;
        this.nombre = nombre;
        this.defauls = defauls;
        this.estatus = estatus;
        this.corePautas = corePautas;
    }

    @Id

    @Column(name = "TIPO_PAUTA_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public int getTipoPautaId() {
        return this.tipoPautaId;
    }

    public void setTipoPautaId(int tipoPautaId) {
        this.tipoPautaId = tipoPautaId;
    }

    @Column(name = "DESCRIPCION", nullable = false, length = 20)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
    public Date getFechaResgistro() {
        return this.fechaResgistro;
    }

    public void setFechaResgistro(Date fechaResgistro) {
        this.fechaResgistro = fechaResgistro;
    }

    @Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
    public String getUsuarioRegistro() {
        return this.usuarioRegistro;
    }

    public void setUsuarioRegistro(String usuarioRegistro) {
        this.usuarioRegistro = usuarioRegistro;
    }

    @Column(name = "CVE", nullable = false, length = 20)
    public String getCve() {
        return this.cve;
    }

    public void setCve(String cve) {
        this.cve = cve;
    }

    @Column(name = "NOMBRE", nullable = false, length = 20)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "VALOR_DEFAULT", nullable = false, precision = 22, scale = 0)
    public int getDefauls() {
        return this.defauls;
    }

    public void setDefauls(int defauls) {
        this.defauls = defauls;
    }

    @Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
    public int getEstatus() {
        return this.estatus;
    }

    public void setEstatus(int estatus) {
        this.estatus = estatus;
    }


    @OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoPauta")
    public Set<CorePauta> getCorePautas() {
        return corePautas;
    }

    public void setCorePautas(Set<CorePauta> corePautas) {
        this.corePautas = corePautas;
    }

    @ManyToOne @JoinColumn( name = "IDIOMA_APP_ID", referencedColumnName = "IDIOMA_APP_ID", nullable = false)
    public CatIdiomaApp getCatIdiomaAppByIdiomaAppId() {
        return catIdiomaAppByIdiomaAppId;
    }

    public void setCatIdiomaAppByIdiomaAppId(CatIdiomaApp catIdiomaAppByIdiomaAppId) {
        this.catIdiomaAppByIdiomaAppId = catIdiomaAppByIdiomaAppId;
    }

}
