package hts.backend.entity;
// Generated 24-ene-2017 15:08:05 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * CatTipoHabitacion generated by hbm2java
 */
@Entity
@Table(name = "cat_tipo_habitacion")
public class CatTipoHabitacion implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer tipoHabitacionId;
	private String cve;
	private String nombre;
	private String descripcion;
	private Integer valorDefault;
	private Integer status;
	private Date fechaRegistro;
	private String usuarioRegistra;
	private Set<AdmHabitacion> admHabitacions = new HashSet<AdmHabitacion>(0);

	public CatTipoHabitacion() {
	}

	public CatTipoHabitacion(Integer tipoHabitacionId) {
		this.tipoHabitacionId = tipoHabitacionId;
	}

	public CatTipoHabitacion(Integer tipoHabitacionId, String cve, String nombre, String descripcion,
			Integer valorDefault, Integer status, Date fechaRegistro, String usuarioRegistra,
			Set<AdmHabitacion> admHabitacions) {
		this.tipoHabitacionId = tipoHabitacionId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.status = status;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
		this.admHabitacions = admHabitacions;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "TIPO_HABITACION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getTipoHabitacionId() {
		return this.tipoHabitacionId;
	}

	public void setTipoHabitacionId(Integer tipoHabitacionId) {
		this.tipoHabitacionId = tipoHabitacionId;
	}

	@Column(name = "CVE", length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", precision = 22, scale = 0)
	public Integer getValorDefault() {
		return this.valorDefault;
	}

	public void setValorDefault(Integer valorDefault) {
		this.valorDefault = valorDefault;
	}

	@Column(name = "ESTATUS", precision = 22, scale = 0)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoHabitacion")
	public Set<AdmHabitacion> getAdmHabitacions() {
		return this.admHabitacions;
	}

	public void setAdmHabitacions(Set<AdmHabitacion> admHabitacions) {
		this.admHabitacions = admHabitacions;
	}

}
