package hts.backend.entity;
// Generated 17/03/2017 11:00:42 AM by Hibernate Tools 5.2.0.CR1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CatUnidadMedidaPres generated by hbm2java
 */
@Entity
@Table(name = "cat_unidad_medida_pres")
public class CatUnidadMedidaPres implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private int unidadMedidaPresId;
	private String cve;
	private String nombre;
	private String descripcion;
	private int valorDefault;
	private int estatus;
	private Date fechaRegistro;
	private String usuarioRegistra;
	private CatIdiomaApp catIdiomaApp;
	private Set<NomPrductoPrestacion> nomPrductoPrestacions = new HashSet<NomPrductoPrestacion>(0);


	public CatUnidadMedidaPres() {
	}

	public CatUnidadMedidaPres(int unidadMedidaPresId, String cve, String nombre, String descripcion,
							   int valorDefault, int estatus, Date fechaRegistro, String usuarioRegistra) {
		this.unidadMedidaPresId = unidadMedidaPresId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
	}

	public CatUnidadMedidaPres(int unidadMedidaPresId, String cve, String nombre, String descripcion,
							   int valorDefault, int estatus, Date fechaRegistro, String usuarioRegistra,
							   CatIdiomaApp catIdiomaApp, Set<NomPrductoPrestacion> nomPrductoPrestacions) {
		this.unidadMedidaPresId = unidadMedidaPresId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
		this.catIdiomaApp = catIdiomaApp;
		this.nomPrductoPrestacions = nomPrductoPrestacions;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "UNIDAD_MEDIDA_PRES_ID", unique = true, nullable = false, precision = 22)
	public int getUnidadMedidaPresId() {
		return this.unidadMedidaPresId;
	}

	public void setUnidadMedidaPresId(int unidadMedidaPresId) {
		this.unidadMedidaPresId = unidadMedidaPresId;
	}

	@Column(name = "CVE", nullable = false, length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, precision = 22)
	public int getValorDefault() {
		return this.valorDefault;
	}

	public void setValorDefault(int valorDefault) {
		this.valorDefault = valorDefault;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22)
	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDIOMA_APP_ID")
	public CatIdiomaApp getCatIdiomaApp() {
		return this.catIdiomaApp;
	}

	public void setCatIdiomaApp(CatIdiomaApp catIdiomaApp) {
		this.catIdiomaApp = catIdiomaApp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catUnidadMedidaPres")
	public Set<NomPrductoPrestacion> getNomPrductoPrestacions() {
		return this.nomPrductoPrestacions;
	}

	public void setNomPrductoPrestacions(Set<NomPrductoPrestacion> nomPrductoPrestacions) {
		this.nomPrductoPrestacions = nomPrductoPrestacions;
	}
}
