package hts.backend.entity;
// Generated 15/05/2017 06:36:43 PM by Hibernate Tools 5.2.0.Beta1

import hts.backend.entity.CexMedicamentosMateriales;
import hts.backend.entity.CexPrescripcionesMedicamento;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CatUnidadMedidaDosis generated by hbm2java
 */
@Entity
@Table(name = "cat_unidad_medida_dosis")
public class CatUnidadMedidaDosis implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer unidadMedidaDosisId;
	private String cve;
	private String nombre;
	private String descripcion;
	private String valorDefault;
	private Integer estatus;
	private Date fechaRegistro;
	private String usuarioRegistro;
	private CatIdiomaApp catIdiomaApp;
	private Set<CexMedicamentosMateriales> cexMedicamentosMaterialeses = new HashSet<CexMedicamentosMateriales>(0);
	private Set<CexPrescripcionesMedicamento> cexPrescripcionesMedicamentos = new HashSet<CexPrescripcionesMedicamento>(0);

	public CatUnidadMedidaDosis() {
	}

	public CatUnidadMedidaDosis(Integer unidadMedidaDosisId) {
		this.unidadMedidaDosisId = unidadMedidaDosisId;
	}

	public CatUnidadMedidaDosis(Integer unidadMedidaDosisId, String cve, String nombre, String descripcion,
								String valorDefault, Integer estatus, Date fechaRegistro, String usuarioRegistro,
								Set cexMedicamentosMaterialeses) {
		this.unidadMedidaDosisId = unidadMedidaDosisId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
		this.cexMedicamentosMaterialeses = cexMedicamentosMaterialeses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "UNIDAD_MEDIDA_DOSIS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getUnidadMedidaDosisId() {
		return this.unidadMedidaDosisId;
	}

	public void setUnidadMedidaDosisId(Integer unidadMedidaDosisId) {
		this.unidadMedidaDosisId = unidadMedidaDosisId;
	}

	@Column(name = "CVE", length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", length = 20)

	public String getValorDefault() {
		return valorDefault;
	}

	public void setValorDefault(String valorDefault) {
		this.valorDefault = valorDefault;
	}


	@Column(name = "ESTATUS", length = 20)
	public Integer getEstatus() {
		return estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}


	@Column(name = "FECHA_REGISTRO", length = 20)

	public Date getFechaRegistro() {
		return fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", length = 20)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catUnidadMedidaDosis")

	public Set<CexMedicamentosMateriales> getCexMedicamentosMaterialeses() {
		return cexMedicamentosMaterialeses;
	}

	public void setCexMedicamentosMaterialeses(Set<CexMedicamentosMateriales> cexMedicamentosMaterialeses) {
		this.cexMedicamentosMaterialeses = cexMedicamentosMaterialeses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDIOMA_APP_ID", nullable = false)
	public CatIdiomaApp getCatIdiomaApp() {
		return catIdiomaApp;
	}

	public void setCatIdiomaApp(CatIdiomaApp catIdiomaApp) {
		this.catIdiomaApp = catIdiomaApp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catUnidadMedidaDosis")
	public Set<CexPrescripcionesMedicamento> getCexPrescripcionesMedicamentos() {
		return this.cexPrescripcionesMedicamentos;
	}

	public void setCexPrescripcionesMedicamentos(Set<CexPrescripcionesMedicamento> cexPrescripcionesMedicamentos) {
		this.cexPrescripcionesMedicamentos = cexPrescripcionesMedicamentos;
	}
}
