package hts.backend.entity;

// Generated 24/02/2017 07:59:12 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * CatVialidad generated by hbm2java
 */
@Entity
@Table(name = "cat_vialidad")
public class CatVialidad implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer vialidadId;
	private String clave;
	private String nombre;
	private String descripcion;
	private Integer indicaDefault;
	private Integer estatus;
	private Date fechaRegistro;
	private String noUsuario;
	private Set<Direccion> direccions = new HashSet<Direccion>(0);
	private Set<AdmHospital> admHospitals = new HashSet<AdmHospital>(0);

	public CatVialidad() {
	}

	public CatVialidad(Integer vialidadId) {
		this.vialidadId = vialidadId;
	}

	public CatVialidad(Integer vialidadId, String clave, String nombre, String descripcion,
					   Integer indicaDefault, Integer estatus, Date fechaRegistro, String noUsuario,
					   Set<Direccion> direccions) {
		this.vialidadId = vialidadId;
		this.clave = clave;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.indicaDefault = indicaDefault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
		this.noUsuario = noUsuario;
		this.direccions = direccions;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "VIALIDAD_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getVialidadId() {
		return this.vialidadId;
	}

	public void setVialidadId(Integer vialidadId) {
		this.vialidadId = vialidadId;
	}

	@Column(name = "CVE", precision = 22, scale = 0)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "NOMBRE", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", precision = 22, scale = 0)
	public Integer getIndicaDefault() {
		return this.indicaDefault;
	}

	public void setIndicaDefault(Integer indicaDefault) {
		this.indicaDefault = indicaDefault;
	}

	@Column(name = "ESTATUS", precision = 22, scale = 0)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", length = 20)
	public String getNoUsuario() {
		return this.noUsuario;
	}

	public void setNoUsuario(String noUsuario) {
		this.noUsuario = noUsuario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catVialidad")
	public Set<Direccion> getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set<Direccion> direccions) {
		this.direccions = direccions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catVialidad")
	public Set<AdmHospital> getAdmHospitals() {
		return this.admHospitals;
	}

	public void setAdmHospitals(Set<AdmHospital> admHospitals) {
		this.admHospitals = admHospitals;
	}


}
