package hts.backend.entity;
// Generated 15/05/2017 06:36:43 PM by Hibernate Tools 5.2.0.Beta1


import hts.backend.entity.CexMedicamentosMateriales;
import hts.backend.entity.CexPrescripcionesMedicamento;
import hts.backend.entity.CorePrescripcionesSoluciones;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CatViaAdministracion generated by hbm2java
 */
@Entity
@Table(name = "cat_via_administracion")
public class CatViaAdministracion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer viaAdministracionId;
	private String cve;
	private String nombre;
	private String descripcion;
	private Integer valorDefault;
	private Integer estatus;
	private Date fechaRegistro;
	private String usuarioRegistro;
	private Integer idiomaAppId;
	private CatIdiomaApp catIdiomaApp;
	private Set<CexMedicamentosMateriales> cexMedicamentosMaterialeses = new HashSet<CexMedicamentosMateriales>(0);
	private Set<CexPrescripcionesMedicamento> cexPrescripcionesMedicamentos = new HashSet<CexPrescripcionesMedicamento>(0);
	private Set<CorePrescripcionesSoluciones> corePrescripcionesSolucionesByViaAdministracionId;
	private Set<CorePrescripcionesSoluciones> corePrescripcionesSolucionesByViaAdministracionId_0;

	@OneToMany(mappedBy = "catViaAdministracionByViaAdministracionId") public Set<CorePrescripcionesSoluciones> getCorePrescripcionesSolucionesByViaAdministracionId() {
		return corePrescripcionesSolucionesByViaAdministracionId;
	}

	public void setCorePrescripcionesSolucionesByViaAdministracionId(Set<CorePrescripcionesSoluciones> corePrescripcionesSolucionesByViaAdministracionId) {
		this.corePrescripcionesSolucionesByViaAdministracionId = corePrescripcionesSolucionesByViaAdministracionId;
	}

	@OneToMany(mappedBy = "catViaAdministracionByViaAdministracionIdMed") public Set<CorePrescripcionesSoluciones> getCorePrescripcionesSolucionesByViaAdministracionId_0() {
		return corePrescripcionesSolucionesByViaAdministracionId_0;
	}

	public void setCorePrescripcionesSolucionesByViaAdministracionId_0(Set<CorePrescripcionesSoluciones> corePrescripcionesSolucionesByViaAdministracionId_0) {
		this.corePrescripcionesSolucionesByViaAdministracionId_0 = corePrescripcionesSolucionesByViaAdministracionId_0;
	}


	public CatViaAdministracion() {
	}

	public CatViaAdministracion(Integer viaAdministracionId, String cve, String nombre, String descripcion,
								Integer valorDafault, Integer estatus, Date fechaRegistro, String usuarioRegistro) {
		this.viaAdministracionId = viaAdministracionId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDafault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
	}

	public CatViaAdministracion(Integer viaAdministracionId, String cve, String nombre, String descripcion,
								Integer valorDafault, Integer estatus, Date fechaRegistro, String usuarioRegistro,
								Integer idiomaAppId, Set cexMedicamentosMaterialeses) {
		this.viaAdministracionId = viaAdministracionId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
		this.idiomaAppId = idiomaAppId;
		this.cexMedicamentosMaterialeses = cexMedicamentosMaterialeses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "VIA_ADMINISTRACION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getViaAdministracionId() {
		return this.viaAdministracionId;
	}

	public void setViaAdministracionId(Integer viaAdministracionId) {
		this.viaAdministracionId = viaAdministracionId;
	}

	@Column(name = "CVE", nullable = false, length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, precision = 22, scale = 0)
	public Integer getvalorDefault() {
		return this.valorDefault;
	}

	public void setvalorDefault(Integer valorDefault) {
		this.valorDefault = valorDefault;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catViaAdministracion")
	public Set<CexMedicamentosMateriales> getCexMedicamentosMaterialeses() {
		return cexMedicamentosMaterialeses;
	}

	public void setCexMedicamentosMaterialeses(Set<CexMedicamentosMateriales> cexMedicamentosMaterialeses) {
		this.cexMedicamentosMaterialeses = cexMedicamentosMaterialeses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDIOMA_APP_ID", nullable = false)
	public CatIdiomaApp getCatIdiomaApp() {
		return catIdiomaApp;
	}

	public void setCatIdiomaApp(CatIdiomaApp catIdiomaApp) {
		this.catIdiomaApp = catIdiomaApp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catViaAdministracion")
	public Set<CexPrescripcionesMedicamento> getCexPrescripcionesMedicamentos() {
		return this.cexPrescripcionesMedicamentos;
	}

	public void setCexPrescripcionesMedicamentos(Set<CexPrescripcionesMedicamento> cexPrescripcionesMedicamentos) {
		this.cexPrescripcionesMedicamentos = cexPrescripcionesMedicamentos;
	}
}
