package hts.backend.entity;
// Generated 12/05/2017 02:12:43 PM by Hibernate Tools 5.2.0.CR1

import org.hibernate.criterion.SimpleExpression;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * CexGenericos generated by hbm2java
 */
@Entity
@Table(name = "cex_genericos")
public class CexGenericos implements java.io.Serializable {

	private Integer genericoId;
	private CexPrincipiosActivos cexPrincipiosActivos;
	private String cve;
	private String nombre;
	private String descripcion;
	private Integer valorDefault;
	private Integer estatus;
	private Date fechaRegistro;
	private String usuarioRegistro;
	private Set<CexMedicamentosMateriales> cexMedicamentosMaterialeses = new HashSet<CexMedicamentosMateriales>(0);

	public CexGenericos() {
	}

	public CexGenericos(Integer genericoId, CexPrincipiosActivos cexPrincipiosActivos, String cve, String nombre,
						String descripcion, Integer valorDefault, Integer estatus, Date fechaRegistro,
						String usuarioRegistro) {
		this.genericoId = genericoId;
		this.cexPrincipiosActivos = cexPrincipiosActivos;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "GENERICO_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getGenericoId() {
		return this.genericoId;
	}

	public void setGenericoId(Integer genericoId) {
		this.genericoId = genericoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRINCIPIO_ACTIVO_ID", nullable = false)
	public CexPrincipiosActivos getCexPrincipiosActivos() {
		return this.cexPrincipiosActivos;
	}

	public void setCexPrincipiosActivos(CexPrincipiosActivos cexPrincipiosActivos) {
		this.cexPrincipiosActivos = cexPrincipiosActivos;
	}

	@Column(name = "CVE", nullable = false, length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 1048)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 1048)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, precision = 22, scale = 0)
	public Integer getValorDefault() {
		return this.valorDefault;
	}

	public void setValorDefault(Integer valorDefault) {
		this.valorDefault = valorDefault;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cexGenericos")
	public Set<CexMedicamentosMateriales> getCexMedicamentosMaterialeses() {
		return cexMedicamentosMaterialeses;
	}

	public void setCexMedicamentosMaterialeses(Set<CexMedicamentosMateriales> cexMedicamentosMaterialeses) {
		this.cexMedicamentosMaterialeses = cexMedicamentosMaterialeses;
	}
}