package hts.backend.entity;
// Generated 8/05/2017 01:42:43 PM by Hibernate Tools 5.2.0.Beta1

import hts.backend.entity.NomCatMotivoAnulaCita;

import java.util.Date;
import javax.persistence.*;

/**
 * CexMotivoAnulacion generated by hbm2java
 */
@Entity
@Table(name = "cex_motivo_anulacion")
public class CexMotivoAnulacion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer anulacionId;
	private NomCatMotivoAnulaCita nomCatMotivoAnulaCita;
	private CexCitaPaciente cexCitaPaciente;
	private Date fechaRegistro;
	private String usuario;

	public CexMotivoAnulacion() {
	}

	public CexMotivoAnulacion(Integer anulacionId, NomCatMotivoAnulaCita nomCatMotivoAnulaCita,
							  CexCitaPaciente cexCitaPaciente, Date fechaRegistro, String usuario) {
		this.anulacionId = anulacionId;
		this.nomCatMotivoAnulaCita = nomCatMotivoAnulaCita;
		this.cexCitaPaciente = cexCitaPaciente;
		this.fechaRegistro = fechaRegistro;
		this.usuario = usuario;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ANULACION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getAnulacionId() {
		return this.anulacionId;
	}

	public void setAnulacionId(Integer anulacionId) {
		this.anulacionId = anulacionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOTIVO_ANULA_ID", nullable = false)
	public NomCatMotivoAnulaCita getNomCatMotivoAnulaCita() {
		return this.nomCatMotivoAnulaCita;
	}

	public void setNomCatMotivoAnulaCita(NomCatMotivoAnulaCita nomCatMotivoAnulaCita) {
		this.nomCatMotivoAnulaCita = nomCatMotivoAnulaCita;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CITA_PACIENTE_ID", nullable = false)
	public CexCitaPaciente getCexCitaPaciente() {
		return this.cexCitaPaciente;
	}

	public void setCexCitaPaciente(CexCitaPaciente cexCitaPaciente) {
		this.cexCitaPaciente = cexCitaPaciente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO", nullable = false, length = 20)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usaurio) {
		this.usuario = usaurio;
	}

}
