package hts.backend.entity;


import hts.backend.entity.*;

import javax.persistence.*;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CexMedicamentosMateriales generated by hbm2java
 */
@Entity
@Table(name = "cex_medicamentos_materiales")
public class CexMedicamentosMateriales implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer medicamentosMaterialesId;

    private CorePauta corePauta;
    private NomPrductoPrestacion nomPrductoPrestacion;
    private NomCatTipoPrestacion1 nomCatTipoPrestacion1;
    private CexGenericos cexGenericos;
    private CatFormaFarmaceutica catFormaFarmaceutica;
    private CatMedicamentoPresentaciones catMedicamentoPresentaciones;
    private CatGrupoTerapeutico catGrupoTerapeutico;
    private CatViaAdministracion catViaAdministracion;
    private CatUnidadMedidaDosis catUnidadMedidaDosis;

    private Integer unidadDispensacion;
    private Integer maxDispensacion;
    private String codInterno;
    private String idVademecum;
    private Float dosis;
    private Integer volumen;
    private Integer conPrescripcion;
    private Integer mezclaIv;
    private Integer cuadroBasico;
    private Integer controlado;
    private Integer antibiotico;
    private Integer multidosis;
    private Integer atencionPrimaria;
    private Integer fraccionable;
    private Integer suero;
    private Integer diluyente;
    private Integer nutricionEnteral;
    private Integer nutricionParenteral;
    private Integer oxigeno;
    private String observacionesPreescripcion;
    private Integer valorDefault;
    private Integer estatus;
    private Date fechaRegistro;
    private String usuarioRegistro;
    private Set<CexPrescripcionesMedicamento> cexPrescripcionesMedicamentos = new HashSet<CexPrescripcionesMedicamento>(0);

    public CexMedicamentosMateriales() {
    }


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "MEDICAMENTOS_MATERIALES_ID", unique = true, precision = 22, scale = 0)
    public Integer getMedicamentosMaterialesId() {
        return medicamentosMaterialesId;
    }

    public void setMedicamentosMaterialesId(Integer medicamentosMaterialesId) {
        this.medicamentosMaterialesId = medicamentosMaterialesId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PAUTA_ID")
    public CorePauta getCorePauta() {
        return this.corePauta;
    }

    public void setCorePauta(CorePauta corePauta) {
        this.corePauta = corePauta;
    }


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PRODUCTO_PRESTACION_ID")
    public NomPrductoPrestacion getNomPrductoPrestacion() {
        return this.nomPrductoPrestacion;
    }

    public void setNomPrductoPrestacion(NomPrductoPrestacion nomPrductoPrestacion) {
        this.nomPrductoPrestacion = nomPrductoPrestacion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TIPO_PRESTACION1_ID")
    public NomCatTipoPrestacion1 getNomCatTipoPrestacion1() {
        return this.nomCatTipoPrestacion1;
    }

    public void setNomCatTipoPrestacion1(NomCatTipoPrestacion1 nomCatTipoPrestacion1) {
        this.nomCatTipoPrestacion1 = nomCatTipoPrestacion1;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GENERICO_ID")
    public CexGenericos getCexGenericos() {
        return this.cexGenericos;
    }

    public void setCexGenericos(CexGenericos cexGenericos) {
        this.cexGenericos = cexGenericos;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FORMA_FARMACEUTICA_ID")
    public CatFormaFarmaceutica getCatFormaFarmaceutica() {
        return this.catFormaFarmaceutica;
    }

    public void setCatFormaFarmaceutica(CatFormaFarmaceutica catFormaFarmaceutica) {
        this.catFormaFarmaceutica = catFormaFarmaceutica;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PRESENTACIONES_ID")
    public CatMedicamentoPresentaciones getCatMedicamentoPresentaciones() {
        return this.catMedicamentoPresentaciones;
    }

    public void setCatMedicamentoPresentaciones(CatMedicamentoPresentaciones catMedicamentoPresentaciones) {
        this.catMedicamentoPresentaciones = catMedicamentoPresentaciones;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GRUPO_TERAPEUTICO_ID")
    public CatGrupoTerapeutico getCatGrupoTerapeutico() {
        return this.catGrupoTerapeutico;
    }

    public void setCatGrupoTerapeutico(CatGrupoTerapeutico catGrupoTerapeutico) {
        this.catGrupoTerapeutico = catGrupoTerapeutico;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "VIA_ADMINISTRACION_ID")
    public CatViaAdministracion getCatViaAdministracion() {
        return this.catViaAdministracion;
    }

    public void setCatViaAdministracion(CatViaAdministracion catViaAdministracion) {
        this.catViaAdministracion = catViaAdministracion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UNIDAD_MEDIDA_DOSIS_ID")
    public CatUnidadMedidaDosis getCatUnidadMedidaDosis() {
        return this.catUnidadMedidaDosis;
    }

    public void setCatUnidadMedidaDosis(CatUnidadMedidaDosis catUnidadMedidaDosis) {
        this.catUnidadMedidaDosis = catUnidadMedidaDosis;
    }


    @Column(name = "UNIDAD_DISPENSACION", precision = 22, scale = 0)
    public Integer getUnidadDispensacion() {
        return unidadDispensacion;
    }

    public void setUnidadDispensacion(Integer unidadDispensacion) {
        this.unidadDispensacion = unidadDispensacion;
    }


    @Column(name = "MAX_DISPENSACION", precision = 22, scale = 0)

    public Integer getMaxDispensacion() {
        return maxDispensacion;
    }

    public void setMaxDispensacion(Integer maxDispensacion) {
        this.maxDispensacion = maxDispensacion;
    }

    @Column(name = "COD_INTERNO", length = 20)
    public String getCodInterno() {
        return this.codInterno;
    }

    public void setCodInterno(String codInterno) {
        this.codInterno = codInterno;
    }


    @Column(name = "ID_VADEMECUM", precision = 22, scale = 0)
    public String getIdVademecum() {
        return idVademecum;
    }

    public void setIdVademecum(String idVademecum) {
        this.idVademecum = idVademecum;
    }

    @Column(name = "DOSIS", precision = 22, scale = 0)
    public Float getDosis() {
        return dosis;
    }

    public void setDosis(Float dosis) {
        this.dosis = dosis;
    }

    @Column(name = "VOLUMEN", precision = 22, scale = 0)
    public Integer getVolumen() {
        return this.volumen;
    }

    public void setVolumen(Integer volumen) {
        this.volumen = volumen;
    }

    @Column(name = "CON_PRESCRIPCION", precision = 22, scale = 0)
    public Integer getConPrescripcion() {
        return this.conPrescripcion;
    }

    public void setConPrescripcion(Integer conPrescripcion) {
        this.conPrescripcion = conPrescripcion;
    }

    @Column(name = "MEZCLA_IV", precision = 22, scale = 0)
    public Integer getMezclaIv() {
        return this.mezclaIv;
    }

    public void setMezclaIv(Integer mezclaIv) {
        this.mezclaIv = mezclaIv;
    }

    @Column(name = "CUADRO_BASICO", precision = 22, scale = 0)
    public Integer getCuadroBasico() {
        return this.cuadroBasico;
    }

    public void setCuadroBasico(Integer cuadroBasico) {
        this.cuadroBasico = cuadroBasico;
    }

    @Column(name = "CONTROLADO", precision = 22, scale = 0)
    public Integer getControlado() {
        return controlado;
    }

    public void setControlado(Integer controlado) {
        this.controlado = controlado;
    }

    @Column(name = "ANTIBIOTICO", precision = 22, scale = 0)
    public Integer getAntibiotico() {
        return this.antibiotico;
    }

    public void setAntibiotico(Integer antibiotico) {
        this.antibiotico = antibiotico;
    }

    @Column(name = "MULTIDOSIS", precision = 22, scale = 0)
    public Integer getMultidosis() {
        return this.multidosis;
    }

    public void setMultidosis(Integer multidosis) {
        this.multidosis = multidosis;
    }

    @Column(name = "ATENCION_PRIMARIA", precision = 22, scale = 0)
    public Integer getAtencionPrimaria() {
        return this.atencionPrimaria;
    }

    public void setAtencionPrimaria(Integer atencionPrimaria) {
        this.atencionPrimaria = atencionPrimaria;
    }

    @Column(name = "FRACCIONABLE", precision = 22, scale = 0)
    public Integer getFraccionable() {
        return this.fraccionable;
    }

    public void setFraccionable(Integer fraccionable) {
        this.fraccionable = fraccionable;
    }


    @Column(name = "SUERO", precision = 22, scale = 0)
    public Integer getSuero() {
        return suero;
    }

    public void setSuero(Integer suero) {
        this.suero = suero;
    }

    @Column(name = "DILUYENTE", precision = 22, scale = 0)
    public Integer getDiluyente() {
        return this.diluyente;
    }

    public void setDiluyente(Integer diluyente) {
        this.diluyente = diluyente;
    }

    @Column(name = "NUTRICION_ENTERAL", precision = 22, scale = 0)
    public Integer getNutricionEnteral() {
        return this.nutricionEnteral;
    }

    public void setNutricionEnteral(Integer nutricionEnteral) {
        this.nutricionEnteral = nutricionEnteral;
    }

    @Column(name = "NUTRICION_PARENTERAL", precision = 22, scale = 0)
    public Integer getNutricionParenteral() {
        return this.nutricionParenteral;
    }

    public void setNutricionParenteral(Integer nutricionParenteral) {
        this.nutricionParenteral = nutricionParenteral;
    }

    @Column(name = "OXIGENO", precision = 22, scale = 0)
    public Integer getOxigeno() {
        return this.oxigeno;
    }

    public void setOxigeno(Integer oxigeno) {
        this.oxigeno = oxigeno;
    }


    @Column(name = "OBSERVACIONES_PREESCRIPCION", length = 100)
    public String getObservacionesPreescripcion() {
        return observacionesPreescripcion;
    }

    public void setObservacionesPreescripcion(String observacionesPreescripcion) {
        this.observacionesPreescripcion = observacionesPreescripcion;
    }


    @Column(name = "VALOR_DEFAULT", precision = 22, scale = 0)
    public Integer getValorDefault() {
        return this.valorDefault;
    }

    public void setValorDefault(Integer valorDefault) {
        this.valorDefault = valorDefault;
    }

    @Column(name = "ESTATUS", precision = 22, scale = 0)
    public Integer getEstatus() {
        return this.estatus;
    }

    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_REGISTRO", length = 7)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Column(name = "USUARIO_REGISTRO", length = 20)
    public String getUsuarioRegistro() {
        return this.usuarioRegistro;
    }

    public void setUsuarioRegistro(String usuarioRegistro) {
        this.usuarioRegistro = usuarioRegistro;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cexMedicamentosMateriales")
    public Set<CexPrescripcionesMedicamento> getCexPrescripcionesMedicamentos() {
        return this.cexPrescripcionesMedicamentos;
    }

    public void setCexPrescripcionesMedicamentos(Set<CexPrescripcionesMedicamento> cexPrescripcionesMedicamentos) {
        this.cexPrescripcionesMedicamentos = cexPrescripcionesMedicamentos;
    }

}
