package hts.backend.entity;
// Generated 8/05/2017 01:42:43 PM by Hibernate Tools 5.2.0.Beta1

import hts.backend.entity.NomCatMotivoReprogrCita;
import hts.backend.entity.AdmAgendaCupo;
import hts.backend.entity.AdmAgendaCupos;

import java.util.Date;
import javax.persistence.*;

/**
 * CexMotivoReprogramacion generated by hbm2java
 */
@Entity
@Table(name = "cex_motivo_reprogramacion")
public class CexMotivoReprogramacion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer reprogramacionId;
	private NomCatMotivoReprogrCita nomCatMotivoReprogrCita;
	private CexCitaPaciente cexCitaPaciente;
	private String usuarioRegistra;
	private Date fechaRegistro;
	private AdmAgendaCupos cupoId;
	private Integer admAgendaCupoId;

	public CexMotivoReprogramacion() {
	}

	public CexMotivoReprogramacion(Integer reprogramacionId, NomCatMotivoReprogrCita nomCatMotivoReprogrCita,
								   CexCitaPaciente cexCitaPaciente, String usuarioRegistra, Date fechaRegistro, AdmAgendaCupos cupoId) {
		this.reprogramacionId = reprogramacionId;
		this.nomCatMotivoReprogrCita = nomCatMotivoReprogrCita;
		this.cexCitaPaciente = cexCitaPaciente;
		this.usuarioRegistra = usuarioRegistra;
		this.fechaRegistro = fechaRegistro;
		this.cupoId = cupoId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "REPROGRAMACION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getReprogramacionId() {
		return this.reprogramacionId;
	}

	public void setReprogramacionId(Integer reprogramacionId) {
		this.reprogramacionId = reprogramacionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOTIVO_REPROG_ID", nullable = false)
	public NomCatMotivoReprogrCita getNomCatMotivoReprogrCita() {
		return this.nomCatMotivoReprogrCita;
	}

	public void setNomCatMotivoReprogrCita(NomCatMotivoReprogrCita nomCatMotivoReprogrCita) {
		this.nomCatMotivoReprogrCita = nomCatMotivoReprogrCita;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CITA_PACIENTE_ID", nullable = false)
	public CexCitaPaciente getCexCitaPaciente() {
		return this.cexCitaPaciente;
	}

	public void setCexCitaPaciente(CexCitaPaciente cexCitaPaciente) {
		this.cexCitaPaciente = cexCitaPaciente;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@ManyToOne @JoinColumn(name = "CUPO_ID", referencedColumnName = "CUPO_ID", nullable = false)

	public AdmAgendaCupos getAdmAgendaCuposByCupoId() {
		return cupoId;
	}

	public void setAdmAgendaCuposByCupoId(AdmAgendaCupos cupoId) {
		this.cupoId = cupoId;
	}


	@Column(name = "ADM_AGENDA_CUPO_ID")
	public Integer getAdmAgendaCupoId() {
		return admAgendaCupoId;
	}

	public void setAdmAgendaCupoId(Integer admAgendaCupoId) {
		this.admAgendaCupoId = admAgendaCupoId;
	}
}
