package hts.backend.entity;
// Generated 4/05/2017 11:05:26 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.*;

/**
 * CexNotas generated by hbm2java
 */
@Entity
@Table(name = "cex_notas")
public class CexNotas implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int notasId;
	private CexCitaPaciente cexCitaPaciente;
	private String nota;
	private String usuarioRegistra;
	private Date fechaRegistro;

	public CexNotas() {
	}

	public CexNotas(int notasId, String nota, CexCitaPaciente cexCitaPaciente, String usuarioRegistra, Date fechaRegistro) {
		this.notasId = notasId;
		this.nota = nota;
		this.cexCitaPaciente = cexCitaPaciente;
		this.usuarioRegistra = usuarioRegistra;
		this.fechaRegistro = fechaRegistro;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "NOTAS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getNotasId() {
		return this.notasId;
	}

	public void setNotasId(int notasId) {
		this.notasId = notasId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CITA_PACIENTE_ID", nullable = false)
	public CexCitaPaciente getCexCitaPaciente() {
		return this.cexCitaPaciente;
	}

	public void setCexCitaPaciente(CexCitaPaciente cexCitaPaciente) {
		this.cexCitaPaciente = cexCitaPaciente;
	}

	@Column(name = "NOTA", nullable = false, length = 200)
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

}
