package hts.backend.entity;


import hts.backend.entity.*;

import java.util.Date;
import javax.persistence.*;

/**
 * CexPrescripcionesMedicamento generated by hbm2java
 */
@Entity
@Table(name = "cex_prescripciones_medicamento")
public class CexPrescripcionesMedicamento implements java.io.Serializable {

    private Integer prescripcionMedicamentoId;
    private CorePauta corePauta;
    private CatMotInterrupcionPresc catMotInterrupcionPresc;
    private CatViaAdministracion catViaAdministracion;
    private CatUnidadMedidaDosis catUnidadMedidaDosis;
    private CexReceta cexReceta;
    private Integer receta;
    private CexMedicamentosMateriales cexMedicamentosMateriales;
    private Integer controlado;
    private String indicaciones;
    private String diluyente;
    private Float cantidad;
    private Integer dias;
    private Integer pautaManual;
    //	private Integer eventoId;
    private Integer horaPautaManual;
    private Date fechaInicio;
    private Date fechaFin;
    private Integer totalMedicamento;
    private Date fechaRegistro;
    private String usuarioRegistro;
    private String noPrescripcion;
    private CatEstadoPrescripcion catEstadoPrescripcion;
    private Date fechaInterrupcion;
    private String usuarioInterrupcion;
    private CatTipoPrescripcion catTipoPrescripcion;



    public CexPrescripcionesMedicamento() {
    }

    public CexPrescripcionesMedicamento(Integer prescripcionMedicamentoId, CatViaAdministracion catViaAdministracion,
                                        CatUnidadMedidaDosis catUnidadMedidaDosis, CexReceta cexReceta, Integer receta, CexMedicamentosMateriales cexMedicamentosMateriales,
                                        Integer controlado, Float cantidad,
                                        Integer dias, Date fechaInicio, Date fechaFin, Integer totalMedicamento, Date fechaRegistro, String usuarioRegistro, String noPrescripcion, CatTipoPrescripcion catTipoPrescripcion) {
        this.prescripcionMedicamentoId = prescripcionMedicamentoId;
        this.catViaAdministracion = catViaAdministracion;
        this.catUnidadMedidaDosis = catUnidadMedidaDosis;
        this.cexReceta = cexReceta;
        this.receta = receta;
//		this.eventoId = eventoId;
        this.cexMedicamentosMateriales = cexMedicamentosMateriales;
        this.controlado = controlado;
        this.cantidad = cantidad;
        this.dias = dias;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.totalMedicamento = totalMedicamento;
        this.fechaRegistro = fechaRegistro;
        this.usuarioRegistro = usuarioRegistro;
        this.noPrescripcion = noPrescripcion;
        this.catTipoPrescripcion = catTipoPrescripcion;

    }

    public CexPrescripcionesMedicamento(Integer prescripcionMedicamentoId, CorePauta corePauta,
                                        CatMotInterrupcionPresc catMotInterrupcionPresc,
                                        CatViaAdministracion catViaAdministracion, CatUnidadMedidaDosis catUnidadMedidaDosis, CexReceta cexReceta,
                                        Integer receta, Integer medicamentosMaterialesId, Integer controlado, String indicaciones, String diluyente,
                                        Float cantidad, Integer dias, Integer pautaManual, Integer horaPautaManual,
                                        Date fechaInicio, Date fechaFin, Integer totalMedicamento, Date fechaRegistro, String usuarioRegistro, String noPrescripcion,
                                        CatEstadoPrescripcion catEstadoPrescripcion, Date fechaInterrupcion, String usuarioInterrupcion, CatTipoPrescripcion catTipoPrescripcion) {
        this.prescripcionMedicamentoId = prescripcionMedicamentoId;
        this.corePauta = corePauta;
        this.catMotInterrupcionPresc = catMotInterrupcionPresc;
        this.catViaAdministracion = catViaAdministracion;
        this.catUnidadMedidaDosis = catUnidadMedidaDosis;
        this.cexReceta = cexReceta;
        this.receta = receta;
//		this.eventoId = eventoId;
        this.cexMedicamentosMateriales = cexMedicamentosMateriales;
        this.controlado = controlado;
        this.indicaciones = indicaciones;
        this.diluyente = diluyente;
        this.cantidad = cantidad;
        this.dias = dias;
        this.pautaManual = pautaManual;
        this.horaPautaManual = horaPautaManual;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.totalMedicamento = totalMedicamento;
        this.fechaRegistro = fechaRegistro;
        this.usuarioRegistro = usuarioRegistro;
        this.noPrescripcion = noPrescripcion;
        this.catEstadoPrescripcion = catEstadoPrescripcion;
        this.fechaInterrupcion = fechaInterrupcion;
        this.usuarioInterrupcion = usuarioInterrupcion;
        this.catTipoPrescripcion = catTipoPrescripcion;

    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "PRESCRIPCION_MEDICAMENTO_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public Integer getPrescripcionMedicamentoId() {
        return this.prescripcionMedicamentoId;
    }

    public void setPrescripcionMedicamentoId(Integer prescripcionMedicamentoId) {
        this.prescripcionMedicamentoId = prescripcionMedicamentoId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PAUTA_ID")
    public CorePauta getCorePauta() {
        return this.corePauta;
    }

    public void setCorePauta(CorePauta corePauta) {
        this.corePauta = corePauta;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MOTIVO_INTERRUPCION_PRESC_ID", referencedColumnName = "MOT_INTERRUPCION_PRESC_ID")
    public CatMotInterrupcionPresc getCatMotInterrupcionPresc() {
        return this.catMotInterrupcionPresc;
    }

    public void setCatMotInterrupcionPresc(CatMotInterrupcionPresc catMotInterrupcionPresc) {
        this.catMotInterrupcionPresc = catMotInterrupcionPresc;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "VIA_ADMINISTRACION_ID", nullable = false)
    public CatViaAdministracion getCatViaAdministracion() {
        return this.catViaAdministracion;
    }

    public void setCatViaAdministracion(CatViaAdministracion catViaAdministracion) {
        this.catViaAdministracion = catViaAdministracion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UNIDAD_MEDIDA_DOSIS_ID")
    public CatUnidadMedidaDosis getCatUnidadMedidaDosis() {
        return this.catUnidadMedidaDosis;
    }

    public void setCatUnidadMedidaDosis(CatUnidadMedidaDosis catUnidadMedidaDosis) {
        this.catUnidadMedidaDosis = catUnidadMedidaDosis;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RECETA_ID", nullable = false)
    public CexReceta getCexReceta() {
        return this.cexReceta;
    }

    public void setCexReceta(CexReceta cexReceta) {
        this.cexReceta = cexReceta;
    }

    @Column(name = "RECETA", nullable = false, precision = 22, scale = 0)
    public Integer getReceta() {
        return this.receta;
    }

    public void setReceta(Integer receta) {
        this.receta = receta;
    }



    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MEDICAMENTOS_MATERIALES_ID", nullable = false)
    public CexMedicamentosMateriales getCexMedicamentosMateriales() {
        return this.cexMedicamentosMateriales;
    }

    public void setCexMedicamentosMateriales(CexMedicamentosMateriales cexMedicamentosMateriales) {
        this.cexMedicamentosMateriales = cexMedicamentosMateriales;
    }

    @Column(name = "CONTROLADO", nullable = false, precision = 22, scale = 0)
    public Integer getControlado() {
        return this.controlado;
    }

    public void setControlado(Integer controlado) {
        this.controlado = controlado;
    }

    @Column(name = "INDICACIONES", length = 100)
    public String getIndicaciones() {
        return this.indicaciones;
    }

    public void setIndicaciones(String indicaciones) {
        this.indicaciones = indicaciones;
    }

    @Column(name = "DILUYENTE", length = 50)
    public String getDiluyente() {
        return this.diluyente;
    }

    public void setDiluyente(String diluyente) {
        this.diluyente = diluyente;
    }

    @Column(name = "CANTIDAD", nullable = false, precision = 22, scale = 0)
    public Float getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(Float cantidad) {
        this.cantidad = cantidad;
    }

    @Column(name = "DIAS", nullable = false, precision = 22, scale = 0)
    public Integer getDias() {
        return this.dias;
    }

    public void setDias(Integer dias) {
        this.dias = dias;
    }

    @Column(name = "PAUTA_MANUAL", precision = 22, scale = 0)
    public Integer getPautaManual() {
        return this.pautaManual;
    }

    public void setPautaManual(Integer pautaManual) {
        this.pautaManual = pautaManual;
    }

    @Column(name = "HORA_PAUTA_MANUAL", precision = 22, scale = 0)
    public Integer getHoraPautaManual() {
        return this.horaPautaManual;
    }

    public void setHoraPautaManual(Integer horaPautaManual) {
        this.horaPautaManual = horaPautaManual;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FECHA_INICIO", nullable = false, length = 7)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FECHA_FIN", nullable = false, length = 7)
    public Date getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    @Column(name = "TOTAL_MEDICAMENTO", nullable = false, precision = 22, scale = 0)
    public Integer getTotalMedicamento() {
        return this.totalMedicamento;
    }

    public void setTotalMedicamento(Integer totalMedicamento) {
        this.totalMedicamento = totalMedicamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
    public String getUsuarioRegistro() {
        return this.usuarioRegistro;
    }

    public void setUsuarioRegistro(String usuarioRegistro) {
        this.usuarioRegistro = usuarioRegistro;
    }

    @Column(name = "NO_PRESCRIPCION", nullable = false, length = 20)
    public String getNoPrescripcion() {
        return this.noPrescripcion;
    }

    public void setNoPrescripcion(String noPrescripcion) {
        this.noPrescripcion = noPrescripcion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ESTADO_PRESCRIPCION_ID", nullable = false)
    public CatEstadoPrescripcion getCatEstadoPrescripcion() {
        return this.catEstadoPrescripcion;
    }

    public void setCatEstadoPrescripcion(CatEstadoPrescripcion catEstadoPrescripcion) {
        this.catEstadoPrescripcion = catEstadoPrescripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_INTERRUPCION", length = 7)
    public Date getFechaInterrupcion() {
        return this.fechaInterrupcion;
    }

    public void setFechaInterrupcion(Date fechaInterrupcion) {
        this.fechaInterrupcion = fechaInterrupcion;
    }

    @Column(name = "USUARIO_INTERRUPCION", length = 20)
    public String getUsuarioInterrupcion() {
        return this.usuarioInterrupcion;
    }

    public void setUsuarioInterrupcion(String usuarioInterrupcion) {
        this.usuarioInterrupcion = usuarioInterrupcion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TIPO_PRESCRIPCION_ID", nullable = false)
    public CatTipoPrescripcion getCatTipoPrescripcion() {
        return this.catTipoPrescripcion;
    }

    public void setCatTipoPrescripcion(CatTipoPrescripcion catTipoPrescripcion) {
        this.catTipoPrescripcion = catTipoPrescripcion;
    }

//	@Column(name = "EVENTO_ID", length = 10)
//	public Integer getEventoId() {
//		return eventoId;
//	}
//
//	public void setEventoId(Integer eventoId) {
//		this.eventoId = eventoId;
//	}
}
