package hts.backend.entity;


import hts.backend.entity.CatTipoPrescripcion;
import hts.backend.entity.GusModulos;
import hts.backend.entity.PacEvento;
import hts.backend.entity.AdmPersonalCedula;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * CexReceta generated by hbm2java
 */
@Entity
@Table(name = "cex_receta")
public class CexReceta implements java.io.Serializable {

    private Integer recetaId;
    //	private CatTipoPrescripcion catTipoPrescripcion;
//	private CatMotInterrupcionPresc catMotInterrupcionPresc;
    private GusModulos gusModulos;
    //	private CatEstadoPrescripcion catEstadoPrescripcion;
    private Integer eventoId;
    private String noReceta;
    private Integer estatus;
    private String usuarioRegistro;
    private Date fechaRegistro;
    //	private Date fechaInterrupcion;
//	private String usuarioInterrupcion;
    private AdmPersonalCedula admPersonalCedula;
    private Set<CexPrescripcionesMedicamento> cexPrescripcionesMedicamentos = new HashSet<CexPrescripcionesMedicamento>(0);

    public CexReceta() {
    }

    public CexReceta(Integer recetaId, CatTipoPrescripcion catTipoPrescripcion,  GusModulos gusModulos,
                     Integer eventoId, String noReceta, Integer estatus, String usuarioRegistro, Date fechaRegistro,  AdmPersonalCedula admPersonalCedula) { //CatMotInterrupcionPresc catMotInterrupcionPresc,CatEstadoPrescripcion catEstadoPrescripcion,
        this.recetaId = recetaId;
        //	this.catTipoPrescripcion = catTipoPrescripcion;
        //	this.catMotInterrupcionPresc = catMotInterrupcionPresc;
        this.gusModulos = gusModulos;
        //	this.catEstadoPrescripcion = catEstadoPrescripcion;
        this.eventoId = eventoId;
        this.noReceta = noReceta;
        this.estatus = estatus;
        this.usuarioRegistro = usuarioRegistro;
        this.fechaRegistro = fechaRegistro;
        this.admPersonalCedula = admPersonalCedula;
    }

    public CexReceta(Integer recetaId, GusModulos gusModulos
            , Integer eventoId, String noReceta, Integer estatus, String usuarioRegistro, Date fechaRegistro,
                     Set<CexPrescripcionesMedicamento> cexPrescripcionesMedicamentos,  AdmPersonalCedula admPersonalCedula) { //CatMotInterrupcionPresc catMotInterrupcionPresc,, String usuarioInterrupcion, Date fechaInterrupcion , CatEstadoPrescripcion catEstadoPrescripcion,
        this.recetaId = recetaId;
//		this.catTipoPrescripcion = catTipoPrescripcion;
//		this.catMotInterrupcionPresc = catMotInterrupcionPresc;
        this.gusModulos = gusModulos;
//		this.catEstadoPrescripcion = catEstadoPrescripcion;
        this.eventoId = eventoId;
        this.noReceta = noReceta;
        this.estatus = estatus;
        this.usuarioRegistro = usuarioRegistro;
        this.fechaRegistro = fechaRegistro;
        this.cexPrescripcionesMedicamentos = cexPrescripcionesMedicamentos;
        this.admPersonalCedula = admPersonalCedula;
//		this.usuarioInterrupcion = usuarioInterrupcion;
//		this.fechaInterrupcion = fechaInterrupcion;

    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "RECETA_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public Integer getRecetaId() {
        return this.recetaId;
    }

    public void setRecetaId(Integer recetaId) {
        this.recetaId = recetaId;
    }

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "TIPO_PRESCRIPCION_ID", nullable = false)
//	public CatTipoPrescripcion getCatTipoPrescripcion() {
//		return this.catTipoPrescripcion;
//	}
//
//	public void setCatTipoPrescripcion(CatTipoPrescripcion catTipoPrescripcion) {
//		this.catTipoPrescripcion = catTipoPrescripcion;
//	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "MOTIVO_INTERRUPCION_PRESC_ID")
//	public CatMotInterrupcionPresc getCatMotInterrupcionPresc() {
//		return this.catMotInterrupcionPresc;
//	}
//
//	public void setCatMotInterrupcionPresc(CatMotInterrupcionPresc catMotInterrupcionPresc) {
//		this.catMotInterrupcionPresc = catMotInterrupcionPresc;
//	}

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GUS_MODULO_ID", nullable = false)
    public GusModulos getGusModulos() {
        return this.gusModulos;
    }

    public void setGusModulos(GusModulos gusModulos) {
        this.gusModulos = gusModulos;
    }

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "ESTADO_PRESCRIPCION_ID", nullable = false)
//	public CatEstadoPrescripcion getCatEstadoPrescripcion() {
//		return this.catEstadoPrescripcion;
//	}
//
//	public void setCatEstadoPrescripcion(CatEstadoPrescripcion catEstadoPrescripcion) {
//		this.catEstadoPrescripcion = catEstadoPrescripcion;
//	}

    @Column(name = "NO_RECETA", nullable = false, length = 20)
    public String getNoReceta() {
        return this.noReceta;
    }

    public void setNoReceta(String noReceta) {
        this.noReceta = noReceta;
    }

    @Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
    public Integer getEstatus() {
        return this.estatus;
    }

    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }

    @Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
    public String getUsuarioRegistro() {
        return this.usuarioRegistro;
    }

    public void setUsuarioRegistro(String usuarioRegistro) {
        this.usuarioRegistro = usuarioRegistro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

//	@Temporal(TemporalType.DATE)
//	@Column(name = "FECHA_INTERRUPCION", length = 7)
//	public Date getFechaInterrupcion() {
//		return this.fechaInterrupcion;
//	}
//
//	public void setFechaInterrupcion(Date fechaInterrupcion) {
//		this.fechaInterrupcion = fechaInterrupcion;
//	}
//
//	@Column(name = "USUARIO_INTERRUPCION", length = 20)
//	public String getUsuarioInterrupcion() {
//		return this.usuarioInterrupcion;
//	}
//
//	public void setUsuarioInterrupcion(String usuarioInterrupcion) {
//		this.usuarioInterrupcion = usuarioInterrupcion;
//	}

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cexReceta")
    public Set<CexPrescripcionesMedicamento> getCexPrescripcionesMedicamentos() {
        return this.cexPrescripcionesMedicamentos;
    }

    public void setCexPrescripcionesMedicamentos(Set<CexPrescripcionesMedicamento> cexPrescripcionesMedicamentos) {
        this.cexPrescripcionesMedicamentos = cexPrescripcionesMedicamentos;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ADM_PROF_SALUD_CEDULA_ID", nullable = false)
    public AdmPersonalCedula getAdmPersonalCedula() {
        return this.admPersonalCedula;
    }

    public void setAdmPersonalCedula(AdmPersonalCedula admPersonalCedula) {
        this.admPersonalCedula = admPersonalCedula;
    }


    @Column(name = "EVENTO_ID", nullable = false)
    public Integer getEventoId() {
        return this.eventoId;
    }

    public void setEventoId(Integer eventoId) {
        this.eventoId = eventoId;
    }
}
