package hts.backend.entity;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * CorePauta generated by hbm2java
 */
@Entity
@Table(name = "core_pauta")
public class CorePauta implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private int pautaId;
    private CatTipoPauta catTipoPauta;
    private String cve;
    private String descripcion;
    private Integer cadaHoras;
    private Integer hospitalId;
    private AdmHospital admHospital;
    private int estatus;
    private Date fechaRegistro;
    private String usuarioRegistro;
    private Set<CorePautaToma> corePautaTomas = new HashSet<CorePautaToma>(0);
    private Set<CorePautaPrescripcion> corePautaPrescripcions = new HashSet<CorePautaPrescripcion>(0);
    private Set<CorePautaDias> corePautaDias = new HashSet<CorePautaDias>(0);
    private Set<CexMedicamentosMateriales> cexMedicamentosMaterialeses = new HashSet<CexMedicamentosMateriales>(0);
    private Set<CexPrescripcionesMedicamento> cexPrescripcionesMedicamentos = new HashSet<CexPrescripcionesMedicamento>(0);

    public CorePauta() {
    }


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "PAUTA_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public int getPautaId() {
        return this.pautaId;
    }

    public void setPautaId(int pautaId) {
        this.pautaId = pautaId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TIPO_PAUTA_ID", nullable = false)
    public CatTipoPauta getCatTipoPauta() {
        return this.catTipoPauta;
    }

    public void setCatTipoPauta(CatTipoPauta catTipoPauta) {
        this.catTipoPauta = catTipoPauta;
    }


    @Column(name = "HOSPITAL_ID", nullable = false)
    public Integer getHospitalId() {
        return hospitalId;
    }

    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    @ManyToOne
    @JoinColumn(name = "HOSPITAL_ID", updatable = false, insertable = false)
    public AdmHospital getAdmHospital() {
        return admHospital;
    }

    public void setAdmHospital(AdmHospital admHospital) {
        this.admHospital = admHospital;
    }

    @Column(name = "CVE", nullable = false, length = 20)
    public String getCve() {
        return this.cve;
    }

    public void setCve(String cve) {
        this.cve = cve;
    }

    @Column(name = "DESCRIPCION", nullable = false, length = 20)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }


    //@Temporal(TemporalType.TIME)
    @Column(name = "CADA_HORAS")
    public Integer getCadaHoras() {
        return cadaHoras;
    }

    public void setCadaHoras(Integer cadaHoras) {
        this.cadaHoras = cadaHoras;
    }

    @Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
    public int getEstatus() {
        return this.estatus;
    }

    public void setEstatus(int estatus) {
        this.estatus = estatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_REGISTRO", nullable = false, length = 20)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }


    @Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
    public String getUsuarioRegistro() {
        return usuarioRegistro;
    }

    public void setUsuarioRegistro(String usuarioRegistro) {
        this.usuarioRegistro = usuarioRegistro;
    }


    @OneToMany(fetch = FetchType.LAZY, mappedBy = "corePauta")
    public Set<CorePautaToma> getCorePautaTomas() {
        return corePautaTomas;
    }

    public void setCorePautaTomas(Set<CorePautaToma> corePautaTomas) {
        this.corePautaTomas = corePautaTomas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "corePauta")

    public Set<CorePautaPrescripcion> getCorePautaPrescripcions() {
        return corePautaPrescripcions;
    }

    public void setCorePautaPrescripcions(Set<CorePautaPrescripcion> corePautaPrescripcions) {
        this.corePautaPrescripcions = corePautaPrescripcions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "corePauta")
    public Set<CorePautaDias> getCorePautaDias() {
        return corePautaDias;
    }

    public void setCorePautaDias(Set<CorePautaDias> corePautaDias) {
        this.corePautaDias = corePautaDias;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "corePauta")
    public Set<CexMedicamentosMateriales> getCexMedicamentosMaterialeses() {
        return cexMedicamentosMaterialeses;
    }

    public void setCexMedicamentosMaterialeses(Set<CexMedicamentosMateriales> cexMedicamentosMaterialeses) {
        this.cexMedicamentosMaterialeses = cexMedicamentosMaterialeses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "corePauta")
    public Set<CexPrescripcionesMedicamento> getCexPrescripcionesMedicamentos() {
        return this.cexPrescripcionesMedicamentos;
    }

    public void setCexPrescripcionesMedicamentos(Set<CexPrescripcionesMedicamento> cexPrescripcionesMedicamentos) {
        this.cexPrescripcionesMedicamentos = cexPrescripcionesMedicamentos;
    }


}
