package hts.backend.entity;



import javax.persistence.*;
import java.util.Date;

/**
 * CorePautaToma generated by hbm2java
 */
@Entity
@Table(name = "core_pauta_toma")
public class CorePautaToma implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private int pautaTomaId;
    private CorePauta corePauta;
    private int numeroToma;
    private Date horaToma;
    private Date fechaRegistro;
    private String usuarioRegistrro;

    public CorePautaToma() {
    }

    public CorePautaToma(int pautaTomaId, CorePauta corePauta, int numeroToma, Date horaToma,
                         Date fechaRegistro, String usuarioRegistrro) {
        this.pautaTomaId = pautaTomaId;
        this.corePauta = corePauta;
        this.numeroToma = numeroToma;
        this.horaToma = horaToma;
        this.fechaRegistro = fechaRegistro;
        this.usuarioRegistrro = usuarioRegistrro;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "PAUTA_TOMA_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public int getPautaTomaId() {
        return this.pautaTomaId;
    }

    public void setPautaTomaId(int pautaTomaId) {
        this.pautaTomaId = pautaTomaId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PAUTA_ID", nullable = false)
    public CorePauta getCorePauta() {
        return this.corePauta;
    }

    public void setCorePauta(CorePauta corePauta) {
        this.corePauta = corePauta;
    }

    @Column(name = "NUMERO_TOMA", nullable = false, precision = 22, scale = 0)
    public int getNumeroToma() {
        return this.numeroToma;
    }

    public void setNumeroToma(int numeroToma) {
        this.numeroToma = numeroToma;
    }


    @Column(name = "HORA_TOMA", nullable = false, length = 7)
    public Date getHoraToma() {
        return this.horaToma;
    }

    public void setHoraToma(Date horaToma) {
        this.horaToma = horaToma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
    public String getUsuarioRegistrro() {
        return this.usuarioRegistrro;
    }

    public void setUsuarioRegistrro(String usuarioRegistrro) {
        this.usuarioRegistrro = usuarioRegistrro;
    }

}
