package hts.backend.entity;


// Generated 24/02/2017 07:59:12 PM by Hibernate Tools 5.2.0.CR1


import org.springframework.security.core.context.SecurityContextHolder;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Correo generated by hbm2java
 */
@Entity
@Table(name = "correo")
public class Correo implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer correoId;
	private String correo;
	private Integer status;
	private String cve;
	private String usuarioCve;
	private Date fechaRegistro;
	private Set<AgenteCorreo> agenteCorreos = new HashSet<AgenteCorreo>(0);

	public Correo() {
	}

	public Correo(Integer correoId, String correo, Integer status, String usuarioCve, Date fechaRegistro) {
		this.correoId = correoId;
		this.correo = correo;
		this.status = status;
		this.usuarioCve = usuarioCve;
		this.fechaRegistro = fechaRegistro;
	}

	public Correo(Integer correoId, String correo, Integer status, String cve, String usuarioCve, Date fechaRegistro, Set<AgenteCorreo> agenteCorreos) {
		this.correoId = correoId;
		this.correo = correo;
		this.status = status;
		this.cve = cve;
		this.usuarioCve = usuarioCve;
		this.fechaRegistro = fechaRegistro;
		this.agenteCorreos = agenteCorreos;
	}

	// Constructor corto para registro de correos
	public Correo(String correo) {
		this.setCorreo(correo);
		this.setStatus(1);
		this.setCve(null);
		this.setUsuarioCve(SecurityContextHolder.getContext().getAuthentication().getName());
		this.setFechaRegistro(new Date());
	}


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CORREO_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getCorreoId() {
		return this.correoId;
	}

	public void setCorreoId(Integer correoId) {
		this.correoId = correoId;
	}

	@Column(name = "CORREO", nullable = false, length = 70)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "CVE", length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioCve() {
		return this.usuarioCve;
	}

	public void setUsuarioCve(String usuarioCve) {
		this.usuarioCve = usuarioCve;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "correo")
	public Set<AgenteCorreo> getAgenteCorreos() {
		return this.agenteCorreos;
	}

	public void setAgenteCorreos(Set<AgenteCorreo> agenteCorreos) {
		this.agenteCorreos = agenteCorreos;
	}

}
