package hts.backend.entity;
// Generated 1/02/2017 11:13:06 AM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HospitalPerfilId generated by hbm2java
 */
@Embeddable
@Deprecated
public class HospitalPerfilId implements java.io.Serializable {

	private Integer hospitalId;
	private Integer perfilId;

	public HospitalPerfilId() {
	}

	public HospitalPerfilId(Integer hospitalId,Integer perfilId) {
		this.hospitalId = hospitalId;
		this.perfilId = perfilId;
	}

	@Column(name = "HOSPITAL_ID", nullable = false, precision = 22, scale = 0)
	public Integer getHospitalId() {
		return this.hospitalId;
	}

	public void setHospitalId(Integer hospitalId) {
		this.hospitalId = hospitalId;
	}

	@Column(name = "PERFIL_ID", nullable = false, precision = 22, scale = 0)
	public Integer getPerfilId() {
		return this.perfilId;
	}

	public void setPerfilId(Integer perfilId) {
		this.perfilId = perfilId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HospitalPerfilId))
			return false;
		HospitalPerfilId castOther = (HospitalPerfilId) other;

		return ((this.getHospitalId() == castOther.getHospitalId()) || (this.getHospitalId() != null
				&& castOther.getHospitalId() != null && this.getHospitalId().equals(castOther.getHospitalId())))
				&& ((this.getPerfilId() == castOther.getPerfilId()) || (this.getPerfilId() != null
						&& castOther.getPerfilId() != null && this.getPerfilId().equals(castOther.getPerfilId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getHospitalId() == null ? 0 : this.getHospitalId().hashCode());
		result = 37 * result + (getPerfilId() == null ? 0 : this.getPerfilId().hashCode());
		return result;
	}

}
