package hts.backend.entity;
// Generated 1/02/2017 11:13:06 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * HospitalPerfil generated by hbm2java
 */
@Entity
@Deprecated
@Table(name = "hospital_perfil")
public class HospitalPerfil implements java.io.Serializable {

	private HospitalPerfilId id;


	public HospitalPerfil() {
	}

	public HospitalPerfil(HospitalPerfilId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "hospitalId", column = @Column(name = "HOSPITAL_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "perfilId", column = @Column(name = "PERFIL_ID", nullable = false, precision = 22, scale = 0)) })
	public HospitalPerfilId getId() {
		return this.id;
	}

	public void setId(HospitalPerfilId id) {
		this.id = id;
	}

}
