package hts.backend.entity;

// Generated 24/02/2017 07:59:12 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * NomCatLocalidad generated by hbm2java
 */
@Entity
@Table(name = "nom_cat_localidad")
public class NomCatLocalidad implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer catLocalidadId;
	private String cveEnt;
	private String cveMun;
	private String cveLoc;
	private String descripcion;
	private Integer indicaDefault;
	private Integer status;
	private String usuarioCve;
	private Date fechaRegistro;
	private Set<Direccion> direccions = new HashSet<Direccion>(0);

	public NomCatLocalidad() {
	}
	public NomCatLocalidad(Integer catLocalidadId) {
		this.catLocalidadId = catLocalidadId;
	}

	public NomCatLocalidad(Integer catLocalidadId, String cveEnt, String cveMun, String cveLoc, String descripcion,
			Integer indicaDefault, Integer status, String usuarioCve, Date fechaRegistro) {
		this.catLocalidadId = catLocalidadId;
		this.cveEnt = cveEnt;
		this.cveMun = cveMun;
		this.cveLoc = cveLoc;
		this.descripcion = descripcion;
		this.indicaDefault = indicaDefault;
		this.status = status;
		this.usuarioCve = usuarioCve;
		this.fechaRegistro = fechaRegistro;
	}

	public NomCatLocalidad(Integer catLocalidadId, String cveEnt, String cveMun, String cveLoc, String descripcion,
			Integer indicaDefault, Integer status, String usuarioCve, Date fechaRegistro,
			Set<Direccion> direccions) {
		this.catLocalidadId = catLocalidadId;
		this.cveEnt = cveEnt;
		this.cveMun = cveMun;
		this.cveLoc = cveLoc;
		this.descripcion = descripcion;
		this.indicaDefault = indicaDefault;
		this.status = status;
		this.usuarioCve = usuarioCve;
		this.fechaRegistro = fechaRegistro;
		this.direccions = direccions;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CAT_LOCALIDAD_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getCatLocalidadId() {
		return this.catLocalidadId;
	}

	public void setCatLocalidadId(Integer catLocalidadId) {
		this.catLocalidadId = catLocalidadId;
	}

	@Column(name = "CVE_ENT", nullable = false, length = 2)
	public String getCveEnt() {
		return this.cveEnt;
	}

	public void setCveEnt(String cveEnt) {
		this.cveEnt = cveEnt;
	}

	@Column(name = "CVE_MUN", nullable = false, length = 3)
	public String getCveMun() {
		return this.cveMun;
	}

	public void setCveMun(String cveMun) {
		this.cveMun = cveMun;
	}

	@Column(name = "CVE_LOC", nullable = false, length = 4)
	public String getCveLoc() {
		return this.cveLoc;
	}

	public void setCveLoc(String cveLoc) {
		this.cveLoc = cveLoc;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, precision = 22, scale = 0)
	public Integer getIndicaDefault() {
		return this.indicaDefault;
	}

	public void setIndicaDefault(Integer indicaDefault) {
		this.indicaDefault = indicaDefault;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioCve() {
		return this.usuarioCve;
	}

	public void setUsuarioCve(String usuarioCve) {
		this.usuarioCve = usuarioCve;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nomCatLocalidad")
	public Set<Direccion> getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set<Direccion> direccions) {
		this.direccions = direccions;
	}

}
