package hts.backend.entity;
// Generated 4/05/2017 11:05:26 AM by Hibernate Tools 5.2.0.Beta1

import hts.backend.entity.CexMotivoAnulacion;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * NomCatMotivoAnulaCita generated by hbm2java
 */
@Entity
@Table(name = "nom_cat_motivo_anula_cita")
public class NomCatMotivoAnulaCita implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int motivoAnulaId;
	private String cve;
	private String nombre;
	private String descripcion;
	private Integer indicaDefault;
	private Integer status;
	private String usuarioRegistra;
	private Date fechaRegistro;
	private Integer idiomaAppId;
	private Set<CexMotivoAnulacion> cexMotivoAnulacions = new HashSet<CexMotivoAnulacion>(0);

	public NomCatMotivoAnulaCita() {
	}

	public NomCatMotivoAnulaCita(int motivoAnulaId, String cve, String nombre, Integer indicaDefault,
			Integer status, String usuarioRegistra, Date fechaRegistro) {
		this.motivoAnulaId = motivoAnulaId;
		this.cve = cve;
		this.nombre = nombre;
		this.indicaDefault = indicaDefault;
		this.status = status;
		this.usuarioRegistra = usuarioRegistra;
		this.fechaRegistro = fechaRegistro;
	}

	public NomCatMotivoAnulaCita(int motivoAnulaId, String cve, String nombre, String descripcion,
			Integer indicaDefault, Integer status, String usuarioRegistra, Date fechaRegistro, Integer idiomaAppId,
								 Set<CexMotivoAnulacion> cexMotivoAnulacions) {
		this.motivoAnulaId = motivoAnulaId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.indicaDefault = indicaDefault;
		this.status = status;
		this.usuarioRegistra = usuarioRegistra;
		this.fechaRegistro = fechaRegistro;
		this.idiomaAppId = idiomaAppId;
		this.cexMotivoAnulacions = cexMotivoAnulacions;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MOTIVO_ANULA_CITA_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getMotivoAnulaId() {
		return this.motivoAnulaId;
	}

	public void setMotivoAnulaId(int motivoAnulaId) {
		this.motivoAnulaId = motivoAnulaId;
	}

	@Column(name = "CVE", nullable = false, length = 10)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 40)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, scale = 0)
	public Integer isIndicaDefault() {
		return this.indicaDefault;
	}

	public void setIndicaDefault(Integer indicaDefault) {
		this.indicaDefault = indicaDefault;
	}

	@Column(name = "ESTATUS", nullable = false, scale = 0)
	public Integer isStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "IDIOMA_APP_ID", precision = 22, scale = 0)
	public Integer getIdiomaAppId() {
		return this.idiomaAppId;
	}

	public void setIdiomaAppId(Integer idiomaAppId) {
		this.idiomaAppId = idiomaAppId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nomCatMotivoAnulaCita")
	public Set<CexMotivoAnulacion> getCexMotivoAnulacions() {
		return this.cexMotivoAnulacions;
	}

	public void setCexMotivoAnulacions(Set<CexMotivoAnulacion> cexMotivoAnulacions) {
		this.cexMotivoAnulacions = cexMotivoAnulacions;
	}


}
