package hts.backend.entity;



import hts.backend.entity.*;

import javax.persistence.*;
import java.util.Date;
import java.util.Set;


/**
 * NomCatParentesco generated by hbm2java
 */
@Entity
@Table(name = "nom_cat_metodo_pago")
public class NomCatMetodoPago implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer metodoPagoId;
	private String cve;
	private String nombre;
	private String descripcion;
	private Integer valorDefault;
	private Integer estatus;
	private Date fechaRegistro;
	private String usuarioRegistra;
	private Integer idiomaAppId;
	private Set<FacAbonosAsegComercial> facAbonosAsegComercialsByMetodoPagoId;
	private Set<FacAbonosAsegParticular> facAbonosAsegParticularsByMetodoPagoId;
	private Set<FacBitAbonosAsegComercial> facBitAbonosAsegComercialsByMetodoPagoId;
	private Set<FacBitAbonosAsegParticular> facBitAbonosAsegParticularsByMetodoPagoId;
	private Set<FacFormasPagoAsegPart> facFormasPagoAsegPartsByMetodoPagoId;


	private Set<FacturacionFormasPago> facturacionFormasPagosByMetodoPagoId;


	public NomCatMetodoPago() {
	}

	public NomCatMetodoPago(Integer metodoPagoId) {
		this.metodoPagoId=metodoPagoId;
	}


	public NomCatMetodoPago(Integer metodoPagoId, String cve, String nombre, String descripcion,
							Integer valorDefault, Integer estatus, Date fechaRegistro, String usuarioRegistra) {
		this.metodoPagoId = metodoPagoId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
	}



	@Id
	@Column(name = "METODO_PAGO_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getMetodoPagoId() {
		return metodoPagoId;
	}

	public void setMetodoPagoId(Integer metodoPagoId) {
		this.metodoPagoId = metodoPagoId;
	}

	@Column(name = "CVE", nullable = false, length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 25)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, precision = 22, scale = 0)
	public Integer getValorDefault() {
		return this.valorDefault;
	}

	public void setValorDefault(Integer valorDefault) {
		this.valorDefault = valorDefault;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}

	@Column(name = "IDIOMA_APP_ID", precision = 22, scale = 0)
	public Integer getIdiomaAppId() {
		return this.idiomaAppId;
	}

	public void setIdiomaAppId(Integer idiomaAppId) {
		this.idiomaAppId = idiomaAppId;
	}

	@OneToMany(mappedBy = "nomCatMetodoPagoByMetodoPagoId")
	public Set<FacturacionFormasPago> getFacturacionFormasPagosByMetodoPagoId() {
		return facturacionFormasPagosByMetodoPagoId;
	}

	public void setFacturacionFormasPagosByMetodoPagoId(Set<FacturacionFormasPago> facturacionFormasPagosByMetodoPagoId) {
		this.facturacionFormasPagosByMetodoPagoId = facturacionFormasPagosByMetodoPagoId;
	}

	@OneToMany(mappedBy = "nomCatMetodoPago") public Set<FacAbonosAsegComercial> getFacAbonosAsegComercialsByMetodoPagoId() {
		return facAbonosAsegComercialsByMetodoPagoId;
	}

	public void setFacAbonosAsegComercialsByMetodoPagoId(Set<FacAbonosAsegComercial> facAbonosAsegComercialsByMetodoPagoId) {
		this.facAbonosAsegComercialsByMetodoPagoId = facAbonosAsegComercialsByMetodoPagoId;
	}

	@OneToMany(mappedBy = "nomCatMetodoPago") public Set<FacAbonosAsegParticular> getFacAbonosAsegParticularsByMetodoPagoId() {
		return facAbonosAsegParticularsByMetodoPagoId;
	}

	public void setFacAbonosAsegParticularsByMetodoPagoId(Set<FacAbonosAsegParticular> facAbonosAsegParticularsByMetodoPagoId) {
		this.facAbonosAsegParticularsByMetodoPagoId = facAbonosAsegParticularsByMetodoPagoId;
	}

	@OneToMany(mappedBy = "nomCatMetodoPagoByMetodoPagoId") public Set<FacBitAbonosAsegComercial> getFacBitAbonosAsegComercialsByMetodoPagoId() {
		return facBitAbonosAsegComercialsByMetodoPagoId;
	}

	public void setFacBitAbonosAsegComercialsByMetodoPagoId(Set<FacBitAbonosAsegComercial> facBitAbonosAsegComercialsByMetodoPagoId) {
		this.facBitAbonosAsegComercialsByMetodoPagoId = facBitAbonosAsegComercialsByMetodoPagoId;
	}

	@OneToMany(mappedBy = "nomCatMetodoPagoByMetodoPagoId") public Set<FacBitAbonosAsegParticular> getFacBitAbonosAsegParticularsByMetodoPagoId() {
		return facBitAbonosAsegParticularsByMetodoPagoId;
	}

	public void setFacBitAbonosAsegParticularsByMetodoPagoId(Set<FacBitAbonosAsegParticular> facBitAbonosAsegParticularsByMetodoPagoId) {
		this.facBitAbonosAsegParticularsByMetodoPagoId = facBitAbonosAsegParticularsByMetodoPagoId;
	}

	@OneToMany(mappedBy = "nomCatMetodoPago") public Set<FacFormasPagoAsegPart> getFacFormasPagoAsegPartsByMetodoPagoId() {
		return facFormasPagoAsegPartsByMetodoPagoId;
	}

	public void setFacFormasPagoAsegPartsByMetodoPagoId(Set<FacFormasPagoAsegPart> facFormasPagoAsegPartsByMetodoPagoId) {
		this.facFormasPagoAsegPartsByMetodoPagoId = facFormasPagoAsegPartsByMetodoPagoId;
	}

}
