package hts.backend.entity;

import hts.backend.entity.*;

import javax.persistence.*;
import java.util.Date;
import java.util.Set;


/**
 * NomCatParentesco generated by hbm2java
 */
@Entity
@Table(name = "nom_cat_banco")
public class NomCatBanco implements java.io.Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer bancoId;
	private String cve;
	private String nombre;
	private String descripcion;
	private Integer valorDefault;
	private Integer estatus;
	private Date fechaRegistro;
	private String usuarioRegistra;
	private Integer idiomaAppId;
	private Set<FacAbonosAsegComercial> facAbonosAsegComercialsByBancoId;
	private Set<FacAbonosAsegParticular> facAbonosAsegParticularsByBancoId;
	private Set<FacBitAbonosAsegComercial> facBitAbonosAsegComercialsByBancoId;
	private Set<FacBitAbonosAsegParticular> facBitAbonosAsegParticularsByBancoId;
	private Set<FacFormasPagoAsegPart> facFormasPagoAsegPartsByBancoId;

	private Set<FacturacionFormasPago> facturacionFormasPagosByBancoId;


	public NomCatBanco() {
	}

	public NomCatBanco(Integer bancoId) {
		this.bancoId=bancoId;
	}


	public NomCatBanco(Integer bancoId, String cve, String nombre, String descripcion,
					   Integer valorDefault, Integer estatus, Date fechaRegistro, String usuarioRegistra) {
		this.bancoId = bancoId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valorDefault = valorDefault;
		this.estatus = estatus;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
	}



	@Id

	@Column(name = "BANCO_ID", unique = true, nullable = false, precision = 22, scale = 0)	public Integer getBancoId() {
		return bancoId;
	}

	public void setBancoId(Integer bancoId) {
		this.bancoId = bancoId;
	}

	@Column(name = "CVE", nullable = false, length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 25)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, precision = 22, scale = 0)
	public Integer getValorDefault() {
		return this.valorDefault;
	}

	public void setValorDefault(Integer valorDefault) {
		this.valorDefault = valorDefault;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}

	@Column(name = "IDIOMA_APP_ID", precision = 22, scale = 0)
	public Integer getIdiomaAppId() {
		return this.idiomaAppId;
	}

	public void setIdiomaAppId(Integer idiomaAppId) {
		this.idiomaAppId = idiomaAppId;
	}

	@OneToMany(mappedBy = "nomCatBancoByBancoId")
	public Set<FacturacionFormasPago> getFacturacionFormasPagosByBancoId() {
		return facturacionFormasPagosByBancoId;
	}

	public void setFacturacionFormasPagosByBancoId(Set<FacturacionFormasPago> facturacionFormasPagosByBancoId) {
		this.facturacionFormasPagosByBancoId = facturacionFormasPagosByBancoId;
	}

	@OneToMany(mappedBy = "nomCatBanco") public Set<FacAbonosAsegComercial> getFacAbonosAsegComercialsByBancoId() {
		return facAbonosAsegComercialsByBancoId;
	}

	public void setFacAbonosAsegComercialsByBancoId(Set<FacAbonosAsegComercial> facAbonosAsegComercialsByBancoId) {
		this.facAbonosAsegComercialsByBancoId = facAbonosAsegComercialsByBancoId;
	}

	@OneToMany(mappedBy = "nomCatBanco") public Set<FacAbonosAsegParticular> getFacAbonosAsegParticularsByBancoId() {
		return facAbonosAsegParticularsByBancoId;
	}

	public void setFacAbonosAsegParticularsByBancoId(Set<FacAbonosAsegParticular> facAbonosAsegParticularsByBancoId) {
		this.facAbonosAsegParticularsByBancoId = facAbonosAsegParticularsByBancoId;
	}

	@OneToMany(mappedBy = "nomCatBancoByBancoId") public Set<FacBitAbonosAsegComercial> getFacBitAbonosAsegComercialsByBancoId() {
		return facBitAbonosAsegComercialsByBancoId;
	}

	public void setFacBitAbonosAsegComercialsByBancoId(Set<FacBitAbonosAsegComercial> facBitAbonosAsegComercialsByBancoId) {
		this.facBitAbonosAsegComercialsByBancoId = facBitAbonosAsegComercialsByBancoId;
	}

	@OneToMany(mappedBy = "nomCatBancoByBancoId") public Set<FacBitAbonosAsegParticular> getFacBitAbonosAsegParticularsByBancoId() {
		return facBitAbonosAsegParticularsByBancoId;
	}

	public void setFacBitAbonosAsegParticularsByBancoId(Set<FacBitAbonosAsegParticular> facBitAbonosAsegParticularsByBancoId) {
		this.facBitAbonosAsegParticularsByBancoId = facBitAbonosAsegParticularsByBancoId;
	}

	@OneToMany(mappedBy = "nomCatBanco") public Set<FacFormasPagoAsegPart> getFacFormasPagoAsegPartsByBancoId() {
		return facFormasPagoAsegPartsByBancoId;
	}

	public void setFacFormasPagoAsegPartsByBancoId(Set<FacFormasPagoAsegPart> facFormasPagoAsegPartsByBancoId) {
		this.facFormasPagoAsegPartsByBancoId = facFormasPagoAsegPartsByBancoId;
	}


}
