package hts.backend.entity;
// Generated 4/05/2017 11:05:26 AM by Hibernate Tools 5.2.0.Beta1

import hts.backend.entity.CexMotivoReprogramacion;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * NomCatMotivoReprogrCita generated by hbm2java
 */
@Entity
@Table(name = "nom_cat_motivo_reprogr_cita")
public class 	NomCatMotivoReprogrCita implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int motivoReprogrId;
	private String cve;
	private String nombre;
	private String descripcion;
	private Integer indicaDefault;
	private Integer status;
	private String usuarioRegistra;
	private Date fechaRegistro;
	private Integer idiomaAppId;
	private Set<CexMotivoReprogramacion> cexMotivoReprogramacions = new HashSet<CexMotivoReprogramacion>(0);

	public NomCatMotivoReprogrCita() {
	}

	public NomCatMotivoReprogrCita(int motivoReprogrId, String cve, String nombre, Integer indicaDefault,
								   Integer status, String usuarioRegistra, Date fechaRegistro) {
		this.motivoReprogrId = motivoReprogrId;
		this.cve = cve;
		this.nombre = nombre;
		this.indicaDefault = indicaDefault;
		this.status = status;
		this.usuarioRegistra = usuarioRegistra;
		this.fechaRegistro = fechaRegistro;
	}

	public NomCatMotivoReprogrCita(int motivoReprogrId, String cve, String nombre, String descripcion,
								   Integer indicaDefault, Integer status, String usuarioRegistra, Date fechaRegistro, Integer idiomaAppId,
			  Set<CexMotivoReprogramacion> cexMotivoReprogramacions) {
		this.motivoReprogrId = motivoReprogrId;
		this.cve = cve;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.indicaDefault = indicaDefault;
		this.status = status;
		this.usuarioRegistra = usuarioRegistra;
		this.fechaRegistro = fechaRegistro;
		this.idiomaAppId = idiomaAppId;
		this.cexMotivoReprogramacions = cexMotivoReprogramacions;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "MOTIVO_REPROGR_CITA_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getMotivoReprogrId() {
		return this.motivoReprogrId;
	}

	public void setMotivoReprogrId(int motivoReprogrId) {
		this.motivoReprogrId = motivoReprogrId;
	}

	@Column(name = "CVE", nullable = false, length = 10)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 40)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, scale = 0)
	public Integer isIndicaDefault() {
		return this.indicaDefault;
	}

	public void setIndicaDefault(Integer indicaDefault) {
		this.indicaDefault = indicaDefault;
	}

	@Column(name = "ESTATUS", nullable = false, scale = 0)
	public Integer isStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "IDIOMA_APP_ID", precision = 22, scale = 0)
	public Integer getIdiomaAppId() {
		return this.idiomaAppId;
	}

	public void setIdiomaAppId(Integer idiomaAppId) {
		this.idiomaAppId = idiomaAppId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nomCatMotivoReprogrCita")
	public Set<CexMotivoReprogramacion> getCexMotivoReprogramacions() {
		return this.cexMotivoReprogramacions;
	}

	public void setCexMotivoReprogramacions(Set<CexMotivoReprogramacion> cexMotivoReprogramacions) {
		this.cexMotivoReprogramacions = cexMotivoReprogramacions;
	}
}
