package hts.backend.entity;
// Generated 15/03/2017 05:15:39 PM by Hibernate Tools 5.2.0.CR1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NomCatSino generated by hbm2java
 */
@Entity
@Table(name = "nom_cat_sino")
public class NomCatSino implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer sinoId;
	private String cve;
	private String nombre;
	private Integer guiaId;
	private Integer idiomaAppId;
//	private PacPaciente seConsideraIndigena;
//	private PacPaciente hablaIndigena;
//	private PacPaciente hablaEspanol;
//	private PacPaciente trabajaActualmente;
//	private Set<PacPaciente> pacPacientes = new HashSet<PacPaciente>(0);
	private Set<PacPaciente> pacPacientesSeConsideraIndigena= new HashSet<PacPaciente>(0);
	private Set<PacPaciente> pacPacientesHablaIndigena= new HashSet<PacPaciente>(0);
	private Set<PacPaciente> pacPacientesHablaEspanol= new HashSet<PacPaciente>(0);
	private Set<PacPaciente> pacPacientesTrabajaActualmente= new HashSet<PacPaciente>(0);


	public NomCatSino() {

	}

	public NomCatSino(Integer sinoId) {
		this.sinoId = sinoId;
	}

	public NomCatSino(Integer sinoId, String cve, String nombre) {
		this.sinoId = sinoId;
		this.cve = cve;
		this.nombre = nombre;
	}

	public NomCatSino(Integer sinoId, String cve, String nombre, Integer guiaId, Integer idiomaAppId) {
		this.sinoId = sinoId;
		this.cve = cve;
		this.nombre = nombre;
		this.guiaId = guiaId;
		this.idiomaAppId = idiomaAppId;
	}

	@Id

	@Column(name = "SINO_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getSinoId() {
		return this.sinoId;
	}

	public void setSinoId(Integer sinoId) {
		this.sinoId = sinoId;
	}

	@Column(name = "CVE", nullable = false, length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "GUIA_ID", precision = 22, scale = 0)
	public Integer getGuiaId() {
		return this.guiaId;
	}

	public void setGuiaId(Integer guiaId) {
		this.guiaId = guiaId;
	}

	@Column(name = "IDIOMA_APP_ID", precision = 22, scale = 0)
	public Integer getIdiomaAppId() {
		return this.idiomaAppId;
	}

	public void setIdiomaAppId(Integer idiomaAppId) {
		this.idiomaAppId = idiomaAppId;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "indigena")
	public Set<PacPaciente> getPacPacientesSeConsideraIndigena() {
		return pacPacientesSeConsideraIndigena;
	}

	public void setPacPacientesSeConsideraIndigena(Set<PacPaciente> pacPacientesSeConsideraIndigena) {
		this.pacPacientesSeConsideraIndigena = pacPacientesSeConsideraIndigena;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hablaIndigena")
	public Set<PacPaciente> getPacPacientesHablaIndigena() {
		return pacPacientesHablaIndigena;
	}

	public void setPacPacientesHablaIndigena(Set<PacPaciente> pacPacientesHablaIndigena) {
		this.pacPacientesHablaIndigena = pacPacientesHablaIndigena;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hablaEspanol")
	public Set<PacPaciente> getPacPacientesHablaEspanol() {
		return pacPacientesHablaEspanol;
	}

	public void setPacPacientesHablaEspanol(Set<PacPaciente> pacPacientesHablaEspanol) {
		this.pacPacientesHablaEspanol = pacPacientesHablaEspanol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trabajaActualmente")
	public Set<PacPaciente> getPacPacientesTrabajaActualmente() {
		return pacPacientesTrabajaActualmente;
	}

	public void setPacPacientesTrabajaActualmente(Set<PacPaciente> pacPacientesTrabajaActualmente) {
		this.pacPacientesTrabajaActualmente = pacPacientesTrabajaActualmente;
	}



}
