package hts.backend.entity;
// Generated 24/02/2017 07:59:12 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * NomCatMunicipio generated by hbm2java
 */
@Entity
@Table(name = "nom_cat_municipio")
public class NomCatMunicipio implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer catMunicipioId;
	private String cveEnt;
	private String cveMun;
	private String descripcion;
	private Integer indicaDefault;
	private Integer status;
	private String usuarioCve;
	private Date fechaRegistro;
	private Set<Direccion> direccions = new HashSet<Direccion>(0);
	private Set<PacPaciente> pacPacientes = new HashSet<PacPaciente>(0);

	public NomCatMunicipio() {
	}

	public NomCatMunicipio(Integer catMunicipioId) {
		this.catMunicipioId = catMunicipioId;
	}

	public NomCatMunicipio(Integer catMunicipioId, String cveEnt, String cveMun, String descripcion,
			Integer indicaDefault, Integer status, String usuarioCve, Date fechaRegistro) {
		this.catMunicipioId = catMunicipioId;
		this.cveEnt = cveEnt;
		this.cveMun = cveMun;
		this.descripcion = descripcion;
		this.indicaDefault = indicaDefault;
		this.status = status;
		this.usuarioCve = usuarioCve;
		this.fechaRegistro = fechaRegistro;
	}

	public NomCatMunicipio(Integer catMunicipioId, String cveEnt, String cveMun, String descripcion,
			Integer indicaDefault, Integer status, String usuarioCve, Date fechaRegistro, Set<Direccion> direccions) {
		this.catMunicipioId = catMunicipioId;
		this.cveEnt = cveEnt;
		this.cveMun = cveMun;
		this.descripcion = descripcion;
		this.indicaDefault = indicaDefault;
		this.status = status;
		this.usuarioCve = usuarioCve;
		this.fechaRegistro = fechaRegistro;
		this.direccions = direccions;
	}

	public NomCatMunicipio(Integer catMunicipioId, String cveEnt, String cveMun, String descripcion,
			Integer indicaDefault, Integer status, String usuarioCve, Date fechaRegistro, Set<Direccion> direccions,
			Set<PacPaciente> pacPacientes) {
		this.catMunicipioId = catMunicipioId;
		this.cveEnt = cveEnt;
		this.cveMun = cveMun;
		this.descripcion = descripcion;
		this.indicaDefault = indicaDefault;
		this.status = status;
		this.usuarioCve = usuarioCve;
		this.fechaRegistro = fechaRegistro;
		this.direccions = direccions;
		this.pacPacientes = pacPacientes;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CAT_MUNICIPIO_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getCatMunicipioId() {
		return this.catMunicipioId;
	}

	public void setCatMunicipioId(Integer catMunicipioId) {
		this.catMunicipioId = catMunicipioId;
	}

	@Column(name = "CVE_ENT", nullable = false, length = 2)
	public String getCveEnt() {
		return this.cveEnt;
	}

	public void setCveEnt(String cveEnt) {
		this.cveEnt = cveEnt;
	}

	@Column(name = "CVE_MUN", nullable = false, length = 3)
	public String getCveMun() {
		return this.cveMun;
	}

	public void setCveMun(String cveMun) {
		this.cveMun = cveMun;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 80)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, precision = 1, scale = 0)
	public Integer getIndicaDefault() {
		return indicaDefault;
	}

	public void setIndicaDefault(Integer indicaDefault) {
		this.indicaDefault = indicaDefault;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 1, scale = 0)
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioCve() {
		return this.usuarioCve;
	}

	public void setUsuarioCve(String usuarioCve) {
		this.usuarioCve = usuarioCve;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nomCatMunicipio")
	public Set<Direccion> getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set<Direccion> direccions) {
		this.direccions = direccions;
	}

	// @OneToOne(mappedBy="nomCatMunicipio")
	// public PacPaciente getPacPaciente() {
	// return pacPaciente;
	// }
	// public void setPacPaciente(PacPaciente pacPaciente) {
	// this.pacPaciente = pacPaciente;
	// }

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nomCatMunicipio")
	public Set<PacPaciente> getPacPacientes() {
		return pacPacientes;
	}

	public void setPacPacientes(Set<PacPaciente> pacPacientes) {
		this.pacPacientes = pacPacientes;
	}
}
