package hts.backend.entity;
// Generated 15/03/2017 05:21:05 PM by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * NomCatTipoLenguaIndigena generated by hbm2java
 */
@Entity
@Table(name = "nom_cat_tipo_lengua_indigena")
public class NomCatTipoLenguaIndigena implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer tipoLenguaIndigenaId;
	private String cve;
	private String nombre;
	private Integer guiaId;
	private Integer idiomaAppId;

	private Set<PacPaciente> pacPacientes = new HashSet<PacPaciente>(0);

	public NomCatTipoLenguaIndigena() {

	}


	public NomCatTipoLenguaIndigena(Integer tipoLenguaIndigenaId) {
		this.tipoLenguaIndigenaId = tipoLenguaIndigenaId;
	}

	public NomCatTipoLenguaIndigena(Integer tipoLenguaIndigenaId, String cve, String nombre) {
		this.tipoLenguaIndigenaId = tipoLenguaIndigenaId;
		this.cve = cve;
		this.nombre = nombre;
	}

	public NomCatTipoLenguaIndigena(Integer tipoLenguaIndigenaId, String cve, String nombre, Integer guiaId,
			Integer idiomaAppId) {
		this.tipoLenguaIndigenaId = tipoLenguaIndigenaId;
		this.cve = cve;
		this.nombre = nombre;
		this.guiaId = guiaId;
		this.idiomaAppId = idiomaAppId;
	}

	@Id

	@Column(name = "TIPO_LENGUA_INDIGENA_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getTipoLenguaIndigenaId() {
		return this.tipoLenguaIndigenaId;
	}

	public void setTipoLenguaIndigenaId(Integer tipoLenguaIndigenaId) {
		this.tipoLenguaIndigenaId = tipoLenguaIndigenaId;
	}

	@Column(name = "CVE", nullable = false, length = 20)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "GUIA_ID", precision = 22, scale = 0)
	public Integer getGuiaId() {
		return this.guiaId;
	}

	public void setGuiaId(Integer guiaId) {
		this.guiaId = guiaId;
	}

	@Column(name = "IDIOMA_APP_ID", precision = 22, scale = 0)
	public Integer getIdiomaAppId() {
		return this.idiomaAppId;
	}

	public void setIdiomaAppId(Integer idiomaAppId) {
		this.idiomaAppId = idiomaAppId;
	}

//	@OneToOne(mappedBy="nomCatTipoLenguaIndigena")
//	public PacPaciente getPacPaciente() {
//		return pacPaciente;
//	}
//
//	public void setPacPaciente(PacPaciente pacPaciente) {
//		this.pacPaciente = pacPaciente;
//	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nomCatTipoLenguaIndigena")
	public Set<PacPaciente> getPacPacientes() {
		return pacPacientes;
	}


	public void setPacPacientes(Set<PacPaciente> pacPacientes) {
		this.pacPacientes = pacPacientes;
	}



}
