package hts.backend.entity;
// Generated 28/03/2017 04:33:43 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PacConvenioDetalle generated by hbm2java
 */
@Entity
@Table(name = "pac_convenio_detalle")
public class PacConvenioDetalle implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private int convenioDetalleId;
	private NomPrductoPrestacion nomPrductoPrestacion;
	private PacConvenioAseguradora pacConvenioAseguradora;
	private Date fechaRegistro;
	private String usuarioRegistra;
	private Set<PacConvenioDetalleEvento> pacConvenioDetalleEventos = new HashSet<PacConvenioDetalleEvento>(0);

	public PacConvenioDetalle() {
	}

	public PacConvenioDetalle(int convenioDetalleId, Date fechaRegistro, String usuarioRegistra) {
		this.convenioDetalleId = convenioDetalleId;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
	}

	public PacConvenioDetalle(int convenioDetalleId, NomPrductoPrestacion nomPrductoPrestacion,
							  PacConvenioAseguradora pacConvenioAseguradora, Date fechaRegistro, String usuarioRegistra,
							  Set<PacConvenioDetalleEvento> pacConvenioDetalleEventos) {
		this.convenioDetalleId = convenioDetalleId;
		this.nomPrductoPrestacion = nomPrductoPrestacion;
		this.pacConvenioAseguradora = pacConvenioAseguradora;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
		this.pacConvenioDetalleEventos = pacConvenioDetalleEventos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CONVENIO_DETALLE_ID", unique = true, nullable = false, precision = 22)
	public int getConvenioDetalleId() {
		return this.convenioDetalleId;
	}

	public void setConvenioDetalleId(int convenioDetalleId) {
		this.convenioDetalleId = convenioDetalleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCTO_PRESTACION_ID")
	public NomPrductoPrestacion getNomPrductoPrestacion() {
		return this.nomPrductoPrestacion;
	}

	public void setNomPrductoPrestacion(NomPrductoPrestacion nomPrductoPrestacion) {
		this.nomPrductoPrestacion = nomPrductoPrestacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CONVENIO_ASEGURADORA_ID")
	public PacConvenioAseguradora getPacConvenioAseguradora() {
		return this.pacConvenioAseguradora;
	}

	public void setPacConvenioAseguradora(PacConvenioAseguradora pacConvenioAseguradora) {
		this.pacConvenioAseguradora = pacConvenioAseguradora;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pacConvenioDetalle")
	public Set<PacConvenioDetalleEvento> getPacConvenioDetalleEventos() {
		return this.pacConvenioDetalleEventos;
	}

	public void setPacConvenioDetalleEventos(Set<PacConvenioDetalleEvento> pacConvenioDetalleEventos) {
		this.pacConvenioDetalleEventos = pacConvenioDetalleEventos;
	}
}
