package hts.backend.entity;


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import hts.backend.entity.FacValidacionEvento;
import hts.backend.entity.FacturacionEvento;
import hts.backend.entity.PacAseguradora;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

//import java.util.HashSet;
//import java.util.Set;
//import javax.persistence.OneToMany;

/**
 * PacConvenioAseguradora generated by hbm2java
 */
@Entity
@Table(name = "pac_convenio_aseguradora")
public class PacConvenioAseguradora implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private int convenioAseguradoraId;
	@JsonIgnore
	private CoreAseguradoraHospital coreAseguradoraHospital;
	private String cve;
	private String nombre;
	private String descripcion;
	private Date fechaInicio;
	private Date fechaFin;
	private int estatus;
	private int valorDefault;
	private Date fechaRegistro;
	private String usuarioRegistra;
	@JsonIgnore
	private Set<PacConvenioDetalle> pacConvenioDetalles = new HashSet<PacConvenioDetalle>(0);
	@JsonIgnore
	private Set<PacAseguradora> pacAseguradoras = new HashSet<PacAseguradora>(0);
	@JsonIgnore
	private Set<FacturacionEvento> facturacionEventosByConvenioAseguradoraId;
	@JsonIgnore
	private Set<TrsNseUnicaOcasion> trsNseUnicaOcasion = new HashSet<TrsNseUnicaOcasion>(0);
	@JsonIgnore
	private Set<FacValidacionEvento> facValidacionEventosByConvenioAseguradoraId;

	@JsonManagedReference(value = "condConvAsegToCondEcon")
	private Set<TrsCondicionesEconomicas> trsCondicionesEconomicas = new HashSet<TrsCondicionesEconomicas>(0);


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CONVENIO_ASEGURADORA_ID", unique = true, nullable = false, precision = 22)
	public int getConvenioAseguradoraId() {
		return this.convenioAseguradoraId;
	}

	public void setConvenioAseguradoraId(int convenioAseguradoraId) {
		this.convenioAseguradoraId = convenioAseguradoraId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ASEGURADORA_HOSPITAL_ID")
	public CoreAseguradoraHospital getCoreAseguradoraHospital() {
		return this.coreAseguradoraHospital;
	}

	public void setCoreAseguradoraHospital(CoreAseguradoraHospital coreAseguradoraHospital) {
		this.coreAseguradoraHospital = coreAseguradoraHospital;
	}

	@Column(name = "CVE", nullable = false, length = 10)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_INICIO", nullable = false, length = 7)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_FIN", length = 7)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "ESTATUS", nullable = false, precision = 22)
	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	@Column(name = "VALOR_DEFAULT", nullable = false, precision = 22)
	public int getValorDefault() {
		return this.valorDefault;
	}

	public void setValorDefault(int valorDefault) {
		this.valorDefault = valorDefault;
	}

	//@Column(name = "FECHA_REGISTRO", nullable = false, length = 18)
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}


	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pacConvenioAseguradora")
	public Set<PacConvenioDetalle> getPacConvenioDetalles() {
		return this.pacConvenioDetalles;
	}

	public void setPacConvenioDetalles(Set<PacConvenioDetalle> pacConvenioDetalles) {
		this.pacConvenioDetalles = pacConvenioDetalles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pacConvenioAseguradora")
	public Set<PacAseguradora> getPacAseguradoras() {
		return pacAseguradoras;
	}

	public void setPacAseguradoras(Set<PacAseguradora> pacAseguradoras) {
		this.pacAseguradoras = pacAseguradoras;
	}


	@OneToMany(mappedBy = "pacConvenioAseguradoraByConvenioAseguradoraId")
	public Set<FacturacionEvento> getFacturacionEventosByConvenioAseguradoraId() {
		return facturacionEventosByConvenioAseguradoraId;
	}

	public void setFacturacionEventosByConvenioAseguradoraId(Set<FacturacionEvento> facturacionEventosByConvenioAseguradoraId) {
		this.facturacionEventosByConvenioAseguradoraId = facturacionEventosByConvenioAseguradoraId;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pacConvenioAseguradora")
	public Set<TrsCondicionesEconomicas> getTrsCondicionesEconomicas() {
		return trsCondicionesEconomicas;
	}

	public void setTrsCondicionesEconomicas(Set<TrsCondicionesEconomicas> trsCondicionesEconomicas) {
		this.trsCondicionesEconomicas = trsCondicionesEconomicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pacConvenioAseguradora")
	public Set<TrsNseUnicaOcasion> getTrsNseUnicaOcasion() {
		return trsNseUnicaOcasion;
	}

	public void setTrsNseUnicaOcasion(Set<TrsNseUnicaOcasion> trsNseUnicaOcasion) {
		this.trsNseUnicaOcasion = trsNseUnicaOcasion;
	}

	@OneToMany(mappedBy = "pacConvenioAseguradoraByConvenioAseguradoraId")
	public Set<FacValidacionEvento> getFacValidacionEventosByConvenioAseguradoraId() {
		return facValidacionEventosByConvenioAseguradoraId;
	}

	public void setFacValidacionEventosByConvenioAseguradoraId(Set<FacValidacionEvento> facValidacionEventosByConvenioAseguradoraId) {
		this.facValidacionEventosByConvenioAseguradoraId = facValidacionEventosByConvenioAseguradoraId;
	}
}
