package hts.backend.entity;
//Generated 5/04/2017 05:49:23 PM by Hibernate Tools 5.2.0.Beta1

import hts.backend.entity.NomCatCodigoPostal;
import hts.backend.entity.NomCatEntidades;
import hts.backend.entity.NomCatMunicipio;
import hts.backend.entity.NomCatPaises;

import javax.persistence.*;
import java.util.Date;

/**
 * PacDetalleFiscalPagadorAso generated by hbm2java
 */
@Entity
@Table(name = "pac_detalle_fiscal_pagador_aso")
public class PacDetalleFiscalPagadorAso implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private int detalleFiscalPagadorAsoId;
	private PacPagadorAsociado pacPagadorAsociado;
	private String rfc;
	private String calle;
	private String noInt;
	private String noExt;
	private String colonia;
	private NomCatPaises nomCatPaises;
	private NomCatEntidades nomCatEntidades;
	private NomCatMunicipio nomCatMunicipio;
	private NomCatCodigoPostal nomCatCodigoPostal;
	private Date fechaRegistro;
	private String usuarioRegistra;

	public PacDetalleFiscalPagadorAso() {
	}


	public PacDetalleFiscalPagadorAso(int detalleFiscalPagadorAsoId, PacPagadorAsociado pacPagadorAsociado, String rfc,
									  String calle, String noInt, String noExt, String colonia, NomCatPaises nomCatPaises,
									  NomCatEntidades nomCatEntidades, NomCatMunicipio nomCatMunicipio, NomCatCodigoPostal nomCatCodigoPostal,
									  Date fechaRegistro, String usuarioRegistra) {

		this.detalleFiscalPagadorAsoId = detalleFiscalPagadorAsoId;
		this.pacPagadorAsociado = pacPagadorAsociado;
		this.rfc = rfc;
		this.calle = calle;
		this.noInt = noInt;
		this.noExt = noExt;
		this.colonia = colonia;
		this.nomCatPaises = nomCatPaises;
		this.nomCatEntidades = nomCatEntidades;
		this.nomCatMunicipio = nomCatMunicipio;
		this.nomCatCodigoPostal = nomCatCodigoPostal;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "DETALLE_FISCAL_PAGADOR_ASO_ID", unique = true, nullable = false, precision = 22)
	public int getDetalleFiscalPagadorAsoId() {
		return this.detalleFiscalPagadorAsoId;
	}

	public void setDetalleFiscalPagadorAsoId(int detalleFiscalPagadorAsoId) {
		this.detalleFiscalPagadorAsoId = detalleFiscalPagadorAsoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAGADOR_ASOCIADO_ID")
	public PacPagadorAsociado getPacPagadorAsociado() {
		return this.pacPagadorAsociado;
	}

	public void setPacPagadorAsociado(PacPagadorAsociado pacPagadorAsociado) {
		this.pacPagadorAsociado = pacPagadorAsociado;
	}

	@Column(name = "RFC", nullable = false, length = 20)
	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	@Column(name = "CALLE", nullable = false, length = 80)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "NO_INT", length = 10)
	public String getNoInt() {
		return this.noInt;
	}

	public void setNoInt(String noInt) {
		this.noInt = noInt;
	}

	@Column(name = "NO_EXT", length = 10)
	public String getNoExt() {
		return this.noExt;
	}

	public void setNoExt(String noExt) {
		this.noExt = noExt;
	}

	@Column(name = "COLONIA", length = 10)
	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAIS_ID")
	public NomCatPaises getNomCatPaises() {
		return nomCatPaises;
	}


	public void setNomCatPaises(NomCatPaises nomCatPaises) {
		this.nomCatPaises = nomCatPaises;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ENTIDAD_ID")
	public NomCatEntidades getNomCatEntidades() {
		return nomCatEntidades;
	}


	public void setNomCatEntidades(NomCatEntidades nomCatEntidades) {
		this.nomCatEntidades = nomCatEntidades;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MUNICIPIO_ID")
	public NomCatMunicipio getNomCatMunicipio() {
		return nomCatMunicipio;
	}


	public void setNomCatMunicipio(NomCatMunicipio nomCatMunicipio) {
		this.nomCatMunicipio = nomCatMunicipio;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_POSTAL_ID")
	public NomCatCodigoPostal getNomCatCodigoPostal() {
		return nomCatCodigoPostal;
	}


	public void setNomCatCodigoPostal(NomCatCodigoPostal nomCatCodigoPostal) {
		this.nomCatCodigoPostal = nomCatCodigoPostal;
	}
}
