package hts.backend.entity;
// Generated 15/05/2017 04:24:20 PM by Hibernate Tools 5.2.1.Final

import hts.backend.entity.CatImpedimento;
import hts.backend.entity.PacPaciente;

import javax.persistence.*;
import java.util.Date;

/**
 * PacImpedimentoPaciente generated by hbm2java
 */
@Entity
@Table(name = "pac_impedimento_paciente")
public class PacImpedimentoPaciente implements java.io.Serializable {

	private Integer impedimentoPacienteId;
	private PacPaciente pacPaciente;
	private CatImpedimento catImpedimento;
	private Date fechaInicial;
	private Date fechaFinal;
	private String observaciones;
	private Date fechaRegistro;
	private String usaurioRegistro;

	public PacImpedimentoPaciente() {
	}


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "IMPEDIMENTO_PACIENTE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getImpedimentoPacienteId() {
		return this.impedimentoPacienteId;
	}

	public void setImpedimentoPacienteId(Integer impedimentoPacienteId) {
		this.impedimentoPacienteId = impedimentoPacienteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PACIENTE", nullable = false)
	public PacPaciente getPacPaciente() {
		return this.pacPaciente;
	}

	public void setPacPaciente(PacPaciente pacPaciente) {
		this.pacPaciente = pacPaciente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IMPEDIMENTO_ID", nullable = false)
	public CatImpedimento getCatImpedimento() {
		return this.catImpedimento;
	}

	public void setCatImpedimento(CatImpedimento catImpedimento) {
		this.catImpedimento = catImpedimento;
	}

	@Column(name = "FECHA_INICIAL", nullable = false, length = 7)
	public Date getFechaInicial() {
		return this.fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	@Column(name = "FECHA_FINAL", nullable = false, length = 7)
	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	@Column(name = "OBSERVACIONES", nullable = false, length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsaurioRegistro() {
		return this.usaurioRegistro;
	}

	public void setUsaurioRegistro(String usaurioRegistro) {
		this.usaurioRegistro = usaurioRegistro;
	}

}
