package hts.backend.entity;

import hts.backend.entity.PacPaciente;

import javax.persistence.*;
import java.util.Date;

/**
 * PacPagadorAsociadoPaciente generated by hbm2java
 */
@Entity
@Table(name = "pac_pagador_asociado_paciente")
public class PacPagadorAsociadoPaciente implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private int pagadorAsociadoPacienteId;
	private PacPaciente pacPaciente;
	private PacPagadorAsociado pacPagadorAsociado;
	private Date fechaRegistro;
	private String usuarioRegistra;

	public PacPagadorAsociadoPaciente() {
	}

	public PacPagadorAsociadoPaciente(int pagadorAsociadoPacienteId, Date fechaRegistro,
									  String usuarioRegistra) {
		this.pagadorAsociadoPacienteId = pagadorAsociadoPacienteId;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
	}

	public PacPagadorAsociadoPaciente(int pagadorAsociadoPacienteId, PacPaciente pacPaciente,
									  PacPagadorAsociado pacPagadorAsociado, Date fechaRegistro, String usuarioRegistra) {
		this.pagadorAsociadoPacienteId = pagadorAsociadoPacienteId;
		this.pacPaciente = pacPaciente;
		this.pacPagadorAsociado = pacPagadorAsociado;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistra = usuarioRegistra;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "PAGADOR_ASOCIADO_PACIENTE_ID", unique = true, nullable = false, precision = 22)
	public int getPagadorAsociadoPacienteId() {
		return this.pagadorAsociadoPacienteId;
	}

	public void setPagadorAsociadoPacienteId(int pagadorAsociadoPacienteId) {
		this.pagadorAsociadoPacienteId = pagadorAsociadoPacienteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PACIENTE")
	public PacPaciente getPacPaciente() {
		return this.pacPaciente;
	}

	public void setPacPaciente(PacPaciente pacPaciente) {
		this.pacPaciente = pacPaciente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAGADOR_ASOCIADO_ID")
	public PacPagadorAsociado getPacPagadorAsociado() {
		return this.pacPagadorAsociado;
	}

	public void setPacPagadorAsociado(PacPagadorAsociado pacPagadorAsociado) {
		this.pacPagadorAsociado = pacPagadorAsociado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioRegistra() {
		return this.usuarioRegistra;
	}

	public void setUsuarioRegistra(String usuarioRegistra) {
		this.usuarioRegistra = usuarioRegistra;
	}
}
