package hts.backend.entity;
// Generated 28/03/2017 12:44:07 PM by Hibernate Tools 5.2.1.Final


import hts.backend.entity.AdmPersonal;
import hts.backend.entity.CatServEspecialidad;
import hts.backend.entity.AdmCatTipoConsulta;

import javax.persistence.*;
import java.util.Date;


/**
 * PermisosCitas generated by hbm2java
 */
@Entity
@Table(name = "permisos_citas")
public class PermisosCitas implements java.io.Serializable {

	/**
	 *
	 */
	private static long serialVersionUID = 1L;
	private Integer permisosCitasId;
	private CatServEspecialidad catServEspecialidadByServEspecialidadId2;
	private CatServEspecialidad catServEspecialidadByServEspecialidadId;
	private AdmPersonal admProfSaludGralByAdmPersonalId2;
	private AdmPersonal admProfSaludGralByAdmPersonalId;
	private String usuarioRegistro;
	private Date fechaRegistro;
	private Integer estatus;
	private Integer hospitalId;

	public PermisosCitas() {
	}

	public PermisosCitas(Integer permisosCitasId) {
		this.permisosCitasId = permisosCitasId;
	}

	public PermisosCitas(Integer permisosCitasId,
						 CatServEspecialidad catServEspecialidadByServEspecialidadId2,
						 CatServEspecialidad catServEspecialidadByServEspecialidadId,
						 AdmPersonal admProfSaludGralByAdmPersonalId2,
						 AdmPersonal admProfSaludGralByAdmPersonalId, String usuarioRegistro, Date fechaRegistro,
						 Integer estatus, Integer hospitalId) {
		this.permisosCitasId = permisosCitasId;
		this.catServEspecialidadByServEspecialidadId2 = catServEspecialidadByServEspecialidadId2;
		this.catServEspecialidadByServEspecialidadId = catServEspecialidadByServEspecialidadId;
		this.admProfSaludGralByAdmPersonalId2 = admProfSaludGralByAdmPersonalId2;
		this.admProfSaludGralByAdmPersonalId = admProfSaludGralByAdmPersonalId;
		this.usuarioRegistro = usuarioRegistro;
		this.fechaRegistro = fechaRegistro;
		this.estatus = estatus;
		this.hospitalId = hospitalId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "PERMISOS_CITAS_ID", unique = true, nullable = false, precision = 22)
	public Integer getPermisosCitasId() {
		return this.permisosCitasId;
	}

	public void setPermisosCitasId(Integer permisosCitasId) {
		this.permisosCitasId = permisosCitasId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_ESPECIALIDAD_ID2")
	public CatServEspecialidad getCatServEspecialidadByServEspecialidadId2() {
		return this.catServEspecialidadByServEspecialidadId2;
	}

	public void setCatServEspecialidadByServEspecialidadId2(
			CatServEspecialidad catServEspecialidadByServEspecialidadId2) {
		this.catServEspecialidadByServEspecialidadId2 = catServEspecialidadByServEspecialidadId2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_ESPECIALIDAD_ID")
	public CatServEspecialidad getCatServEspecialidadByServEspecialidadId() {
		return this.catServEspecialidadByServEspecialidadId;
	}

	public void setCatServEspecialidadByServEspecialidadId(CatServEspecialidad catServEspecialidadByServEspecialidadId) {
		this.catServEspecialidadByServEspecialidadId = catServEspecialidadByServEspecialidadId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADM_PROF_SALUD_GRAL_ID2")
	public AdmPersonal getAdmProfSaludGralByAdmPersonalId2() {
		return this.admProfSaludGralByAdmPersonalId2;
	}

	public void setAdmProfSaludGralByAdmPersonalId2(AdmPersonal admProfSaludGralByAdmPersonalId2) {
		this.admProfSaludGralByAdmPersonalId2 = admProfSaludGralByAdmPersonalId2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADM_PROF_SALUD_GRAL_ID")
	public AdmPersonal getAdmProfSaludGralByAdmPersonalId() {
		return this.admProfSaludGralByAdmPersonalId;
	}

	public void setAdmProfSaludGralByAdmPersonalId(AdmPersonal admProfSaludGralByAdmPersonalId) {
		this.admProfSaludGralByAdmPersonalId = admProfSaludGralByAdmPersonalId;
	}

	@Column(name = "USUARIO_REGISTRO", length = 20)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "ESTATUS", precision = 22)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@Column(name = "HOSPITAL_ID", precision = 22)
	public Integer getHospitalId() {
		return hospitalId;
	}

	public void setHospitalId(Integer hospitalId) {
		this.hospitalId = hospitalId;
	}
}
