package hts.backend.entity;
// Generated 30/03/2017 06:46:44 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.*;
import java.util.Date;

/**
 * PrestacionTipoServesp generated by hbm2java
 */
@Entity
@Table(name = "prestacion_tipo_servesp")
public class PrestacionTipoServesp implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer prestacionTipoServespId;
	private NomPrductoPrestacion nomPrductoPrestacion;
	private NomCatTipoPrestacion1 nomCatTipoPrestacion1;
	private CatServEspecialidad catServEspecialidad;
	private AdmHospital admHospital;
	private Date fechaRegistro;
	private String usuarioRegistro;

	public PrestacionTipoServesp() {
	}

	public PrestacionTipoServesp(Integer prestacionTipoServespId, NomPrductoPrestacion nomPrductoPrestacion, CatServEspecialidad catServEspecialidad, AdmHospital admHospital, Integer tipoPrestacion1Id, Date fechaRegistro, String usuarioRegistro) {
		this.prestacionTipoServespId = prestacionTipoServespId;
		this.nomPrductoPrestacion = nomPrductoPrestacion;
		this.catServEspecialidad = catServEspecialidad;
		this.admHospital = admHospital;
		this.fechaRegistro = fechaRegistro;
		this.usuarioRegistro = usuarioRegistro;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "PRESTACION_TIPO_SERVESP_ID", unique = true, nullable = false, precision = 22)
	public Integer getPrestacionTipoServespId() {
		return this.prestacionTipoServespId;
	}

	public void setPrestacionTipoServespId(Integer prestacionTipoServespId) {
		this.prestacionTipoServespId = prestacionTipoServespId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCTO_PRESTACION_ID", nullable = false)
	public NomPrductoPrestacion getNomPrductoPrestacion() {
		return this.nomPrductoPrestacion;
	}

	public void setNomPrductoPrestacion(NomPrductoPrestacion nomPrductoPrestacion) {
		this.nomPrductoPrestacion = nomPrductoPrestacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_PRESTACION1_ID", nullable = false)
	public NomCatTipoPrestacion1 getNomCatTipoPrestacion1() {
		return this.nomCatTipoPrestacion1;
	}

	public void setNomCatTipoPrestacion1(NomCatTipoPrestacion1 nomCatTipoPrestacion1) {
		this.nomCatTipoPrestacion1 = nomCatTipoPrestacion1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERV_ESPECIALIDAD_ID", nullable = false)
	public CatServEspecialidad getCatServEspecialidad() {
		return this.catServEspecialidad;
	}

	public void setCatServEspecialidad(CatServEspecialidad catServEspecialidad) {
		this.catServEspecialidad = catServEspecialidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HOSPITAL_ID", nullable = false)
	public AdmHospital getAdmHospital() {
		return this.admHospital;
	}

	public void setAdmHospital(AdmHospital admHospital) {
		this.admHospital = admHospital;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 50)
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}
}
