// default package
// Generated 22/08/2016 11:13:44 AM by Hibernate Tools 5.1.0.Beta1
package hts.backend.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import java.util.Date;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
@Entity
@Deprecated
@Table(name = "roles")
public class Roles implements java.io.Serializable {


	private Integer roleId;
	private String descripcion;
	private Integer usuarioCambio;
	private Integer usuarioAlta;
	private Date fechaAlta;
	private Date fechaModifica;
	@JsonIgnore
	private Set<Usuario> usuarios;

	public Roles() {
	}

	public Roles(Integer roleId) {
		this.roleId = roleId;
	}

	public Roles(Integer roleId, String descripcion, Integer usuarioCambio, Integer usuarioAlta,
				 Date fechaAlta, Date fechaModifica, Set<Usuario> usuarios) {
		this.roleId = roleId;
		this.descripcion = descripcion;
		this.usuarioCambio = usuarioCambio;
		this.usuarioAlta = usuarioAlta;
		this.fechaAlta = fechaAlta;
		this.fechaModifica = fechaModifica;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ROLE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "DESCRIPCION", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "USUARIO_CAMBIO", precision = 22, scale = 0)
	public Integer getUsuarioCambio() {
		return this.usuarioCambio;
	}

	public void setUsuarioCambio(Integer usuarioCambio) {
		this.usuarioCambio = usuarioCambio;
	}

	@Column(name = "USUARIO_ALTA", precision = 22, scale = 0)
	public Integer getUsuarioAlta() {
		return this.usuarioAlta;
	}

	public void setUsuarioAlta(Integer usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_ALTA", length = 7)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_MODIFICA", length = 7)
	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}
}
