package hts.backend.entity;

// Generated 24/02/2017 07:59:12 PM by Hibernate Tools 5.2.0.CR1

import org.springframework.security.core.context.SecurityContextHolder;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name = "telefono")
public class Telefono implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer telefonoId;
	private CatTipoTelefono catTipoTelefono;
	private Integer tipoTelefonoId;
	private String telefono;
	private Integer status;
	private String cve;
	private String usuarioCve;
	private Date fechaRegistro;
	private Set<AgenteTelefono> agenteTelefonos = new HashSet<AgenteTelefono>(0);

	public Telefono() {
	}

	// Constructor para registro de teléfonos
	public Telefono(Integer tipoTelefonoId, String telefono, String cve) {
		this.tipoTelefonoId = tipoTelefonoId;
		this.telefono = telefono;
		this.cve = cve;

		this.status = 1;
		this.usuarioCve = SecurityContextHolder.getContext().getAuthentication().getName();
		this.fechaRegistro = new Date();
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "TELEFONO_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getTelefonoId() {
		return this.telefonoId;
	}

	public void setTelefonoId(Integer telefonoId) {
		this.telefonoId = telefonoId;
	}


	@Column(name = "TELEFONO", nullable = false, length = 12)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}


	@Column(name = "ESTATUS", nullable = false, precision = 22, scale = 0)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}


	@Column(name = "CVE", length = 50)
	public String getCve() {
		return this.cve;
	}

	public void setCve(String cve) {
		this.cve = cve;
	}


	@Column(name = "USUARIO_REGISTRO", nullable = false, length = 20)
	public String getUsuarioCve() {
		return this.usuarioCve;
	}

	public void setUsuarioCve(String usuarioCve) {
		this.usuarioCve = usuarioCve;
	}


	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGISTRO", nullable = false, length = 7)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "telefono")
	public Set<AgenteTelefono> getAgenteTelefonos() {
		return this.agenteTelefonos;
	}

	public void setAgenteTelefonos(Set<AgenteTelefono> agenteTelefonos) {
		this.agenteTelefonos = agenteTelefonos;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_TELEFONO_ID", insertable = false, updatable = false)
	public CatTipoTelefono getCatTipoTelefono() {
		return this.catTipoTelefono;
	}

	public void setCatTipoTelefono(CatTipoTelefono catTipoTelefono) {
		this.catTipoTelefono = catTipoTelefono;
	}


	@Column(name = "TIPO_TELEFONO_ID", nullable = false)
	public Integer getTipoTelefonoId() {
		return tipoTelefonoId;
	}

	public void setTipoTelefonoId(Integer tipoTelefonoId) {
		this.tipoTelefonoId = tipoTelefonoId;
	}
}
