// default package
// Generated 22/08/2016 11:13:44 AM by Hibernate Tools 5.1.0.Beta1
package hts.backend.entity;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Deprecated
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 3099407101269548480L;
	private Integer userId;
	private Roles roles;
	private String username;
	private String password;
	private Integer usuarioCambio;
	private Integer usuarioAlta;
	private Date fechaAlta;
	private Date fechaModifica;
	private String nombre;
	private String a_paterno;
	private String a_materno;
	private String mail;
	private String telefono;
	private Integer extension;
	private Integer usuarioNuevo;
	private Integer activo;




	public Usuario() {
	}

	public Usuario(Integer userId) {
		this.userId = userId;
	}

	public Usuario(Integer userId, Roles roles, String username, String password, Integer usuarioCambio,
			Integer usuarioAlta, Date fechaAlta, Date fechaModifica, String nombre, String a_paterno,
			String a_materno, String mail, String telefono, Integer extension) {
		this.userId = userId;
		this.roles = roles;
		this.username = username;
		this.password = password;
		this.usuarioCambio = usuarioCambio;
		this.usuarioAlta = usuarioAlta;
		this.fechaAlta = fechaAlta;
		this.fechaModifica = fechaModifica;
		this.nombre = nombre;
		this.a_paterno = a_paterno;
		this.a_materno = a_materno;
		this.mail = mail;
		this.telefono = telefono;
		this.extension = extension;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "USER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID")
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@Column(name = "USERNAME")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "USUARIO_CAMBIO", precision = 22, scale = 0)
	public Integer getUsuarioCambio() {
		return this.usuarioCambio;
	}

	public void setUsuarioCambio(Integer usuarioCambio) {
		this.usuarioCambio = usuarioCambio;
	}

	@Column(name = "USUARIO_ALTA", precision = 22, scale = 0)
	public Integer getUsuarioAlta() {
		return this.usuarioAlta;
	}

	public void setUsuarioAlta(Integer usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_ALTA", length = 7)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_VIGENCIA", length = 7)
	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	/**
	 * @return the nombre
	 */
	@Column(name = "NOMBRE")
	public String getNombre() {
		return nombre;
	}

	/**
	 * @param nombre the nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * @return the a_paterno
	 */
	@Column(name = "A_PATERNO")
	public String getA_paterno() {
		return a_paterno;
	}

	/**
	 * @param a_paterno the a_paterno to set
	 */
	public void setA_paterno(String a_paterno) {
		this.a_paterno = a_paterno;
	}

	/**
	 * @return the a_materno
	 */
	@Column(name = "A_MATERNO")
	public String getA_materno() {
		return a_materno;
	}

	/**
	 * @param a_materno the a_materno to set
	 */
	public void setA_materno(String a_materno) {
		this.a_materno = a_materno;
	}

	/**
	 * @return the mail
	 */
	@Column(name = "MAIL")
	public String getMail() {
		return mail;
	}

	/**
	 * @param mail the mail to set
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	/**
	 * @return the telefono
	 */
	@Column(name = "TELEFONO")
	public String getTelefono() {
		return telefono;
	}

	/**
	 * @param telefono the telefono to set
	 */
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	/**
	 * @return the extension
	 */
	@Column(name = "EXTENSION")
	public Integer getExtension() {
		return extension;
	}

	/**
	 * @param extension the extension to set
	 */
	public void setExtension(Integer extension) {
		this.extension = extension;
	}
	@Column(name = "USUARIO_NUEVO")
	public Integer getUsuarioNuevo() {
		return this.usuarioNuevo;
	}

	public void setUsuarioNuevo(Integer usuarioNuevo) {
		this.usuarioNuevo = usuarioNuevo;
	}
	@Column(name = "ACTIVO")
	public Integer getActivo() {
		return activo;
	}
	public void setActivo(Integer activo) {
		this.activo = activo;
	}

}
